#!/usr/bin/env ruby
# frozen_string_literal: true

# Regenerate lib/dommy/internal/ce_reactions_table.rb — every member the specs
# mark [CEReactions] (HTML §4.13.6 "Custom element reactions"), by interface —
# from test/fixtures/webidl/interfaces.json, the specs' own IDL as
# script/build_webidl_fixture.js distills it.
#
#   ruby script/build_ce_reactions_table.rb          # write the file
#   ruby script/build_ce_reactions_table.rb --check  # exit 1 if it is stale
#
# The bridge runs a script's call of one of these members — an operation, an
# attribute's setter, or an interface's [CEReactions] setter / deleter — inside
# a custom element reactions scope (Internal::CEReactions.scope), so the
# reactions it enqueues run when the member returns. A [PutForwards] attribute
# counts when the attribute it forwards to does.

require "json"

module CEReactionsTable
  ROOT = File.expand_path("..", __dir__)
  FIXTURE = File.join(ROOT, "test/fixtures/webidl/interfaces.json")
  OUTPUT = File.join(ROOT, "lib/dommy/internal/ce_reactions_table.rb")

  module_function

  def data
    @data ||= JSON.parse(File.read(FIXTURE))
  end

  # { "Interface" => { "attributes" => [...], "operations" => [...],
  #   "special" => ["setter", "deleter"] } }, members sorted, empty kinds and
  # interfaces left out.
  # A [PutForwards] attribute's assignment is an assignment to the attribute
  # it forwards to (`el.classList = "a"` sets the DOMTokenList's `value`), so
  # it is a [CEReactions] member when that one is.
  def forwards_to_ce_reactions?(member)
    return false unless member["kind"] == "attribute" && member["put_forwards"]

    interface = member["type"].to_s.delete_suffix("?")
    while (record = data["interfaces"][interface])
      target = record["members"].find { |m| m["kind"] == "attribute" && m["name"] == member["put_forwards"] }
      return target["ce_reactions"] if target

      interface = record["inherits"]
    end
    false
  end

  def table
    data["interfaces"].sort.each_with_object({}) do |(name, record), out|
      marked = record["members"].select { |m| (m["ce_reactions"] || forwards_to_ce_reactions?(m)) && !m["static"] }
      next if marked.empty?

      entry = {
        "attributes" => marked.select { |m| m["kind"] == "attribute" }.map { |m| m["name"] },
        "operations" => marked.select { |m| m["kind"] == "operation" && m["name"] }.map { |m| m["name"] },
        "special" => marked.select { |m| m["kind"] == "special" }.map { |m| m["special"] }
      }.transform_values { |names| names.uniq.sort }.reject { |_, names| names.empty? }
      out[name] = entry
    end
  end

  def render
    interfaces = table.map do |name, entry|
      rows = entry.map { |kind, names| "#{' ' * 10}#{kind}: %w[#{names.join(' ')}].freeze" }
      "#{' ' * 8}#{name.inspect} => {\n#{rows.join(",\n")}\n#{' ' * 8}}.freeze"
    end
    header = <<~RUBY
      # frozen_string_literal: true

      # GENERATED by script/build_ce_reactions_table.rb from
      # test/fixtures/webidl/interfaces.json (web-platform-tests #{data['wpt_commit']}).
      # Do not edit by hand: re-run the script after refreshing the fixture.
      #
      # The members each interface marks [CEReactions] (HTML §4.13.6): the
      # operations, the attributes (whose setter carries it) and the special
      # setter / deleter. Internal::CEReactions.member? answers from it.
      module Dommy
        module Internal
          module CEReactions
            TABLE = {
    RUBY
    footer = <<~RUBY
            }.freeze
          end
        end
      end
    RUBY
    "#{header}#{interfaces.join(",\n")}\n#{footer}"
  end
end

if $PROGRAM_NAME == __FILE__
  rendered = CEReactionsTable.render
  if ARGV.include?("--check")
    current = File.exist?(CEReactionsTable::OUTPUT) ? File.read(CEReactionsTable::OUTPUT) : ""
    abort "#{CEReactionsTable::OUTPUT} is stale; re-run #{$PROGRAM_NAME}" unless current == rendered
  else
    File.write(CEReactionsTable::OUTPUT, rendered)
    puts "wrote #{CEReactionsTable::OUTPUT}: #{CEReactionsTable.table.size} interfaces"
  end
end
