#!/usr/bin/env ruby
# frozen_string_literal: true

# Writes lib/dommy/encodings/tables.rb from the Encoding Standard's own data:
#
#   encodings.json          https://encoding.spec.whatwg.org/encodings.json
#   index-<name>.txt        https://encoding.spec.whatwg.org/index-<name>.txt
#                           for each legacy single-byte encoding
#
# Usage: ruby script/build_encoding_tables.rb <dir with those files>
#
# ISO-8859-8-I has no index file of its own; the spec says it shares
# index ISO-8859-8.

require "json"

dir = ARGV[0] or abort "Usage: #{$PROGRAM_NAME} <dir>"
table = JSON.parse(File.read(File.join(dir, "encodings.json")))

labels = {}
single_byte = []
table.each do |section|
  section["encodings"].each do |encoding|
    encoding["labels"].each { |label| labels[label] = encoding["name"] }
    single_byte << encoding["name"] if section["heading"] == "Legacy single-byte encodings"
  end
end

def read_index(path)
  index = Array.new(128)
  File.foreach(path) do |line|
    next if line.start_with?("#") || line.strip.empty?

    pointer, code_point = line.split("\t")
    index[pointer.to_i] = code_point.hex
  end
  index
end

indexes = single_byte.to_h do |name|
  file = name == "ISO-8859-8-I" ? "index-iso-8859-8.txt" : "index-#{name.downcase}.txt"
  [name, read_index(File.join(dir, file))]
end

out = +<<~RUBY
  # frozen_string_literal: true

  # Generated by script/build_encoding_tables.rb from the Encoding Standard's
  # encodings.json and index-*.txt. Do not edit by hand.
  #
  # Spec: https://encoding.spec.whatwg.org/

  module Dommy
    module Encodings
      # Every label the spec knows, lowercased, to the name of its encoding.
      LABELS = {
RUBY
labels.each { |label, name| out << "      #{label.inspect} => #{name.inspect},\n" }
out << <<~RUBY
      }.freeze

      # For each legacy single-byte encoding, the code point of byte 0x80 + i,
      # or nil where the byte has no mapping.
      SINGLE_BYTE_INDEXES = {
RUBY
indexes.each do |name, index|
  out << "      #{name.inspect} => [\n"
  index.each_slice(8) do |slice|
    out << "        " << slice.map { |cp| cp ? format("0x%04X", cp) : "nil" }.join(", ") << ",\n"
  end
  out << "      ].freeze,\n"
end
out << <<~RUBY
      }.freeze
    end
  end
RUBY

target = File.expand_path("../lib/dommy/encodings/tables.rb", __dir__)
File.write(target, out)
puts "wrote #{target}: #{labels.size} labels, #{indexes.size} single-byte indexes"
