#!/usr/bin/env ruby
# frozen_string_literal: true

# Regenerate lib/dommy/internal/idl_reflection_table.rb — every IDL attribute
# the specs mark as REFLECTING a content attribute (HTML §2.6.1), with the
# parameters the IDL gives it — from test/fixtures/webidl/interfaces.json, the
# specs' own IDL as script/build_webidl_fixture.js distills it.
#
#   ruby script/build_idl_reflection_table.rb          # write the file
#   ruby script/build_idl_reflection_table.rb --check  # exit 1 if it is stale
#
# The table is data only: what each entry is DECLARED as (reflect_string,
# reflect_url, reflect_ulong, …) is decided at load time by
# Internal::IdlReflection, which the WebIDL audit shares, together with the
# hand-written overlay for what the IDL cannot say (enumerated keywords,
# supported tokens, prose-only reflections).

require "json"

module IdlReflectionTable
  ROOT = File.expand_path("..", __dir__)
  FIXTURE = File.join(ROOT, "test/fixtures/webidl/interfaces.json")
  OUTPUT = File.join(ROOT, "lib/dommy/internal/idl_reflection_table.rb")

  # The [Reflect*] parameters, in the order they are written out.
  PARAMETERS = %w[attr default range non_negative positive positive_with_fallback].freeze

  module_function

  def data
    @data ||= JSON.parse(File.read(FIXTURE))
  end

  # { "Interface" => { "idlName" => { idl:, shape:, attr:, … } } }, interfaces
  # and members in IDL order.
  def table
    data["interfaces"].sort.each_with_object({}) do |(name, record), out|
      members = record["members"].select { |m| m["kind"] == "attribute" && m["reflect"] && !m["static"] }
      next if members.empty?

      out[name] = members.to_h do |member|
        reflect = member["reflect"]
        entry = {"idl" => member["type"], "shape" => reflect["shape"]}
        PARAMETERS.each { |key| entry[key] = reflect[key] if reflect.key?(key) }
        [member["name"], entry]
      end
    end
  end

  def literal(value)
    case value
    when Array then "#{value.first}..#{value.last}"
    when String then value.inspect
    else value.inspect
    end
  end

  def render_entry(entry)
    parts = ["idl: #{entry['idl'].inspect}", "shape: :#{entry['shape']}"]
    PARAMETERS.each { |key| parts << "#{key}: #{literal(entry[key])}" if entry.key?(key) }
    "{ #{parts.join(', ')} }.freeze"
  end

  def render
    interfaces = table.map do |name, members|
      rows = members.map { |member, entry| "#{' ' * 10}#{member.inspect} => #{render_entry(entry)}" }
      "#{' ' * 8}#{name.inspect} => {\n#{rows.join(",\n")}\n#{' ' * 8}}.freeze"
    end
    header = <<~RUBY
      # frozen_string_literal: true

      # GENERATED by script/build_idl_reflection_table.rb from
      # test/fixtures/webidl/interfaces.json (web-platform-tests #{data['wpt_commit']}).
      # Do not edit by hand: re-run the script after refreshing the fixture.
      #
      # Every IDL attribute the specs mark as reflecting a content attribute
      # (HTML §2.6.1 "Using reflect via IDL extended attributes"): its IDL type,
      # its shape ([Reflect] / [ReflectNonNegative] / [ReflectPositive] /
      # [ReflectPositiveWithFallback] are :plain, [ReflectURL] :url,
      # [ReflectSetter] :setter) and the parameters the IDL gives it — the content
      # attribute when it is not the IDL name lowercased, [ReflectDefault],
      # [ReflectRange] and the sign limits. Internal::IdlReflection turns each
      # entry into a reflect_* declaration.
      module Dommy
        module Internal
          module IdlReflection
            TABLE = {
    RUBY
    footer = <<~RUBY
            }.freeze
          end
        end
      end
    RUBY
    "#{header}#{interfaces.join(",\n")}\n#{footer}"
  end
end

if $PROGRAM_NAME == __FILE__
  rendered = IdlReflectionTable.render
  if ARGV.include?("--check")
    current = File.exist?(IdlReflectionTable::OUTPUT) ? File.read(IdlReflectionTable::OUTPUT) : ""
    abort "#{IdlReflectionTable::OUTPUT} is stale; re-run #{$PROGRAM_NAME}" unless current == rendered
  else
    File.write(IdlReflectionTable::OUTPUT, rendered)
    puts "wrote #{IdlReflectionTable::OUTPUT}: #{IdlReflectionTable.table.sum { |_, m| m.size }} reflected attributes"
  end
end
