# frozen_string_literal: true

# GENERATED by script/build_ce_reactions_table.rb from
# test/fixtures/webidl/interfaces.json (web-platform-tests 863077959ca8c1a7ceecfbe2534b75d2527b9013).
# Do not edit by hand: re-run the script after refreshing the fixture.
#
# The members each interface marks [CEReactions] (HTML §4.13.6): the
# operations, the attributes (whose setter carries it) and the special
# setter / deleter. Internal::CEReactions.member? answers from it.
module Dommy
  module Internal
    module CEReactions
      TABLE = {
        "Attr" => {
          attributes: %w[value].freeze
        }.freeze,
        "CSSKeyframeRule" => {
          attributes: %w[style].freeze
        }.freeze,
        "CSSMarginRule" => {
          attributes: %w[style].freeze
        }.freeze,
        "CSSPageRule" => {
          attributes: %w[style].freeze
        }.freeze,
        "CSSStyleDeclaration" => {
          attributes: %w[cssText].freeze,
          operations: %w[removeProperty setProperty].freeze
        }.freeze,
        "CSSStyleProperties" => {
          attributes: %w[cssFloat].freeze
        }.freeze,
        "CSSStyleRule" => {
          attributes: %w[style].freeze
        }.freeze,
        "CharacterData" => {
          operations: %w[after before remove replaceWith].freeze
        }.freeze,
        "CustomElementRegistry" => {
          operations: %w[define initialize upgrade].freeze
        }.freeze,
        "DOMStringMap" => {
          special: %w[deleter setter].freeze
        }.freeze,
        "DOMTokenList" => {
          attributes: %w[value].freeze,
          operations: %w[add remove replace toggle].freeze
        }.freeze,
        "Document" => {
          attributes: %w[alinkColor bgColor body designMode dir fgColor linkColor title vlinkColor].freeze,
          operations: %w[adoptNode append close createElement createElementNS execCommand importNode moveBefore open prepend replaceChildren write writeln].freeze
        }.freeze,
        "DocumentFragment" => {
          operations: %w[append moveBefore prepend replaceChildren].freeze
        }.freeze,
        "DocumentType" => {
          operations: %w[after before remove replaceWith].freeze
        }.freeze,
        "Element" => {
          attributes: %w[ariaActiveDescendantElement ariaAtomic ariaAutoComplete ariaBrailleLabel ariaBrailleRoleDescription ariaBusy ariaChecked ariaColCount ariaColIndex ariaColIndexText ariaColSpan ariaControlsElements ariaCurrent ariaDescribedByElements ariaDescription ariaDetailsElements ariaDisabled ariaErrorMessageElements ariaExpanded ariaFlowToElements ariaHasPopup ariaHidden ariaInvalid ariaKeyShortcuts ariaLabel ariaLabelledByElements ariaLevel ariaLive ariaModal ariaMultiLine ariaMultiSelectable ariaOrientation ariaOwnsElements ariaPlaceholder ariaPosInSet ariaPressed ariaReadOnly ariaRelevant ariaRequired ariaRoleDescription ariaRowCount ariaRowIndex ariaRowIndexText ariaRowSpan ariaSelected ariaSetSize ariaSort ariaValueMax ariaValueMin ariaValueNow ariaValueText classList className id innerHTML outerHTML role slot].freeze,
          operations: %w[after append before insertAdjacentElement insertAdjacentHTML moveBefore prepend remove removeAttribute removeAttributeNS removeAttributeNode replaceChildren replaceWith setAttribute setAttributeNS setAttributeNode setAttributeNodeNS setHTML setHTMLUnsafe toggleAttribute].freeze
        }.freeze,
        "ElementInternals" => {
          attributes: %w[ariaActiveDescendantElement ariaAtomic ariaAutoComplete ariaBrailleLabel ariaBrailleRoleDescription ariaBusy ariaChecked ariaColCount ariaColIndex ariaColIndexText ariaColSpan ariaControlsElements ariaCurrent ariaDescribedByElements ariaDescription ariaDetailsElements ariaDisabled ariaErrorMessageElements ariaExpanded ariaFlowToElements ariaHasPopup ariaHidden ariaInvalid ariaKeyShortcuts ariaLabel ariaLabelledByElements ariaLevel ariaLive ariaModal ariaMultiLine ariaMultiSelectable ariaOrientation ariaOwnsElements ariaPlaceholder ariaPosInSet ariaPressed ariaReadOnly ariaRelevant ariaRequired ariaRoleDescription ariaRowCount ariaRowIndex ariaRowIndexText ariaRowSpan ariaSelected ariaSetSize ariaSort ariaValueMax ariaValueMin ariaValueNow ariaValueText role].freeze
        }.freeze,
        "HTMLAnchorElement" => {
          attributes: %w[charset coords download hash host hostname href hreflang name password pathname ping port protocol referrerPolicy rel relList rev search shape target text type username].freeze
        }.freeze,
        "HTMLAreaElement" => {
          attributes: %w[alt coords download hash host hostname href hreflang noHref password pathname ping port protocol referrerPolicy rel relList search shape target type username].freeze
        }.freeze,
        "HTMLBRElement" => {
          attributes: %w[clear].freeze
        }.freeze,
        "HTMLBaseElement" => {
          attributes: %w[href target].freeze
        }.freeze,
        "HTMLBodyElement" => {
          attributes: %w[aLink background bgColor link text vLink].freeze
        }.freeze,
        "HTMLButtonElement" => {
          attributes: %w[command commandForElement disabled formAction formEnctype formMethod formNoValidate formTarget name popoverTargetAction popoverTargetElement type value].freeze
        }.freeze,
        "HTMLCanvasElement" => {
          attributes: %w[height width].freeze
        }.freeze,
        "HTMLDListElement" => {
          attributes: %w[compact].freeze
        }.freeze,
        "HTMLDataElement" => {
          attributes: %w[value].freeze
        }.freeze,
        "HTMLDetailsElement" => {
          attributes: %w[name open].freeze
        }.freeze,
        "HTMLDialogElement" => {
          attributes: %w[closedBy open].freeze,
          operations: %w[close requestClose show showModal].freeze
        }.freeze,
        "HTMLDirectoryElement" => {
          attributes: %w[compact].freeze
        }.freeze,
        "HTMLDivElement" => {
          attributes: %w[align].freeze
        }.freeze,
        "HTMLElement" => {
          attributes: %w[accessKey autocapitalize autocorrect autofocus contentEditable dir draggable enterKeyHint headingOffset headingReset hidden inert innerText inputMode lang outerText popover spellcheck style tabIndex title translate writingSuggestions].freeze
        }.freeze,
        "HTMLEmbedElement" => {
          attributes: %w[align height name src type width].freeze
        }.freeze,
        "HTMLFieldSetElement" => {
          attributes: %w[disabled name].freeze
        }.freeze,
        "HTMLFontElement" => {
          attributes: %w[color face size].freeze
        }.freeze,
        "HTMLFormElement" => {
          attributes: %w[acceptCharset action autocomplete encoding enctype method name noValidate rel relList target].freeze,
          operations: %w[reset].freeze
        }.freeze,
        "HTMLFrameElement" => {
          attributes: %w[frameBorder longDesc marginHeight marginWidth name noResize scrolling src].freeze
        }.freeze,
        "HTMLFrameSetElement" => {
          attributes: %w[cols rows].freeze
        }.freeze,
        "HTMLHRElement" => {
          attributes: %w[align color noShade size width].freeze
        }.freeze,
        "HTMLHeadingElement" => {
          attributes: %w[align].freeze
        }.freeze,
        "HTMLHtmlElement" => {
          attributes: %w[version].freeze
        }.freeze,
        "HTMLIFrameElement" => {
          attributes: %w[align allow allowFullscreen frameBorder height loading longDesc marginHeight marginWidth name referrerPolicy sandbox scrolling src srcdoc width].freeze
        }.freeze,
        "HTMLImageElement" => {
          attributes: %w[align alt border controls crossOrigin decoding fetchPriority height hspace isMap loading longDesc lowsrc name referrerPolicy sizes src srcset useMap vspace width].freeze
        }.freeze,
        "HTMLInputElement" => {
          attributes: %w[accept align alpha alt autocomplete colorSpace defaultChecked defaultValue dirName disabled formAction formEnctype formMethod formNoValidate formTarget height max maxLength min minLength multiple name pattern placeholder popoverTargetAction popoverTargetElement readOnly required size src step type useMap value width].freeze
        }.freeze,
        "HTMLLIElement" => {
          attributes: %w[type value].freeze
        }.freeze,
        "HTMLLabelElement" => {
          attributes: %w[htmlFor].freeze
        }.freeze,
        "HTMLLegendElement" => {
          attributes: %w[align].freeze
        }.freeze,
        "HTMLLinkElement" => {
          attributes: %w[as blocking charset crossOrigin disabled fetchPriority href hreflang imageSizes imageSrcset integrity media referrerPolicy rel relList rev sizes target type].freeze
        }.freeze,
        "HTMLMapElement" => {
          attributes: %w[name].freeze
        }.freeze,
        "HTMLMarqueeElement" => {
          attributes: %w[behavior bgColor direction height hspace loop scrollAmount scrollDelay trueSpeed vspace width].freeze
        }.freeze,
        "HTMLMediaElement" => {
          attributes: %w[autoplay controls crossOrigin defaultMuted loading loop preload src].freeze
        }.freeze,
        "HTMLMenuElement" => {
          attributes: %w[compact].freeze
        }.freeze,
        "HTMLMetaElement" => {
          attributes: %w[content httpEquiv media name scheme].freeze
        }.freeze,
        "HTMLMeterElement" => {
          attributes: %w[high low max min optimum value].freeze
        }.freeze,
        "HTMLModElement" => {
          attributes: %w[cite dateTime].freeze
        }.freeze,
        "HTMLOListElement" => {
          attributes: %w[compact reversed start type].freeze
        }.freeze,
        "HTMLObjectElement" => {
          attributes: %w[align archive border code codeBase codeType data declare height hspace name standby type useMap vspace width].freeze
        }.freeze,
        "HTMLOptGroupElement" => {
          attributes: %w[disabled label].freeze
        }.freeze,
        "HTMLOptionElement" => {
          attributes: %w[defaultSelected disabled label text value].freeze
        }.freeze,
        "HTMLOptionsCollection" => {
          attributes: %w[length].freeze,
          operations: %w[add remove].freeze,
          special: %w[setter].freeze
        }.freeze,
        "HTMLOutputElement" => {
          attributes: %w[defaultValue htmlFor name value].freeze
        }.freeze,
        "HTMLParagraphElement" => {
          attributes: %w[align].freeze
        }.freeze,
        "HTMLParamElement" => {
          attributes: %w[name type value valueType].freeze
        }.freeze,
        "HTMLPreElement" => {
          attributes: %w[width].freeze
        }.freeze,
        "HTMLProgressElement" => {
          attributes: %w[max value].freeze
        }.freeze,
        "HTMLQuoteElement" => {
          attributes: %w[cite].freeze
        }.freeze,
        "HTMLScriptElement" => {
          attributes: %w[async blocking charset crossOrigin defer event fetchPriority htmlFor integrity noModule referrerPolicy src text type].freeze
        }.freeze,
        "HTMLSelectElement" => {
          attributes: %w[autocomplete disabled length multiple name required size].freeze,
          operations: %w[add remove].freeze,
          special: %w[setter].freeze
        }.freeze,
        "HTMLSlotElement" => {
          attributes: %w[name].freeze
        }.freeze,
        "HTMLSourceElement" => {
          attributes: %w[height media sizes src srcset type width].freeze
        }.freeze,
        "HTMLStyleElement" => {
          attributes: %w[blocking media type].freeze
        }.freeze,
        "HTMLTableCaptionElement" => {
          attributes: %w[align].freeze
        }.freeze,
        "HTMLTableCellElement" => {
          attributes: %w[abbr align axis bgColor ch chOff colSpan headers height noWrap rowSpan scope vAlign width].freeze
        }.freeze,
        "HTMLTableColElement" => {
          attributes: %w[align ch chOff span vAlign width].freeze
        }.freeze,
        "HTMLTableElement" => {
          attributes: %w[align bgColor border caption cellPadding cellSpacing frame rules summary tFoot tHead width].freeze,
          operations: %w[deleteCaption deleteRow deleteTFoot deleteTHead].freeze
        }.freeze,
        "HTMLTableRowElement" => {
          attributes: %w[align bgColor ch chOff vAlign].freeze,
          operations: %w[deleteCell].freeze
        }.freeze,
        "HTMLTableSectionElement" => {
          attributes: %w[align ch chOff vAlign].freeze,
          operations: %w[deleteRow].freeze
        }.freeze,
        "HTMLTemplateElement" => {
          attributes: %w[htmlFor shadowRootClonable shadowRootCustomElementRegistry shadowRootDelegatesFocus shadowRootMode shadowRootSerializable shadowRootSlotAssignment].freeze
        }.freeze,
        "HTMLTextAreaElement" => {
          attributes: %w[autocomplete cols defaultValue dirName disabled maxLength minLength name placeholder readOnly required rows wrap].freeze
        }.freeze,
        "HTMLTimeElement" => {
          attributes: %w[dateTime].freeze
        }.freeze,
        "HTMLTitleElement" => {
          attributes: %w[text].freeze
        }.freeze,
        "HTMLTrackElement" => {
          attributes: %w[default kind label src srclang].freeze
        }.freeze,
        "HTMLUListElement" => {
          attributes: %w[compact type].freeze
        }.freeze,
        "HTMLVideoElement" => {
          attributes: %w[height playsInline poster width].freeze
        }.freeze,
        "NamedNodeMap" => {
          operations: %w[removeNamedItem removeNamedItemNS setNamedItem setNamedItemNS].freeze
        }.freeze,
        "Node" => {
          attributes: %w[nodeValue textContent].freeze,
          operations: %w[appendChild cloneNode insertBefore normalize removeChild replaceChild].freeze
        }.freeze,
        "Range" => {
          operations: %w[cloneContents createContextualFragment deleteContents extractContents insertNode surroundContents].freeze
        }.freeze,
        "Selection" => {
          operations: %w[deleteFromDocument].freeze
        }.freeze,
        "ShadowRoot" => {
          attributes: %w[innerHTML].freeze,
          operations: %w[setHTML setHTMLUnsafe].freeze
        }.freeze,
        "XSLTProcessor" => {
          operations: %w[transformToDocument transformToFragment].freeze
        }.freeze
      }.freeze
    end
  end
end
