# frozen_string_literal: true

# GENERATED by script/build_event_handlers.rb from
# test/fixtures/webidl/interfaces.json (web-platform-tests 863077959ca8c1a7ceecfbe2534b75d2527b9013).
# Do not edit by hand: re-run the script (`rake webidl:event_handlers`).

module Dommy
  module Internal
    # HTML §8.1.8 event handlers, as the specs' IDL declares them. See
    # Internal::EventHandlers for what reads them.
    module EventHandlerTables
      # Interface -> the event handler IDL attributes it declares itself
      # (its mixins' included, its ancestors' not).
      BY_INTERFACE = {
        "AbortSignal" => %w[
          onabort
        ].freeze,
        "AudioTrackList" => %w[
          onaddtrack onchange onremovetrack
        ].freeze,
        "BroadcastChannel" => %w[
          onmessage onmessageerror
        ].freeze,
        "CloseWatcher" => %w[
          oncancel onclose
        ].freeze,
        "DedicatedWorkerGlobalScope" => %w[
          onmessage onmessageerror
        ].freeze,
        "Document" => %w[
          onabort onanimationcancel onanimationend onanimationiteration onanimationstart onauxclick
          onbeforeinput onbeforematch onbeforetoggle onblur oncancel oncanplay oncanplaythrough
          onchange onclick onclose oncommand oncontextlost oncontextmenu oncontextrestored oncopy
          oncuechange oncut ondblclick ondrag ondragend ondragenter ondragleave ondragover ondragstart
          ondrop ondurationchange onemptied onended onerror onfocus onformdata onfullscreenchange
          onfullscreenerror ongotpointercapture oninput oninvalid onkeydown onkeypress onkeyup onload
          onloadeddata onloadedmetadata onloadstart onlostpointercapture onmousedown onmouseenter
          onmouseleave onmousemove onmouseout onmouseover onmouseup onpaste onpause onplay onplaying
          onpointercancel onpointerdown onpointerenter onpointerleave onpointermove onpointerout
          onpointerover onpointerrawupdate onpointerup onprogress onratechange onreadystatechange
          onreset onresize onscroll onscrollend onsecuritypolicyviolation onseeked onseeking onselect
          onselectionchange onselectstart onslotchange onstalled onsubmit onsuspend ontimeupdate
          ontoggle ontouchcancel ontouchend ontouchmove ontouchstart ontransitioncancel
          ontransitionend ontransitionrun ontransitionstart onvisibilitychange onvolumechange
          onwaiting onwebkitanimationend onwebkitanimationiteration onwebkitanimationstart
          onwebkittransitionend onwheel
        ].freeze,
        "Element" => %w[
          onfullscreenchange onfullscreenerror
        ].freeze,
        "EventSource" => %w[
          onerror onmessage onopen
        ].freeze,
        "FileReader" => %w[
          onabort onerror onload onloadend onloadstart onprogress
        ].freeze,
        "HTMLBodyElement" => %w[
          onafterprint onbeforeprint onbeforeunload onhashchange onlanguagechange onmessage
          onmessageerror onoffline ononline onpagehide onpagereveal onpageshow onpageswap onpopstate
          onrejectionhandled onstorage onunhandledrejection onunload
        ].freeze,
        "HTMLElement" => %w[
          onabort onanimationcancel onanimationend onanimationiteration onanimationstart onauxclick
          onbeforeinput onbeforematch onbeforetoggle onblur oncancel oncanplay oncanplaythrough
          onchange onclick onclose oncommand oncontextlost oncontextmenu oncontextrestored oncopy
          oncuechange oncut ondblclick ondrag ondragend ondragenter ondragleave ondragover ondragstart
          ondrop ondurationchange onemptied onended onerror onfocus onformdata ongotpointercapture
          oninput oninvalid onkeydown onkeypress onkeyup onload onloadeddata onloadedmetadata
          onloadstart onlostpointercapture onmousedown onmouseenter onmouseleave onmousemove
          onmouseout onmouseover onmouseup onpaste onpause onplay onplaying onpointercancel
          onpointerdown onpointerenter onpointerleave onpointermove onpointerout onpointerover
          onpointerrawupdate onpointerup onprogress onratechange onreset onresize onscroll onscrollend
          onsecuritypolicyviolation onseeked onseeking onselect onselectionchange onselectstart
          onslotchange onstalled onsubmit onsuspend ontimeupdate ontoggle ontouchcancel ontouchend
          ontouchmove ontouchstart ontransitioncancel ontransitionend ontransitionrun
          ontransitionstart onvolumechange onwaiting onwebkitanimationend onwebkitanimationiteration
          onwebkitanimationstart onwebkittransitionend onwheel
        ].freeze,
        "HTMLFrameSetElement" => %w[
          onafterprint onbeforeprint onbeforeunload onhashchange onlanguagechange onmessage
          onmessageerror onoffline ononline onpagehide onpagereveal onpageshow onpageswap onpopstate
          onrejectionhandled onstorage onunhandledrejection onunload
        ].freeze,
        "MathMLElement" => %w[
          onabort onanimationcancel onanimationend onanimationiteration onanimationstart onauxclick
          onbeforeinput onbeforematch onbeforetoggle onblur oncancel oncanplay oncanplaythrough
          onchange onclick onclose oncommand oncontextlost oncontextmenu oncontextrestored oncopy
          oncuechange oncut ondblclick ondrag ondragend ondragenter ondragleave ondragover ondragstart
          ondrop ondurationchange onemptied onended onerror onfocus onformdata ongotpointercapture
          oninput oninvalid onkeydown onkeypress onkeyup onload onloadeddata onloadedmetadata
          onloadstart onlostpointercapture onmousedown onmouseenter onmouseleave onmousemove
          onmouseout onmouseover onmouseup onpaste onpause onplay onplaying onpointercancel
          onpointerdown onpointerenter onpointerleave onpointermove onpointerout onpointerover
          onpointerrawupdate onpointerup onprogress onratechange onreset onresize onscroll onscrollend
          onsecuritypolicyviolation onseeked onseeking onselect onselectionchange onselectstart
          onslotchange onstalled onsubmit onsuspend ontimeupdate ontoggle ontouchcancel ontouchend
          ontouchmove ontouchstart ontransitioncancel ontransitionend ontransitionrun
          ontransitionstart onvolumechange onwaiting onwebkitanimationend onwebkitanimationiteration
          onwebkitanimationstart onwebkittransitionend onwheel
        ].freeze,
        "MediaQueryList" => %w[
          onchange
        ].freeze,
        "MessagePort" => %w[
          onclose onmessage onmessageerror
        ].freeze,
        "Navigation" => %w[
          oncurrententrychange onnavigate onnavigateerror onnavigatesuccess
        ].freeze,
        "NavigationHistoryEntry" => %w[
          ondispose
        ].freeze,
        "Notification" => %w[
          onclick onclose onerror onshow
        ].freeze,
        "OffscreenCanvas" => %w[
          oncontextlost oncontextrestored
        ].freeze,
        "SVGElement" => %w[
          onabort onanimationcancel onanimationend onanimationiteration onanimationstart onauxclick
          onbeforeinput onbeforematch onbeforetoggle onblur oncancel oncanplay oncanplaythrough
          onchange onclick onclose oncommand oncontextlost oncontextmenu oncontextrestored oncopy
          oncuechange oncut ondblclick ondrag ondragend ondragenter ondragleave ondragover ondragstart
          ondrop ondurationchange onemptied onended onerror onfocus onformdata ongotpointercapture
          oninput oninvalid onkeydown onkeypress onkeyup onload onloadeddata onloadedmetadata
          onloadstart onlostpointercapture onmousedown onmouseenter onmouseleave onmousemove
          onmouseout onmouseover onmouseup onpaste onpause onplay onplaying onpointercancel
          onpointerdown onpointerenter onpointerleave onpointermove onpointerout onpointerover
          onpointerrawupdate onpointerup onprogress onratechange onreset onresize onscroll onscrollend
          onsecuritypolicyviolation onseeked onseeking onselect onselectionchange onselectstart
          onslotchange onstalled onsubmit onsuspend ontimeupdate ontoggle ontouchcancel ontouchend
          ontouchmove ontouchstart ontransitioncancel ontransitionend ontransitionrun
          ontransitionstart onvolumechange onwaiting onwebkitanimationend onwebkitanimationiteration
          onwebkitanimationstart onwebkittransitionend onwheel
        ].freeze,
        "ShadowRoot" => %w[
          onslotchange
        ].freeze,
        "SharedWorker" => %w[
          onerror
        ].freeze,
        "SharedWorkerGlobalScope" => %w[
          onconnect
        ].freeze,
        "TextTrack" => %w[
          oncuechange
        ].freeze,
        "TextTrackCue" => %w[
          onenter onexit
        ].freeze,
        "TextTrackList" => %w[
          onaddtrack onchange onremovetrack
        ].freeze,
        "VideoTrackList" => %w[
          onaddtrack onchange onremovetrack
        ].freeze,
        "VisualViewport" => %w[
          onresize onscroll onscrollend
        ].freeze,
        "WebSocket" => %w[
          onclose onerror onmessage onopen
        ].freeze,
        "Window" => %w[
          onabort onafterprint onanimationcancel onanimationend onanimationiteration onanimationstart
          onauxclick onbeforeinput onbeforematch onbeforeprint onbeforetoggle onbeforeunload onblur
          oncancel oncanplay oncanplaythrough onchange onclick onclose oncommand oncontextlost
          oncontextmenu oncontextrestored oncopy oncuechange oncut ondblclick ondrag ondragend
          ondragenter ondragleave ondragover ondragstart ondrop ondurationchange onemptied onended
          onerror onfocus onformdata ongotpointercapture onhashchange oninput oninvalid onkeydown
          onkeypress onkeyup onlanguagechange onload onloadeddata onloadedmetadata onloadstart
          onlostpointercapture onmessage onmessageerror onmousedown onmouseenter onmouseleave
          onmousemove onmouseout onmouseover onmouseup onoffline ononline onpagehide onpagereveal
          onpageshow onpageswap onpaste onpause onplay onplaying onpointercancel onpointerdown
          onpointerenter onpointerleave onpointermove onpointerout onpointerover onpointerrawupdate
          onpointerup onpopstate onprogress onratechange onrejectionhandled onreset onresize onscroll
          onscrollend onsecuritypolicyviolation onseeked onseeking onselect onselectionchange
          onselectstart onslotchange onstalled onstorage onsubmit onsuspend ontimeupdate ontoggle
          ontouchcancel ontouchend ontouchmove ontouchstart ontransitioncancel ontransitionend
          ontransitionrun ontransitionstart onunhandledrejection onunload onvolumechange onwaiting
          onwebkitanimationend onwebkitanimationiteration onwebkitanimationstart onwebkittransitionend
          onwheel
        ].freeze,
        "Worker" => %w[
          onerror onmessage onmessageerror
        ].freeze,
        "WorkerGlobalScope" => %w[
          onerror onlanguagechange onoffline ononline onrejectionhandled onunhandledrejection
        ].freeze,
        "XMLHttpRequest" => %w[
          onreadystatechange
        ].freeze,
        "XMLHttpRequestEventTarget" => %w[
          onabort onerror onload onloadend onloadstart onprogress ontimeout
        ].freeze
      }.freeze

      # GlobalEventHandlers: event handler content attributes of every HTML
      # element (and of SVG and MathML elements, whose IDL includes the mixin).
      GLOBAL_EVENT_HANDLERS = %w[
        onabort onanimationcancel onanimationend onanimationiteration onanimationstart onauxclick
        onbeforeinput onbeforematch onbeforetoggle onblur oncancel oncanplay oncanplaythrough onchange
        onclick onclose oncommand oncontextlost oncontextmenu oncontextrestored oncopy oncuechange
        oncut ondblclick ondrag ondragend ondragenter ondragleave ondragover ondragstart ondrop
        ondurationchange onemptied onended onerror onfocus onformdata ongotpointercapture oninput
        oninvalid onkeydown onkeypress onkeyup onload onloadeddata onloadedmetadata onloadstart
        onlostpointercapture onmousedown onmouseenter onmouseleave onmousemove onmouseout onmouseover
        onmouseup onpaste onpause onplay onplaying onpointercancel onpointerdown onpointerenter
        onpointerleave onpointermove onpointerout onpointerover onpointerrawupdate onpointerup
        onprogress onratechange onreset onresize onscroll onscrollend onsecuritypolicyviolation
        onseeked onseeking onselect onselectionchange onselectstart onslotchange onstalled onsubmit
        onsuspend ontimeupdate ontoggle ontouchcancel ontouchend ontouchmove ontouchstart
        ontransitioncancel ontransitionend ontransitionrun ontransitionstart onvolumechange onwaiting
        onwebkitanimationend onwebkitanimationiteration onwebkitanimationstart onwebkittransitionend
        onwheel
      ].to_set.freeze

      # WindowEventHandlers: further content attributes of body and frameset.
      WINDOW_EVENT_HANDLERS = %w[
        onafterprint onbeforeprint onbeforeunload onhashchange onlanguagechange onmessage
        onmessageerror onoffline ononline onpagehide onpagereveal onpageshow onpageswap onpopstate
        onrejectionhandled onstorage onunhandledrejection onunload
      ].to_set.freeze

      # HTML §8.1.8.2's "Window-reflecting body element event handler set",
      # which the spec lists in prose: on body/frameset, these and the
      # WindowEventHandlers are the Window's handlers.
      WINDOW_REFLECTING_BODY_ELEMENT_SET = %w[
        onblur onerror onfocus onload onresize onscroll
      ].to_set.freeze

      # The handlers whose event handler event type (§8.1.8.2's tables) is
      # not simply the name without "on".
      EVENT_TYPE_OVERRIDES = {
        "onwebkitanimationend" => "webkitAnimationEnd",
        "onwebkitanimationiteration" => "webkitAnimationIteration",
        "onwebkitanimationstart" => "webkitAnimationStart",
        "onwebkittransitionend" => "webkitTransitionEnd"
      }.freeze
    end
  end
end
