# frozen_string_literal: true

require_relative "idl_reflection_table"

module Dommy
  module Internal
    # HTML §2.6.1 reflection, generated from the specs' own IDL.
    #
    # TABLE (idl_reflection_table.rb, generated by
    # script/build_idl_reflection_table.rb) records every attribute the IDL marks
    # [Reflect] / [ReflectURL] / [ReflectSetter] / [ReflectNonNegative] /
    # [ReflectPositive] / [ReflectPositiveWithFallback], with [ReflectDefault] /
    # [ReflectRange]. OVERLAY below adds what the IDL cannot say: an enumerated
    # attribute's keywords and defaults, a token list's supported tokens, and
    # the handful of reflections the spec writes only in prose.
    #
    # `install_all!` runs once, after every element class is defined, and gives
    # each class the reflection its interface declares through the existing
    # reflect_* machinery (Internal::ReflectedAttributes) — except where the
    # class already says something about that attribute itself: a reflect_*
    # declaration, or a Ruby accessor of the same name. Hand-written code wins;
    # the generated declarations only fill the gaps.
    #
    # The WebIDL audit (test/support/webidl_audit.rb) reads the same mapping, so
    # what is generated and what is checked cannot drift.
    module IdlReflection
      # The §2.6.1 type an IDL type reflects as, for the plain [Reflect] shapes.
      TYPE_FOR_IDL = {
        "DOMString" => :string,
        "USVString" => :string,
        "DOMString?" => :nullable_string,
        "boolean" => :boolean,
        "long" => :long,
        "unsigned long" => :ulong,
        "double" => :double,
        "DOMTokenList" => :token_list,
        "Element?" => :element_ref,
        "FrozenArray<Element>?" => :element_refs
      }.freeze

      # [ReflectSetter] says only that the getter is prose; what the setter
      # converts comes from the IDL type.
      SETTER_FOR_IDL = {
        "DOMString" => :setter_only,
        "USVString" => :setter_only,
        "long" => :long_setter,
        "unsigned long" => :ulong_setter,
        "double" => :double_setter
      }.freeze

      # What the IDL cannot express, keyed "Interface.idlName". Each value is a
      # declaration: `type:` (a ReflectedAttributes::REFLECTORS key) plus that
      # type's options. An entry either completes a [Reflect] the table has (a
      # DOMString? that is enumerated, a DOMTokenList's supported tokens) or
      # stands for a reflection the spec states only in prose, where the IDL
      # carries no [Reflect] at all.
      #
      # Most enumerated attributes are still declared by hand next to the
      # behaviour that reads them (input.type, form.method, …); this lists the
      # ones nothing else declares.
      OVERLAY = {
        # HTML "The canvas element": "The width and height IDL attributes must reflect the
        # respective content attributes of the same name, with the same
        # defaults" — 300 and 150, said only in prose.
        "HTMLCanvasElement.width" => { type: :ulong, default: 300 },
        "HTMLCanvasElement.height" => { type: :ulong, default: 150 },
        # HTML "The iframe element": the srcdoc getter returns the null-namespace
        # attribute's value or "", and the setter sets it to the Trusted Types
        # "compliant string" (which, with no Trusted Types policy, is the
        # string itself) — a plain string reflection written out in prose,
        # since the IDL type is (TrustedHTML or DOMString).
        "HTMLIFrameElement.srcdoc" => { type: :string },
        # HTML "The size attribute" (input): the IDL says only [Reflect]; the
        # prose adds
        # "The size IDL attribute is limited to only positive numbers and has a
        # default value of 20."
        "HTMLInputElement.size" => { type: :ulong, positive: true, default: 20 }
      }.freeze

      # Declaration types the installer may define. :nullable_string and
      # :element_refs need an overlay (an enumerated DOMString?) or the ARIA
      # machinery on Element (Internal::ElementAria), so a bare one is skipped.
      INSTALLABLE = %i[
        string url long ulong double token_list boolean enumerated element_ref
        setter_only long_setter ulong_setter double_setter
      ].freeze

      SETTER_TYPES = %i[setter_only long_setter ulong_setter double_setter].freeze

      module_function

      # { idlName => { type:, attr:, options: } } for one interface: the table's
      # entries with the overlay applied, plus the overlay's prose-only ones.
      def declarations_for(interface)
        @declarations ||= {}
        @declarations[interface] ||= begin
          out = {}
          TABLE.fetch(interface, {}).each do |name, entry|
            out[name] = declaration(entry, name)
          end
          OVERLAY.each do |key, overlay|
            owner, name = key.split(".", 2)
            next unless owner == interface

            base = out[name] || { type: nil, attr: name.downcase, options: {} }
            out[name] = {
              type: overlay.fetch(:type),
              attr: overlay.fetch(:attr, base[:attr]),
              options: base[:options].merge(overlay.except(:type, :attr)).freeze
            }.freeze
          end
          out.freeze
        end
      end

      # The declaration one table entry stands for.
      def declaration(entry, name)
        type =
          case entry[:shape]
          when :url then :url
          when :setter then SETTER_FOR_IDL[entry[:idl]]
          else TYPE_FOR_IDL[entry[:idl]]
          end
        { type: type, attr: entry[:attr] || name.downcase, options: options_for(entry) }.freeze
      end

      # The numeric parameters, spelled as the reflect_* options spell them.
      def options_for(entry)
        options = {}
        options[:default] = entry[:default] if entry.key?(:default)
        options[:default] = options[:default].to_f if options.key?(:default) && entry[:idl] == "double"
        options[:range] = entry[:range] if entry.key?(:range)
        options[:non_negative] = true if entry[:non_negative]
        options[:positive] = true if entry[:positive] || entry[:positive_with_fallback]
        options[:fallback] = true if entry[:positive_with_fallback]
        options.freeze
      end

      # The declaration the audit expects for "Interface.idlName", or nil when
      # the spec does not reflect it (neither the IDL nor the overlay).
      def expected(interface, name)
        declarations_for(interface)[name]
      end

      # Every element class that takes reflect_* declarations, given the
      # reflection its interface declares and the class has not.
      def install_all!(root = Dommy::HTMLElement)
        each_class(root) { |klass| install(klass) }
      end

      def each_class(klass, &block)
        yield klass
        klass.subclasses.sort_by { |sub| sub.name.to_s }.each { |sub| each_class(sub, &block) }
      end

      # The class's own interface (`Dommy::HTMLAnchorElement` →
      # "HTMLAnchorElement") — only its OWN interface's attributes: an
      # inherited interface's are its superclass's to declare.
      def install(klass, interface = klass.name&.split("::")&.last)
        return unless interface

        declarations_for(interface).each do |name, declaration|
          type = declaration[:type]
          next unless INSTALLABLE.include?(type)
          next if klass.reflect_specs.key?(name)

          ruby_name = ruby_name_for(name)
          getter = own_method?(klass, ruby_name)
          setter = own_method?(klass, :"#{ruby_name}=")
          # Registered for the bridge by hand (js_accessor) to an accessor the
          # class has written: that accessor is its answer.
          next if klass.reflected_property_map.key?(name) && getter
          if SETTER_TYPES.include?(type)
            # [ReflectSetter]: the getter is prose, so only a class that has
            # written one gets the setter (and the bridge registration) here.
            next unless getter && !setter
          elsif getter || setter
            # A hand-written accessor of that name is the class's own answer.
            next
          end

          klass.__send__(:_reflect, type, [], { ruby_name => declaration[:options].merge(attr: declaration[:attr], js: name) },
                          generated: true)
        end
      end

      # Whether a Dommy class or module in the ancestry defines `name` — not
      # Kernel's `open` or Object's `display`, which say nothing about the
      # element.
      def own_method?(klass, name)
        return false unless klass.method_defined?(name) || klass.private_method_defined?(name)

        klass.instance_method(name).owner.name.to_s.start_with?("Dommy")
      end

      # `bgColor` → :bg_color, `aLink` → :a_link, `imageSrcset` → :image_srcset.
      def ruby_name_for(name)
        name.gsub(/([A-Z])/) { "_#{::Regexp.last_match(1).downcase}" }.to_sym
      end
    end
  end
end
