# frozen_string_literal: true

# GENERATED by script/build_idl_reflection_table.rb from
# test/fixtures/webidl/interfaces.json (web-platform-tests 863077959ca8c1a7ceecfbe2534b75d2527b9013).
# Do not edit by hand: re-run the script after refreshing the fixture.
#
# Every IDL attribute the specs mark as reflecting a content attribute
# (HTML §2.6.1 "Using reflect via IDL extended attributes"): its IDL type,
# its shape ([Reflect] / [ReflectNonNegative] / [ReflectPositive] /
# [ReflectPositiveWithFallback] are :plain, [ReflectURL] :url,
# [ReflectSetter] :setter) and the parameters the IDL gives it — the content
# attribute when it is not the IDL name lowercased, [ReflectDefault],
# [ReflectRange] and the sign limits. Internal::IdlReflection turns each
# entry into a reflect_* declaration.
module Dommy
  module Internal
    module IdlReflection
      TABLE = {
        "Element" => {
          "ariaActiveDescendantElement" => { idl: "Element?", shape: :plain, attr: "aria-activedescendant" }.freeze,
          "ariaAtomic" => { idl: "DOMString?", shape: :plain, attr: "aria-atomic" }.freeze,
          "ariaAutoComplete" => { idl: "DOMString?", shape: :plain, attr: "aria-autocomplete" }.freeze,
          "ariaBrailleLabel" => { idl: "DOMString?", shape: :plain, attr: "aria-braillelabel" }.freeze,
          "ariaBrailleRoleDescription" => { idl: "DOMString?", shape: :plain, attr: "aria-brailleroledescription" }.freeze,
          "ariaBusy" => { idl: "DOMString?", shape: :plain, attr: "aria-busy" }.freeze,
          "ariaChecked" => { idl: "DOMString?", shape: :plain, attr: "aria-checked" }.freeze,
          "ariaColCount" => { idl: "DOMString?", shape: :plain, attr: "aria-colcount" }.freeze,
          "ariaColIndex" => { idl: "DOMString?", shape: :plain, attr: "aria-colindex" }.freeze,
          "ariaColIndexText" => { idl: "DOMString?", shape: :plain, attr: "aria-colindextext" }.freeze,
          "ariaColSpan" => { idl: "DOMString?", shape: :plain, attr: "aria-colspan" }.freeze,
          "ariaControlsElements" => { idl: "FrozenArray<Element>?", shape: :plain, attr: "aria-controls" }.freeze,
          "ariaCurrent" => { idl: "DOMString?", shape: :plain, attr: "aria-current" }.freeze,
          "ariaDescribedByElements" => { idl: "FrozenArray<Element>?", shape: :plain, attr: "aria-describedby" }.freeze,
          "ariaDescription" => { idl: "DOMString?", shape: :plain, attr: "aria-description" }.freeze,
          "ariaDetailsElements" => { idl: "FrozenArray<Element>?", shape: :plain, attr: "aria-details" }.freeze,
          "ariaDisabled" => { idl: "DOMString?", shape: :plain, attr: "aria-disabled" }.freeze,
          "ariaErrorMessageElements" => { idl: "FrozenArray<Element>?", shape: :plain, attr: "aria-errormessage" }.freeze,
          "ariaExpanded" => { idl: "DOMString?", shape: :plain, attr: "aria-expanded" }.freeze,
          "ariaFlowToElements" => { idl: "FrozenArray<Element>?", shape: :plain, attr: "aria-flowto" }.freeze,
          "ariaHasPopup" => { idl: "DOMString?", shape: :plain, attr: "aria-haspopup" }.freeze,
          "ariaHidden" => { idl: "DOMString?", shape: :plain, attr: "aria-hidden" }.freeze,
          "ariaInvalid" => { idl: "DOMString?", shape: :plain, attr: "aria-invalid" }.freeze,
          "ariaKeyShortcuts" => { idl: "DOMString?", shape: :plain, attr: "aria-keyshortcuts" }.freeze,
          "ariaLabel" => { idl: "DOMString?", shape: :plain, attr: "aria-label" }.freeze,
          "ariaLabelledByElements" => { idl: "FrozenArray<Element>?", shape: :plain, attr: "aria-labelledby" }.freeze,
          "ariaLevel" => { idl: "DOMString?", shape: :plain, attr: "aria-level" }.freeze,
          "ariaLive" => { idl: "DOMString?", shape: :plain, attr: "aria-live" }.freeze,
          "ariaModal" => { idl: "DOMString?", shape: :plain, attr: "aria-modal" }.freeze,
          "ariaMultiLine" => { idl: "DOMString?", shape: :plain, attr: "aria-multiline" }.freeze,
          "ariaMultiSelectable" => { idl: "DOMString?", shape: :plain, attr: "aria-multiselectable" }.freeze,
          "ariaOrientation" => { idl: "DOMString?", shape: :plain, attr: "aria-orientation" }.freeze,
          "ariaOwnsElements" => { idl: "FrozenArray<Element>?", shape: :plain, attr: "aria-owns" }.freeze,
          "ariaPlaceholder" => { idl: "DOMString?", shape: :plain, attr: "aria-placeholder" }.freeze,
          "ariaPosInSet" => { idl: "DOMString?", shape: :plain, attr: "aria-posinset" }.freeze,
          "ariaPressed" => { idl: "DOMString?", shape: :plain, attr: "aria-pressed" }.freeze,
          "ariaReadOnly" => { idl: "DOMString?", shape: :plain, attr: "aria-readonly" }.freeze,
          "ariaRelevant" => { idl: "DOMString?", shape: :plain, attr: "aria-relevant" }.freeze,
          "ariaRequired" => { idl: "DOMString?", shape: :plain, attr: "aria-required" }.freeze,
          "ariaRoleDescription" => { idl: "DOMString?", shape: :plain, attr: "aria-roledescription" }.freeze,
          "ariaRowCount" => { idl: "DOMString?", shape: :plain, attr: "aria-rowcount" }.freeze,
          "ariaRowIndex" => { idl: "DOMString?", shape: :plain, attr: "aria-rowindex" }.freeze,
          "ariaRowIndexText" => { idl: "DOMString?", shape: :plain, attr: "aria-rowindextext" }.freeze,
          "ariaRowSpan" => { idl: "DOMString?", shape: :plain, attr: "aria-rowspan" }.freeze,
          "ariaSelected" => { idl: "DOMString?", shape: :plain, attr: "aria-selected" }.freeze,
          "ariaSetSize" => { idl: "DOMString?", shape: :plain, attr: "aria-setsize" }.freeze,
          "ariaSort" => { idl: "DOMString?", shape: :plain, attr: "aria-sort" }.freeze,
          "ariaValueMax" => { idl: "DOMString?", shape: :plain, attr: "aria-valuemax" }.freeze,
          "ariaValueMin" => { idl: "DOMString?", shape: :plain, attr: "aria-valuemin" }.freeze,
          "ariaValueNow" => { idl: "DOMString?", shape: :plain, attr: "aria-valuenow" }.freeze,
          "ariaValueText" => { idl: "DOMString?", shape: :plain, attr: "aria-valuetext" }.freeze,
          "role" => { idl: "DOMString?", shape: :plain }.freeze
        }.freeze,
        "ElementInternals" => {
          "ariaActiveDescendantElement" => { idl: "Element?", shape: :plain, attr: "aria-activedescendant" }.freeze,
          "ariaAtomic" => { idl: "DOMString?", shape: :plain, attr: "aria-atomic" }.freeze,
          "ariaAutoComplete" => { idl: "DOMString?", shape: :plain, attr: "aria-autocomplete" }.freeze,
          "ariaBrailleLabel" => { idl: "DOMString?", shape: :plain, attr: "aria-braillelabel" }.freeze,
          "ariaBrailleRoleDescription" => { idl: "DOMString?", shape: :plain, attr: "aria-brailleroledescription" }.freeze,
          "ariaBusy" => { idl: "DOMString?", shape: :plain, attr: "aria-busy" }.freeze,
          "ariaChecked" => { idl: "DOMString?", shape: :plain, attr: "aria-checked" }.freeze,
          "ariaColCount" => { idl: "DOMString?", shape: :plain, attr: "aria-colcount" }.freeze,
          "ariaColIndex" => { idl: "DOMString?", shape: :plain, attr: "aria-colindex" }.freeze,
          "ariaColIndexText" => { idl: "DOMString?", shape: :plain, attr: "aria-colindextext" }.freeze,
          "ariaColSpan" => { idl: "DOMString?", shape: :plain, attr: "aria-colspan" }.freeze,
          "ariaControlsElements" => { idl: "FrozenArray<Element>?", shape: :plain, attr: "aria-controls" }.freeze,
          "ariaCurrent" => { idl: "DOMString?", shape: :plain, attr: "aria-current" }.freeze,
          "ariaDescribedByElements" => { idl: "FrozenArray<Element>?", shape: :plain, attr: "aria-describedby" }.freeze,
          "ariaDescription" => { idl: "DOMString?", shape: :plain, attr: "aria-description" }.freeze,
          "ariaDetailsElements" => { idl: "FrozenArray<Element>?", shape: :plain, attr: "aria-details" }.freeze,
          "ariaDisabled" => { idl: "DOMString?", shape: :plain, attr: "aria-disabled" }.freeze,
          "ariaErrorMessageElements" => { idl: "FrozenArray<Element>?", shape: :plain, attr: "aria-errormessage" }.freeze,
          "ariaExpanded" => { idl: "DOMString?", shape: :plain, attr: "aria-expanded" }.freeze,
          "ariaFlowToElements" => { idl: "FrozenArray<Element>?", shape: :plain, attr: "aria-flowto" }.freeze,
          "ariaHasPopup" => { idl: "DOMString?", shape: :plain, attr: "aria-haspopup" }.freeze,
          "ariaHidden" => { idl: "DOMString?", shape: :plain, attr: "aria-hidden" }.freeze,
          "ariaInvalid" => { idl: "DOMString?", shape: :plain, attr: "aria-invalid" }.freeze,
          "ariaKeyShortcuts" => { idl: "DOMString?", shape: :plain, attr: "aria-keyshortcuts" }.freeze,
          "ariaLabel" => { idl: "DOMString?", shape: :plain, attr: "aria-label" }.freeze,
          "ariaLabelledByElements" => { idl: "FrozenArray<Element>?", shape: :plain, attr: "aria-labelledby" }.freeze,
          "ariaLevel" => { idl: "DOMString?", shape: :plain, attr: "aria-level" }.freeze,
          "ariaLive" => { idl: "DOMString?", shape: :plain, attr: "aria-live" }.freeze,
          "ariaModal" => { idl: "DOMString?", shape: :plain, attr: "aria-modal" }.freeze,
          "ariaMultiLine" => { idl: "DOMString?", shape: :plain, attr: "aria-multiline" }.freeze,
          "ariaMultiSelectable" => { idl: "DOMString?", shape: :plain, attr: "aria-multiselectable" }.freeze,
          "ariaOrientation" => { idl: "DOMString?", shape: :plain, attr: "aria-orientation" }.freeze,
          "ariaOwnsElements" => { idl: "FrozenArray<Element>?", shape: :plain, attr: "aria-owns" }.freeze,
          "ariaPlaceholder" => { idl: "DOMString?", shape: :plain, attr: "aria-placeholder" }.freeze,
          "ariaPosInSet" => { idl: "DOMString?", shape: :plain, attr: "aria-posinset" }.freeze,
          "ariaPressed" => { idl: "DOMString?", shape: :plain, attr: "aria-pressed" }.freeze,
          "ariaReadOnly" => { idl: "DOMString?", shape: :plain, attr: "aria-readonly" }.freeze,
          "ariaRelevant" => { idl: "DOMString?", shape: :plain, attr: "aria-relevant" }.freeze,
          "ariaRequired" => { idl: "DOMString?", shape: :plain, attr: "aria-required" }.freeze,
          "ariaRoleDescription" => { idl: "DOMString?", shape: :plain, attr: "aria-roledescription" }.freeze,
          "ariaRowCount" => { idl: "DOMString?", shape: :plain, attr: "aria-rowcount" }.freeze,
          "ariaRowIndex" => { idl: "DOMString?", shape: :plain, attr: "aria-rowindex" }.freeze,
          "ariaRowIndexText" => { idl: "DOMString?", shape: :plain, attr: "aria-rowindextext" }.freeze,
          "ariaRowSpan" => { idl: "DOMString?", shape: :plain, attr: "aria-rowspan" }.freeze,
          "ariaSelected" => { idl: "DOMString?", shape: :plain, attr: "aria-selected" }.freeze,
          "ariaSetSize" => { idl: "DOMString?", shape: :plain, attr: "aria-setsize" }.freeze,
          "ariaSort" => { idl: "DOMString?", shape: :plain, attr: "aria-sort" }.freeze,
          "ariaValueMax" => { idl: "DOMString?", shape: :plain, attr: "aria-valuemax" }.freeze,
          "ariaValueMin" => { idl: "DOMString?", shape: :plain, attr: "aria-valuemin" }.freeze,
          "ariaValueNow" => { idl: "DOMString?", shape: :plain, attr: "aria-valuenow" }.freeze,
          "ariaValueText" => { idl: "DOMString?", shape: :plain, attr: "aria-valuetext" }.freeze,
          "role" => { idl: "DOMString?", shape: :plain }.freeze
        }.freeze,
        "HTMLAnchorElement" => {
          "charset" => { idl: "DOMString", shape: :plain }.freeze,
          "coords" => { idl: "DOMString", shape: :plain }.freeze,
          "download" => { idl: "DOMString", shape: :plain }.freeze,
          "href" => { idl: "USVString", shape: :setter }.freeze,
          "hreflang" => { idl: "DOMString", shape: :plain }.freeze,
          "name" => { idl: "DOMString", shape: :plain }.freeze,
          "ping" => { idl: "USVString", shape: :plain }.freeze,
          "rel" => { idl: "DOMString", shape: :plain }.freeze,
          "relList" => { idl: "DOMTokenList", shape: :plain, attr: "rel" }.freeze,
          "rev" => { idl: "DOMString", shape: :plain }.freeze,
          "shape" => { idl: "DOMString", shape: :plain }.freeze,
          "target" => { idl: "DOMString", shape: :plain }.freeze,
          "type" => { idl: "DOMString", shape: :plain }.freeze
        }.freeze,
        "HTMLAreaElement" => {
          "alt" => { idl: "DOMString", shape: :plain }.freeze,
          "coords" => { idl: "DOMString", shape: :plain }.freeze,
          "download" => { idl: "DOMString", shape: :plain }.freeze,
          "href" => { idl: "USVString", shape: :setter }.freeze,
          "hreflang" => { idl: "DOMString", shape: :plain }.freeze,
          "noHref" => { idl: "boolean", shape: :plain }.freeze,
          "ping" => { idl: "USVString", shape: :plain }.freeze,
          "rel" => { idl: "DOMString", shape: :plain }.freeze,
          "relList" => { idl: "DOMTokenList", shape: :plain, attr: "rel" }.freeze,
          "shape" => { idl: "DOMString", shape: :plain }.freeze,
          "target" => { idl: "DOMString", shape: :plain }.freeze,
          "type" => { idl: "DOMString", shape: :plain }.freeze
        }.freeze,
        "HTMLBRElement" => {
          "clear" => { idl: "DOMString", shape: :plain }.freeze
        }.freeze,
        "HTMLBaseElement" => {
          "href" => { idl: "USVString", shape: :setter }.freeze,
          "target" => { idl: "DOMString", shape: :plain }.freeze
        }.freeze,
        "HTMLBodyElement" => {
          "aLink" => { idl: "DOMString", shape: :plain }.freeze,
          "background" => { idl: "DOMString", shape: :plain }.freeze,
          "bgColor" => { idl: "DOMString", shape: :plain }.freeze,
          "link" => { idl: "DOMString", shape: :plain }.freeze,
          "text" => { idl: "DOMString", shape: :plain }.freeze,
          "vLink" => { idl: "DOMString", shape: :plain }.freeze
        }.freeze,
        "HTMLButtonElement" => {
          "command" => { idl: "DOMString", shape: :setter }.freeze,
          "commandForElement" => { idl: "Element?", shape: :plain, attr: "commandfor" }.freeze,
          "disabled" => { idl: "boolean", shape: :plain }.freeze,
          "formAction" => { idl: "USVString", shape: :setter }.freeze,
          "formNoValidate" => { idl: "boolean", shape: :plain }.freeze,
          "formTarget" => { idl: "DOMString", shape: :plain }.freeze,
          "name" => { idl: "DOMString", shape: :plain }.freeze,
          "popoverTargetElement" => { idl: "Element?", shape: :plain, attr: "popovertarget" }.freeze,
          "type" => { idl: "DOMString", shape: :setter }.freeze,
          "value" => { idl: "DOMString", shape: :plain }.freeze
        }.freeze,
        "HTMLDListElement" => {
          "compact" => { idl: "boolean", shape: :plain }.freeze
        }.freeze,
        "HTMLDataElement" => {
          "value" => { idl: "DOMString", shape: :plain }.freeze
        }.freeze,
        "HTMLDetailsElement" => {
          "name" => { idl: "DOMString", shape: :plain }.freeze,
          "open" => { idl: "boolean", shape: :plain }.freeze
        }.freeze,
        "HTMLDialogElement" => {
          "closedBy" => { idl: "DOMString", shape: :setter }.freeze,
          "open" => { idl: "boolean", shape: :plain }.freeze
        }.freeze,
        "HTMLDirectoryElement" => {
          "compact" => { idl: "boolean", shape: :plain }.freeze
        }.freeze,
        "HTMLDivElement" => {
          "align" => { idl: "DOMString", shape: :plain }.freeze
        }.freeze,
        "HTMLElement" => {
          "accessKey" => { idl: "DOMString", shape: :plain }.freeze,
          "autocapitalize" => { idl: "DOMString", shape: :setter }.freeze,
          "autofocus" => { idl: "boolean", shape: :plain }.freeze,
          "headingOffset" => { idl: "unsigned long", shape: :plain, range: 0..8 }.freeze,
          "headingReset" => { idl: "boolean", shape: :plain }.freeze,
          "inert" => { idl: "boolean", shape: :plain }.freeze,
          "lang" => { idl: "DOMString", shape: :plain }.freeze,
          "tabIndex" => { idl: "long", shape: :setter }.freeze,
          "title" => { idl: "DOMString", shape: :plain }.freeze,
          "writingSuggestions" => { idl: "DOMString", shape: :setter }.freeze
        }.freeze,
        "HTMLEmbedElement" => {
          "align" => { idl: "DOMString", shape: :plain }.freeze,
          "height" => { idl: "DOMString", shape: :plain }.freeze,
          "name" => { idl: "DOMString", shape: :plain }.freeze,
          "src" => { idl: "USVString", shape: :url }.freeze,
          "type" => { idl: "DOMString", shape: :plain }.freeze,
          "width" => { idl: "DOMString", shape: :plain }.freeze
        }.freeze,
        "HTMLFieldSetElement" => {
          "disabled" => { idl: "boolean", shape: :plain }.freeze,
          "name" => { idl: "DOMString", shape: :plain }.freeze
        }.freeze,
        "HTMLFontElement" => {
          "color" => { idl: "DOMString", shape: :plain }.freeze,
          "face" => { idl: "DOMString", shape: :plain }.freeze,
          "size" => { idl: "DOMString", shape: :plain }.freeze
        }.freeze,
        "HTMLFormElement" => {
          "acceptCharset" => { idl: "DOMString", shape: :plain, attr: "accept-charset" }.freeze,
          "action" => { idl: "USVString", shape: :setter }.freeze,
          "name" => { idl: "DOMString", shape: :plain }.freeze,
          "noValidate" => { idl: "boolean", shape: :plain }.freeze,
          "rel" => { idl: "DOMString", shape: :plain }.freeze,
          "relList" => { idl: "DOMTokenList", shape: :plain, attr: "rel" }.freeze,
          "target" => { idl: "DOMString", shape: :plain }.freeze
        }.freeze,
        "HTMLFrameElement" => {
          "frameBorder" => { idl: "DOMString", shape: :plain }.freeze,
          "longDesc" => { idl: "USVString", shape: :url }.freeze,
          "marginHeight" => { idl: "DOMString", shape: :plain }.freeze,
          "marginWidth" => { idl: "DOMString", shape: :plain }.freeze,
          "name" => { idl: "DOMString", shape: :plain }.freeze,
          "noResize" => { idl: "boolean", shape: :plain }.freeze,
          "scrolling" => { idl: "DOMString", shape: :plain }.freeze,
          "src" => { idl: "USVString", shape: :url }.freeze
        }.freeze,
        "HTMLFrameSetElement" => {
          "cols" => { idl: "DOMString", shape: :plain }.freeze,
          "rows" => { idl: "DOMString", shape: :plain }.freeze
        }.freeze,
        "HTMLHRElement" => {
          "align" => { idl: "DOMString", shape: :plain }.freeze,
          "color" => { idl: "DOMString", shape: :plain }.freeze,
          "noShade" => { idl: "boolean", shape: :plain }.freeze,
          "size" => { idl: "DOMString", shape: :plain }.freeze,
          "width" => { idl: "DOMString", shape: :plain }.freeze
        }.freeze,
        "HTMLHeadingElement" => {
          "align" => { idl: "DOMString", shape: :plain }.freeze
        }.freeze,
        "HTMLHtmlElement" => {
          "version" => { idl: "DOMString", shape: :plain }.freeze
        }.freeze,
        "HTMLIFrameElement" => {
          "align" => { idl: "DOMString", shape: :plain }.freeze,
          "allow" => { idl: "DOMString", shape: :plain }.freeze,
          "allowFullscreen" => { idl: "boolean", shape: :plain }.freeze,
          "frameBorder" => { idl: "DOMString", shape: :plain }.freeze,
          "height" => { idl: "DOMString", shape: :plain }.freeze,
          "longDesc" => { idl: "USVString", shape: :url }.freeze,
          "marginHeight" => { idl: "DOMString", shape: :plain }.freeze,
          "marginWidth" => { idl: "DOMString", shape: :plain }.freeze,
          "name" => { idl: "DOMString", shape: :plain }.freeze,
          "sandbox" => { idl: "DOMTokenList", shape: :plain }.freeze,
          "scrolling" => { idl: "DOMString", shape: :plain }.freeze,
          "src" => { idl: "USVString", shape: :url }.freeze,
          "width" => { idl: "DOMString", shape: :plain }.freeze
        }.freeze,
        "HTMLImageElement" => {
          "align" => { idl: "DOMString", shape: :plain }.freeze,
          "alt" => { idl: "DOMString", shape: :plain }.freeze,
          "border" => { idl: "DOMString", shape: :plain }.freeze,
          "controls" => { idl: "boolean", shape: :plain }.freeze,
          "height" => { idl: "unsigned long", shape: :setter }.freeze,
          "hspace" => { idl: "unsigned long", shape: :plain }.freeze,
          "isMap" => { idl: "boolean", shape: :plain }.freeze,
          "longDesc" => { idl: "USVString", shape: :url }.freeze,
          "lowsrc" => { idl: "USVString", shape: :url }.freeze,
          "name" => { idl: "DOMString", shape: :plain }.freeze,
          "sizes" => { idl: "DOMString", shape: :plain }.freeze,
          "src" => { idl: "USVString", shape: :url }.freeze,
          "srcset" => { idl: "USVString", shape: :plain }.freeze,
          "useMap" => { idl: "DOMString", shape: :plain }.freeze,
          "vspace" => { idl: "unsigned long", shape: :plain }.freeze,
          "width" => { idl: "unsigned long", shape: :setter }.freeze
        }.freeze,
        "HTMLInputElement" => {
          "accept" => { idl: "DOMString", shape: :plain }.freeze,
          "align" => { idl: "DOMString", shape: :plain }.freeze,
          "alpha" => { idl: "boolean", shape: :plain }.freeze,
          "alt" => { idl: "DOMString", shape: :plain }.freeze,
          "autocomplete" => { idl: "DOMString", shape: :setter }.freeze,
          "defaultChecked" => { idl: "boolean", shape: :plain, attr: "checked" }.freeze,
          "defaultValue" => { idl: "DOMString", shape: :plain, attr: "value" }.freeze,
          "dirName" => { idl: "DOMString", shape: :plain }.freeze,
          "disabled" => { idl: "boolean", shape: :plain }.freeze,
          "formAction" => { idl: "USVString", shape: :setter }.freeze,
          "formNoValidate" => { idl: "boolean", shape: :plain }.freeze,
          "formTarget" => { idl: "DOMString", shape: :plain }.freeze,
          "height" => { idl: "unsigned long", shape: :setter }.freeze,
          "max" => { idl: "DOMString", shape: :plain }.freeze,
          "maxLength" => { idl: "long", shape: :plain, non_negative: true }.freeze,
          "min" => { idl: "DOMString", shape: :plain }.freeze,
          "minLength" => { idl: "long", shape: :plain, non_negative: true }.freeze,
          "multiple" => { idl: "boolean", shape: :plain }.freeze,
          "name" => { idl: "DOMString", shape: :plain }.freeze,
          "pattern" => { idl: "DOMString", shape: :plain }.freeze,
          "placeholder" => { idl: "DOMString", shape: :plain }.freeze,
          "popoverTargetElement" => { idl: "Element?", shape: :plain, attr: "popovertarget" }.freeze,
          "readOnly" => { idl: "boolean", shape: :plain }.freeze,
          "required" => { idl: "boolean", shape: :plain }.freeze,
          "size" => { idl: "unsigned long", shape: :plain }.freeze,
          "src" => { idl: "USVString", shape: :url }.freeze,
          "step" => { idl: "DOMString", shape: :plain }.freeze,
          "useMap" => { idl: "DOMString", shape: :plain }.freeze,
          "width" => { idl: "unsigned long", shape: :setter }.freeze
        }.freeze,
        "HTMLLIElement" => {
          "type" => { idl: "DOMString", shape: :plain }.freeze,
          "value" => { idl: "long", shape: :plain }.freeze
        }.freeze,
        "HTMLLabelElement" => {
          "htmlFor" => { idl: "DOMString", shape: :plain, attr: "for" }.freeze
        }.freeze,
        "HTMLLegendElement" => {
          "align" => { idl: "DOMString", shape: :plain }.freeze
        }.freeze,
        "HTMLLinkElement" => {
          "blocking" => { idl: "DOMTokenList", shape: :plain }.freeze,
          "charset" => { idl: "DOMString", shape: :plain }.freeze,
          "disabled" => { idl: "boolean", shape: :plain }.freeze,
          "href" => { idl: "USVString", shape: :url }.freeze,
          "hreflang" => { idl: "DOMString", shape: :plain }.freeze,
          "imageSizes" => { idl: "DOMString", shape: :plain }.freeze,
          "imageSrcset" => { idl: "USVString", shape: :plain }.freeze,
          "integrity" => { idl: "DOMString", shape: :plain }.freeze,
          "media" => { idl: "DOMString", shape: :plain }.freeze,
          "rel" => { idl: "DOMString", shape: :plain }.freeze,
          "relList" => { idl: "DOMTokenList", shape: :plain, attr: "rel" }.freeze,
          "rev" => { idl: "DOMString", shape: :plain }.freeze,
          "sizes" => { idl: "DOMTokenList", shape: :plain }.freeze,
          "target" => { idl: "DOMString", shape: :plain }.freeze,
          "type" => { idl: "DOMString", shape: :plain }.freeze
        }.freeze,
        "HTMLMapElement" => {
          "name" => { idl: "DOMString", shape: :plain }.freeze
        }.freeze,
        "HTMLMarqueeElement" => {
          "behavior" => { idl: "DOMString", shape: :plain }.freeze,
          "bgColor" => { idl: "DOMString", shape: :plain }.freeze,
          "direction" => { idl: "DOMString", shape: :plain }.freeze,
          "height" => { idl: "DOMString", shape: :plain }.freeze,
          "hspace" => { idl: "unsigned long", shape: :plain }.freeze,
          "scrollAmount" => { idl: "unsigned long", shape: :plain, default: 6 }.freeze,
          "scrollDelay" => { idl: "unsigned long", shape: :plain, default: 85 }.freeze,
          "trueSpeed" => { idl: "boolean", shape: :plain }.freeze,
          "vspace" => { idl: "unsigned long", shape: :plain }.freeze,
          "width" => { idl: "DOMString", shape: :plain }.freeze
        }.freeze,
        "HTMLMediaElement" => {
          "autoplay" => { idl: "boolean", shape: :plain }.freeze,
          "controls" => { idl: "boolean", shape: :plain }.freeze,
          "defaultMuted" => { idl: "boolean", shape: :plain, attr: "muted" }.freeze,
          "loop" => { idl: "boolean", shape: :plain }.freeze,
          "src" => { idl: "USVString", shape: :url }.freeze
        }.freeze,
        "HTMLMenuElement" => {
          "compact" => { idl: "boolean", shape: :plain }.freeze
        }.freeze,
        "HTMLMetaElement" => {
          "content" => { idl: "DOMString", shape: :plain }.freeze,
          "httpEquiv" => { idl: "DOMString", shape: :plain, attr: "http-equiv" }.freeze,
          "media" => { idl: "DOMString", shape: :plain }.freeze,
          "name" => { idl: "DOMString", shape: :plain }.freeze,
          "scheme" => { idl: "DOMString", shape: :plain }.freeze
        }.freeze,
        "HTMLMeterElement" => {
          "high" => { idl: "double", shape: :setter }.freeze,
          "low" => { idl: "double", shape: :setter }.freeze,
          "max" => { idl: "double", shape: :setter }.freeze,
          "min" => { idl: "double", shape: :setter }.freeze,
          "optimum" => { idl: "double", shape: :setter }.freeze,
          "value" => { idl: "double", shape: :setter }.freeze
        }.freeze,
        "HTMLModElement" => {
          "cite" => { idl: "USVString", shape: :url }.freeze,
          "dateTime" => { idl: "DOMString", shape: :plain }.freeze
        }.freeze,
        "HTMLOListElement" => {
          "compact" => { idl: "boolean", shape: :plain }.freeze,
          "reversed" => { idl: "boolean", shape: :plain }.freeze,
          "start" => { idl: "long", shape: :plain, default: 1 }.freeze,
          "type" => { idl: "DOMString", shape: :plain }.freeze
        }.freeze,
        "HTMLObjectElement" => {
          "align" => { idl: "DOMString", shape: :plain }.freeze,
          "archive" => { idl: "DOMString", shape: :plain }.freeze,
          "border" => { idl: "DOMString", shape: :plain }.freeze,
          "code" => { idl: "DOMString", shape: :plain }.freeze,
          "codeBase" => { idl: "DOMString", shape: :url }.freeze,
          "codeType" => { idl: "DOMString", shape: :plain }.freeze,
          "data" => { idl: "USVString", shape: :url }.freeze,
          "declare" => { idl: "boolean", shape: :plain }.freeze,
          "height" => { idl: "DOMString", shape: :plain }.freeze,
          "hspace" => { idl: "unsigned long", shape: :plain }.freeze,
          "name" => { idl: "DOMString", shape: :plain }.freeze,
          "standby" => { idl: "DOMString", shape: :plain }.freeze,
          "type" => { idl: "DOMString", shape: :plain }.freeze,
          "useMap" => { idl: "DOMString", shape: :plain }.freeze,
          "vspace" => { idl: "unsigned long", shape: :plain }.freeze,
          "width" => { idl: "DOMString", shape: :plain }.freeze
        }.freeze,
        "HTMLOptGroupElement" => {
          "disabled" => { idl: "boolean", shape: :plain }.freeze,
          "label" => { idl: "DOMString", shape: :plain }.freeze
        }.freeze,
        "HTMLOptionElement" => {
          "defaultSelected" => { idl: "boolean", shape: :plain, attr: "selected" }.freeze,
          "disabled" => { idl: "boolean", shape: :plain }.freeze,
          "label" => { idl: "DOMString", shape: :setter }.freeze,
          "value" => { idl: "DOMString", shape: :setter }.freeze
        }.freeze,
        "HTMLOutputElement" => {
          "htmlFor" => { idl: "DOMTokenList", shape: :plain, attr: "for" }.freeze,
          "name" => { idl: "DOMString", shape: :plain }.freeze
        }.freeze,
        "HTMLParagraphElement" => {
          "align" => { idl: "DOMString", shape: :plain }.freeze
        }.freeze,
        "HTMLParamElement" => {
          "name" => { idl: "DOMString", shape: :plain }.freeze,
          "type" => { idl: "DOMString", shape: :plain }.freeze,
          "value" => { idl: "DOMString", shape: :plain }.freeze,
          "valueType" => { idl: "DOMString", shape: :plain }.freeze
        }.freeze,
        "HTMLPreElement" => {
          "width" => { idl: "long", shape: :plain }.freeze
        }.freeze,
        "HTMLProgressElement" => {
          "max" => { idl: "double", shape: :plain, default: 1, positive: true }.freeze,
          "value" => { idl: "double", shape: :setter }.freeze
        }.freeze,
        "HTMLQuoteElement" => {
          "cite" => { idl: "USVString", shape: :url }.freeze
        }.freeze,
        "HTMLScriptElement" => {
          "blocking" => { idl: "DOMTokenList", shape: :plain }.freeze,
          "charset" => { idl: "DOMString", shape: :plain }.freeze,
          "defer" => { idl: "boolean", shape: :plain }.freeze,
          "event" => { idl: "DOMString", shape: :plain }.freeze,
          "htmlFor" => { idl: "DOMString", shape: :plain, attr: "for" }.freeze,
          "integrity" => { idl: "DOMString", shape: :plain }.freeze,
          "noModule" => { idl: "boolean", shape: :plain }.freeze,
          "src" => { idl: "USVString", shape: :url }.freeze,
          "type" => { idl: "DOMString", shape: :plain }.freeze
        }.freeze,
        "HTMLSelectElement" => {
          "autocomplete" => { idl: "DOMString", shape: :setter }.freeze,
          "disabled" => { idl: "boolean", shape: :plain }.freeze,
          "multiple" => { idl: "boolean", shape: :plain }.freeze,
          "name" => { idl: "DOMString", shape: :plain }.freeze,
          "required" => { idl: "boolean", shape: :plain }.freeze,
          "size" => { idl: "unsigned long", shape: :plain, default: 0 }.freeze
        }.freeze,
        "HTMLSlotElement" => {
          "name" => { idl: "DOMString", shape: :plain }.freeze
        }.freeze,
        "HTMLSourceElement" => {
          "height" => { idl: "unsigned long", shape: :plain }.freeze,
          "media" => { idl: "DOMString", shape: :plain }.freeze,
          "sizes" => { idl: "DOMString", shape: :plain }.freeze,
          "src" => { idl: "USVString", shape: :url }.freeze,
          "srcset" => { idl: "USVString", shape: :plain }.freeze,
          "type" => { idl: "DOMString", shape: :plain }.freeze,
          "width" => { idl: "unsigned long", shape: :plain }.freeze
        }.freeze,
        "HTMLStyleElement" => {
          "blocking" => { idl: "DOMTokenList", shape: :plain }.freeze,
          "media" => { idl: "DOMString", shape: :plain }.freeze,
          "type" => { idl: "DOMString", shape: :plain }.freeze
        }.freeze,
        "HTMLTableCaptionElement" => {
          "align" => { idl: "DOMString", shape: :plain }.freeze
        }.freeze,
        "HTMLTableCellElement" => {
          "abbr" => { idl: "DOMString", shape: :plain }.freeze,
          "align" => { idl: "DOMString", shape: :plain }.freeze,
          "axis" => { idl: "DOMString", shape: :plain }.freeze,
          "bgColor" => { idl: "DOMString", shape: :plain }.freeze,
          "ch" => { idl: "DOMString", shape: :plain, attr: "char" }.freeze,
          "chOff" => { idl: "DOMString", shape: :plain, attr: "charoff" }.freeze,
          "colSpan" => { idl: "unsigned long", shape: :plain, default: 1, range: 1..1000 }.freeze,
          "headers" => { idl: "DOMString", shape: :plain }.freeze,
          "height" => { idl: "DOMString", shape: :plain }.freeze,
          "noWrap" => { idl: "boolean", shape: :plain }.freeze,
          "rowSpan" => { idl: "unsigned long", shape: :plain, default: 1, range: 0..65534 }.freeze,
          "vAlign" => { idl: "DOMString", shape: :plain }.freeze,
          "width" => { idl: "DOMString", shape: :plain }.freeze
        }.freeze,
        "HTMLTableColElement" => {
          "align" => { idl: "DOMString", shape: :plain }.freeze,
          "ch" => { idl: "DOMString", shape: :plain, attr: "char" }.freeze,
          "chOff" => { idl: "DOMString", shape: :plain, attr: "charoff" }.freeze,
          "span" => { idl: "unsigned long", shape: :plain, default: 1, range: 1..1000 }.freeze,
          "vAlign" => { idl: "DOMString", shape: :plain }.freeze,
          "width" => { idl: "DOMString", shape: :plain }.freeze
        }.freeze,
        "HTMLTableElement" => {
          "align" => { idl: "DOMString", shape: :plain }.freeze,
          "bgColor" => { idl: "DOMString", shape: :plain }.freeze,
          "border" => { idl: "DOMString", shape: :plain }.freeze,
          "cellPadding" => { idl: "DOMString", shape: :plain }.freeze,
          "cellSpacing" => { idl: "DOMString", shape: :plain }.freeze,
          "frame" => { idl: "DOMString", shape: :plain }.freeze,
          "rules" => { idl: "DOMString", shape: :plain }.freeze,
          "summary" => { idl: "DOMString", shape: :plain }.freeze,
          "width" => { idl: "DOMString", shape: :plain }.freeze
        }.freeze,
        "HTMLTableRowElement" => {
          "align" => { idl: "DOMString", shape: :plain }.freeze,
          "bgColor" => { idl: "DOMString", shape: :plain }.freeze,
          "ch" => { idl: "DOMString", shape: :plain, attr: "char" }.freeze,
          "chOff" => { idl: "DOMString", shape: :plain, attr: "charoff" }.freeze,
          "vAlign" => { idl: "DOMString", shape: :plain }.freeze
        }.freeze,
        "HTMLTableSectionElement" => {
          "align" => { idl: "DOMString", shape: :plain }.freeze,
          "ch" => { idl: "DOMString", shape: :plain, attr: "char" }.freeze,
          "chOff" => { idl: "DOMString", shape: :plain, attr: "charoff" }.freeze,
          "vAlign" => { idl: "DOMString", shape: :plain }.freeze
        }.freeze,
        "HTMLTemplateElement" => {
          "htmlFor" => { idl: "DOMString", shape: :plain, attr: "for" }.freeze,
          "shadowRootClonable" => { idl: "boolean", shape: :plain }.freeze,
          "shadowRootCustomElementRegistry" => { idl: "DOMString", shape: :plain }.freeze,
          "shadowRootDelegatesFocus" => { idl: "boolean", shape: :plain }.freeze,
          "shadowRootSerializable" => { idl: "boolean", shape: :plain }.freeze
        }.freeze,
        "HTMLTextAreaElement" => {
          "autocomplete" => { idl: "DOMString", shape: :setter }.freeze,
          "cols" => { idl: "unsigned long", shape: :plain, default: 20, positive_with_fallback: true }.freeze,
          "dirName" => { idl: "DOMString", shape: :plain }.freeze,
          "disabled" => { idl: "boolean", shape: :plain }.freeze,
          "maxLength" => { idl: "long", shape: :plain, non_negative: true }.freeze,
          "minLength" => { idl: "long", shape: :plain, non_negative: true }.freeze,
          "name" => { idl: "DOMString", shape: :plain }.freeze,
          "placeholder" => { idl: "DOMString", shape: :plain }.freeze,
          "readOnly" => { idl: "boolean", shape: :plain }.freeze,
          "required" => { idl: "boolean", shape: :plain }.freeze,
          "rows" => { idl: "unsigned long", shape: :plain, default: 2, positive_with_fallback: true }.freeze,
          "wrap" => { idl: "DOMString", shape: :plain }.freeze
        }.freeze,
        "HTMLTimeElement" => {
          "dateTime" => { idl: "DOMString", shape: :plain }.freeze
        }.freeze,
        "HTMLTrackElement" => {
          "default" => { idl: "boolean", shape: :plain }.freeze,
          "label" => { idl: "DOMString", shape: :plain }.freeze,
          "src" => { idl: "USVString", shape: :url }.freeze,
          "srclang" => { idl: "DOMString", shape: :plain }.freeze
        }.freeze,
        "HTMLUListElement" => {
          "compact" => { idl: "boolean", shape: :plain }.freeze,
          "type" => { idl: "DOMString", shape: :plain }.freeze
        }.freeze,
        "HTMLVideoElement" => {
          "height" => { idl: "unsigned long", shape: :plain }.freeze,
          "playsInline" => { idl: "boolean", shape: :plain }.freeze,
          "poster" => { idl: "USVString", shape: :url }.freeze,
          "width" => { idl: "unsigned long", shape: :plain }.freeze
        }.freeze
      }.freeze
    end
  end
end
