# frozen_string_literal: true

require "json"

module Dommy
  module Js
    # Engine-agnostic core of the JS<->Ruby DOM bridge. Given a `backend` that
    # can evaluate JS, register Ruby host functions, and call back into JS,
    # HostBridge exposes a Ruby object to the JS side as an ES Proxy whose
    # property/method access routes into the bridge ABI:
    #   __js_get__(name) / __js_set__(name, value) / __js_call__(method, args)
    #
    # Nothing here is QuickJS-specific; this layer is intended to move into a
    # future `dommy-js` gem with QuickJS/wasm backends plugged in underneath.
    #
    # Collaborators keep the bridge focused on the engine ABI:
    #   Marshaller          — Ruby<->JS value conversion + the handle/callback
    #                         identity tables (#wrap / #unwrap, delegated below)
    #   DomInterfaces       — interface name/chain derivation (instanceof support)
    #   ConstructorResolver — `new Event(...)` style reverse construction
    #   CustomElementBridge — JS customElements.define -> Dommy wiring
    #   CrossingProfile     — the opt-in boundary-crossing counter
    #
    # Backend contract:
    #   backend.eval(js)                         -> evaluate top-level JS
    #   backend.define_host_function(name) { }   -> expose a Ruby block as a JS global
    #   backend.call_js(path, *args)             -> invoke a JS global function by path
    #   backend.run_bundle(cache_key, source)    -> run a reused-across-VMs source
    #                                               bundle (engine may compile-cache)
    #
    # Value representation a backend must deliver across the boundary (host
    # function arguments and call_js results): JSON-ish Ruby values
    # (Hash/Array/String/Numeric/true/false/nil) carrying the WireTags protocol.
    # The backend does NOT need to distinguish JS `undefined` from `null` in its
    # value marshalling: host_runtime.js tags every top-level `undefined` crossing
    # to Ruby (dehydrateTop — callback/host returns, property-set values, call
    # args) as `{__rb_undefined: true}`, so it arrives as Dommy::Bridge::UNDEFINED
    # regardless of the engine (V8/mini_racer cannot tell the two apart, and need
    # not). As a defensive fallback, the bridge also normalizes a *bare* JS
    # `undefined` delivered as the Ruby symbol `:undefined` (a backend that can
    # produce it, like QuickJS) to Dommy::Bridge::UNDEFINED, but no backend is
    # required to.
    #
    # The host object must implement __js_get__/__js_set__/__js_call__, and the
    # bridge needs to know which names are methods (callable via __js_call__)
    # vs. properties (read via __js_get__) — see #method_names.
    class HostBridge
      # JS half of the bridge (globalThis.__rbHost). Read from a companion file
      # so it stays lintable/highlightable rather than buried in a heredoc.
      # ::File — inside module Dommy, bare `File` resolves to Dommy::File (the
      # File API class), not Ruby's file class. These bundles are identical
      # across VMs; the backend's #run_bundle keeps them parsed once per process,
      # so the bridge itself stays free of any bytecode/engine knowledge.
      # The specs' own enumerations (interface members, constants, arities, event
      # handler attributes), which host_runtime.js destructures — see the file's
      # header for what belongs there.
      WEBIDL_TABLES_JS = ::File.read(::File.join(__dir__, "webidl_tables.js")).freeze
      # The string conversions the specs' IDL declares for each operation,
      # constructor and attribute, generated from it by
      # script/build_webidl_signatures.rb; host_runtime.js carries them out.
      WEBIDL_SIGNATURES_JS = ::File.read(::File.join(__dir__, "webidl_signatures.js")).freeze
      # The members each interface prototype carries: the IDL's, as far as the
      # bridge classes answer them, generated by script/build_webidl_members.rb.
      WEBIDL_MEMBERS_JS = ::File.read(::File.join(__dir__, "webidl_members.js")).freeze
      # The event handler IDL attributes each interface declares, generated by
      # script/build_event_handlers.rb.
      WEBIDL_EVENT_HANDLERS_JS = ::File.read(::File.join(__dir__, "webidl_event_handlers.js")).freeze
      HOST_RUNTIME_JS = ::File.read(::File.join(__dir__, "host_runtime.js")).freeze
      # The WICG Observable polyfill (Observable/Subscriber + EventTarget.when),
      # evaluated after the DOM interface prototypes are seeded.
      OBSERVABLE_RUNTIME_JS = ::File.read(::File.join(__dir__, "observable_runtime.js")).freeze

      def initialize(backend)
        @backend = backend
        @profile = CrossingProfile.build
        # The marshaller owns value conversion + the handle/callback identity
        # tables; the bridge keeps the engine ABI and lifecycle wiring.
        @codec = Marshaller.new(self)
        @constructor_resolver = ConstructorResolver.new
        @custom_element_bridge = CustomElementBridge.new(self)
        @window_wiring = WindowWiring.new(@backend,
          script_runner: ->(source) { run_classic_script(source) },
          event_handler_compiler: ->(*args) { compile_event_handler(*args) },
          constructor_resolver: @constructor_resolver,
          custom_elements: @custom_element_bridge,
          microtask_scheduler: ->(callback) { schedule_native_microtask(callback) })
        @microtask_procs = {}
        @microtask_seq = 0
        @rejection_details = [] # opt-in rejection-debug capture (see take_rejection_detail)
        install!
      end

      # Bind a Ruby object to a JS global of the given name.
      def define_host_object(name, obj)
        @backend.call_js("__rbHost.defineGlobal", name.to_s, @codec.register(obj))
        obj
      end

      # Bind the window the bridge draws on for JS constructors (new Event(...))
      # and custom element registration. Called by Runtime#install_window — kept
      # distinct from define_host_object so the generic binder has no hidden
      # side effects. The realm wiring itself is WindowWiring's.
      def window=(win)
        @window = win # the window host promises (thenable adoption) schedule on
        @window_wiring.attach(win)
      end

      # Enqueue a Ruby callback as a NATIVE microtask (a resolved-promise job), so
      # it runs in FIFO order with the engine's other promise jobs.
      def schedule_native_microtask(callback)
        id = (@microtask_seq += 1)
        @microtask_procs[id] = callback
        @backend.call_js("__rbHost.scheduleMicrotask", id)
        nil
      end

      # Expose the seeded interface constructors (Element, Node, DOMException, …)
      # on a secondary window object — an iframe's contentWindow — so cross-window
      # `instanceof subWin.Element` and `subDoc.defaultView.DOMException` resolve
      # to the same constructors the top window uses. Idempotent per window.
      def expose_constructors_on(window_obj)
        @backend.call_js("__rbHost.exposeConstructorsOnSubWindow", @codec.register(window_obj))
        window_obj
      end

      # A JS custom element definition's constructor, constructed with no
      # arguments (DOM "create an element" with the synchronous custom
      # elements flag): what it returned, or its exception raised.
      def ce_construct(definition_id)
        callback_result(@backend.call_js("__rbHost.ceConstruct", definition_id), true)
      end

      # HTML "upgrade an element": construct the definition's constructor with
      # `element` on its construction stack. Raises what it threw.
      def ce_upgrade(definition_id, element)
        callback_result(@backend.call_js("__rbHost.ceUpgrade", definition_id, @codec.register(element)), true)
        nil
      end

      # A JS custom element definition's lifecycle callback, called with
      # `element` as `this`. Raises what it threw.
      def ce_invoke(definition_id, element, callback_name, args)
        raw = @backend.call_js("__rbHost.ceInvoke", definition_id, @codec.register(element), callback_name.to_s,
                               wrap(Array(args)))
        callback_result(raw, true)
        nil
      end

      # Invoke a retained live JS function by id (used by HostCallback). The JS
      # side returns a `dehydrate`d (tagged) value, so unwrap it back to Ruby:
      # a callback that returns e.g. a Promise proxy must come back as the live
      # PromiseValue, otherwise Dommy can't adopt it (breaking
      # `fetch().then(r => r.json()).then(…)` chains).
      # `raising: true` re-raises a thrown value (as a ThrowValue dom_guard
      # rethrows verbatim) where the spec requires the exception to propagate — a
      # NodeFilter whose error must surface out of the traversal method that ran
      # it. The default swallows it: event listeners / observers / timers must not
      # let a callback error escape their dispatch.
      def invoke_callback(id, args, this_arg = nil, raising: false)
        callback_result(@backend.call_js("__rbHost.invokeCallback", id, wrap(Array(args)), wrap(this_arg)), raising)
      end

      # Run a classic script's source in the realm's global scope (an inserted
      # `<script>`, a string timer handler). What it throws — a compile error
      # included — re-raises as a ThrowValue carrying the thrown value, so the
      # report of it hands the page the Error it threw.
      def run_classic_script(source)
        callback_result(@backend.call_js("__rbHost.runScript", source.to_s), true)
      end

      # Compile an event handler content attribute's body (see
      # Document#event_handler_compiler): the function, or the SyntaxError of a
      # body that does not parse, raised as a ThrowValue.
      def compile_event_handler(element, name, source, window_handler)
        callback_result(@backend.call_js("__rbHost.compileEventHandler", wrap(element), name.to_s, source.to_s,
          window_handler ? true : false), true)
      end

      # StructuredDeserializeWithTransfer of a record the realm serialized (see
      # SerializedRecord): `{"value" => …, "ports" => [MessagePort…]}`, or
      # `{"error" => message}` when it cannot be deserialized.
      def deserialize_record(id)
        unwrap(@backend.call_js("__rbHost.deserializeRecord", id))
      end

      def release_record(id)
        @backend.call_js("__rbHost.releaseRecord", id)
        nil
      end

      # Invoke a JS EventListener *object*'s handleEvent (see HostEventListener),
      # passing the dispatched event as a proxy. A thrown value re-raises as a
      # ThrowValue (identity preserved) so event dispatch can report it as a
      # window `error` event — EventTarget#invoke_listener_isolated catches it,
      # rather than letting it escape the dispatch.
      def invoke_js_ref_handle_event(ref, event)
        callback_result(@backend.call_js("__rbHost.invokeJsRefHandleEvent", ref, wrap(event)), true)
      end

      # Invoke a JS NodeFilter object's acceptNode (see HostNodeFilter). `raising`
      # re-raises a thrown value (the traversal must propagate it) rather than
      # swallowing it.
      def invoke_js_ref_accept_node(ref, node, raising: false)
        callback_result(@backend.call_js("__rbHost.invokeJsRefAcceptNode", ref, wrap(node)), raising)
      end

      # Turn a JS-side tagged value (produced by __rbHost.tag) back into Ruby:
      # tagged handles become the original Ruby DOM objects. Used for return
      # values that may contain DOM nodes (e.g. evaluate_script).
      def decode(tagged)
        unwrap(tagged)
      end

      # Ruby -> JS: the wire-tagged shape of `value` (a DOM object becomes
      # `{__rb_handle: id, …}`). Used to pass script arguments into the VM
      # (execute_script / evaluate_script), which rehydrate them JS-side.
      def encode(value)
        wrap(value)
      end

      # Number of live handle entries. Introspection for lifetime tests.
      def registered_count
        @codec.size
      end

      # Snapshot bridge crossing counts, enabled with DOMMY_JS_BRIDGE_PROFILE=1.
      # Counts are grouped by ABI function name, with a nested breakdown of the
      # hottest interface/property or interface/method labels where available.
      def crossing_counts(limit: nil) = @profile.snapshot(limit: limit)

      def reset_crossing_counts
        @profile.reset
        self
      end

      # Drain the most-recent recorded rejection detail (paired by recency with the
      # engine's detail-less "[object Object]" report). Nil when none recorded /
      # the opt-in tracker (installRejectionTracker) isn't installed.
      def take_rejection_detail
        @rejection_details.pop
      end

      private

      # Register the host-function ABI in cohesive groups, then run the JS-side
      # runtime that consumes it. Registration order among the groups is
      # irrelevant (they only define functions); seed_runtime! must run last,
      # since the runtime it loads calls back into these functions.
      def install!
        install_object_abi!
        install_lifecycle_abi!
        install_construction_abi!
        install_custom_elements_abi!
        seed_runtime!
      end

      # A host object's property/method ABI, plus the legacy-platform-object
      # named-property protocol (named getter/deleter) and the self-describe call
      # makeProxy uses to build the right JS prototype.
      def install_object_abi!
        @backend.define_host_function("__rb_host_get") do |handle, prop|
          dom_guard do
            obj = host(handle)
            @profile.count(:__rb_host_get, obj, prop)
            wrap(obj.respond_to?(:__js_get__) ? obj.__js_get__(prop) : nil)
          end
        end
        @backend.define_host_function("__rb_host_set") do |handle, prop, value|
          # Returns whether Dommy handled the write as a DOM property. When it
          # didn't (or the object has no __js_set__), the JS side keeps the value
          # as an expando (preserving object/instance field identity). Wrapped in
          # dom_guard so a throwing setter (e.g. `documentElement.outerHTML = …` →
          # NoModificationAllowedError) crosses as a tagged exception the JS set
          # trap re-throws, rather than escaping as a raw Ruby error.
          dom_guard do
            obj = host(handle)
            @profile.count(:__rb_host_set, obj, prop)
            next false unless obj.respond_to?(:__js_set__)

            ce_reactions(obj, :set, prop) { dommy_handled?(obj.__js_set__(prop, unwrap(value))) }
          end
        end
        # Unlistened-dispatch fast path (see dommy-js-quickjs
        # docs/event-dispatch-fastpath.md): a namespaced event type (contains
        # ":", so no built-in default action exists for it) with no listener
        # ever registered for it process-wide dispatches here in ONE crossing,
        # and the JS side skips its epoch bumps — nothing could have mutated
        # the DOM. Anything else returns fast:false and takes the classic path.
        # Type-only variant for JS-side events (docs/js-side-events-design.md):
        # true when a dispatch of this type can run entirely JS-side (namespaced
        # type, no listener ever registered for it).
        @backend.define_host_function("__rb_host_event_fast") do |type|
          @profile.count(:__rb_host_event_fast)
          t = type.to_s
          t.include?(":") && !Dommy::EventTarget.__internal_type_listened__?(t)
        end
        @backend.define_host_function("__rb_host_dispatch_fast") do |handle, event_handle|
          dom_guard do
            target = host(handle)
            event = host(event_handle)
            @profile.count(:__rb_host_dispatch_fast, target)
            type = event.respond_to?(:type) ? event.type.to_s : ""
            if type.include?(":") && !Dommy::EventTarget.__internal_type_listened__?(type) &&
               target.respond_to?(:dispatch_event)
              {"fast" => true, "result" => target.dispatch_event(event) ? true : false}
            else
              {"fast" => false}
            end
          end
        end
        @backend.define_host_function("__rb_host_call") do |handle, method, args|
          dom_guard do
            obj = host(handle)
            @profile.count(:__rb_host_call, obj, method)
            next nil unless obj.respond_to?(:__js_call__)

            ce_reactions(obj, :call, method) { wrap(obj.__js_call__(method, unwrap(args))) }
          end
        end
        # A pending host PromiseValue used to ADOPT a JS thenable returned from a
        # `.then` callback (Promises/A+): the JS side subscribes the thenable to
        # settle this promise, so the host chain WAITS for the thenable instead of
        # resolving immediately with an opaque ref (the HttpLink #95 reorder).
        @backend.define_host_function("__rb_new_host_promise") do
          @profile.count(:__rb_new_host_promise)
          dom_guard { @codec.register(Dommy::PromiseValue.new(@window)) }
        end
        # A host PromiseValue crossing into JS becomes a realm Promise
        # (host_runtime.js realmPromiseFor), which subscribes here to be settled
        # with it.
        @backend.define_host_function("__rb_host_promise_subscribe") do |handle, on_fulfilled, on_rejected|
          @profile.count(:__rb_host_promise_subscribe)
          dom_guard do
            host(handle).__internal_subscribe__(unwrap(on_fulfilled), unwrap(on_rejected))
            nil
          end
        end
        @backend.define_host_function("__rb_settle_host_promise") do |handle, fulfilled, value|
          @profile.count(:__rb_settle_host_promise)
          dom_guard do
            promise = host(handle)
            fulfilled ? promise.fulfill(unwrap(value)) : promise.reject(unwrap(value))
            nil
          end
        end
        # Structured serialization of a platform object (host_runtime.js
        # structuredSerializeInternal): a serializable one answers
        # `__internal_structured_clone__(for_storage)` with a new object holding
        # the same data — the snapshot a record keeps, and each deserialized
        # copy; anything else is a DataCloneError.
        @backend.define_host_function("__rb_host_clone") do |handle, for_storage|
          @profile.count(:__rb_host_clone)
          dom_guard do
            obj = host(handle)
            unless obj.respond_to?(:__internal_structured_clone__)
              raise DOMException::DataCloneError, "#{DomInterfaces.info(obj)["name"] || obj.class.name} object could not be cloned"
            end

            wrap(obj.__internal_structured_clone__(for_storage ? true : false))
          end
        end
        # A transferable platform object's state: "transferable", "detached"
        # (its [[Detached]] slot is true), or nil for one that is not
        # transferable at all.
        @backend.define_host_function("__rb_host_transfer_state") do |handle|
          @profile.count(:__rb_host_transfer_state)
          obj = host(handle)
          next nil unless obj.respond_to?(:__internal_transfer__)

          obj.respond_to?(:__internal_detached__?) && obj.__internal_detached__? ? "detached" : "transferable"
        end
        # The transfer steps + transfer-receiving steps: the object is detached
        # and the new one that takes over its data is returned.
        @backend.define_host_function("__rb_host_transfer") do |handle|
          @profile.count(:__rb_host_transfer)
          dom_guard { wrap(host(handle).__internal_transfer__) }
        end
        # A piece of a host object's internal state an algorithm running JS-side
        # needs before it crosses (a BroadcastChannel's closed flag, a port's
        # entangled port, whether a History's document is fully active):
        # `__internal_state__(name)`, never a page-visible member.
        @backend.define_host_function("__rb_host_state") do |handle, name|
          @profile.count(:__rb_host_state, nil, name)
          dom_guard do
            obj = host(handle)
            wrap(obj.respond_to?(:__internal_state__) ? obj.__internal_state__(name.to_s) : nil)
          end
        end
        # 2d: one call returns everything makeProxy needs — interface name +
        # chain, and method names.
        @backend.define_host_function("__rb_host_describe") do |handle|
          obj = host(handle)
          @profile.count(:__rb_host_describe, obj)
          info = DomInterfaces.info(obj)
          info["methods"] = method_names(obj)
          info
        end
        # One-shot attribute snapshot for the JS-side attribute cache: a plain
        # {qualified_name => value} Hash (an element with case-insensitive
        # attribute lookups), or nil (anything else — the JS side keeps the
        # per-call path). Staleness is the JS side's concern (the DOM epoch).
        @backend.define_host_function("__rb_host_attrs") do |handle|
          dom_guard do
            obj = host(handle)
            @profile.count(:__rb_host_attrs, obj)
            obj.respond_to?(:__js_attribute_snapshot__) ? obj.__js_attribute_snapshot__ : nil
          end
        end
        # WebIDL "supported property names" for a legacy platform object (a live
        # array-like/maplike collection): the current ordered named-property
        # keys. Queried per ownKeys / getOwnPropertyDescriptor so it tracks DOM
        # mutations. Nil when the object has no named getter.
        @backend.define_host_function("__rb_named_props") do |handle|
          obj = host(handle)
          @profile.count(:__rb_named_props, obj)
          obj.respond_to?(:__js_named_props__) ? Array(obj.__js_named_props__).map(&:to_s) : nil
        end
        # A named property's value, for an object whose named properties
        # override its builtins: `__js_named_get__` when the object separates
        # the two (a document answers `body` as a builtin from `__js_get__`),
        # else `__js_get__`, which then answers named properties first.
        @backend.define_host_function("__rb_named_get") do |handle, prop|
          dom_guard do
            obj = host(handle)
            @profile.count(:__rb_named_get, obj, prop)
            value = obj.respond_to?(:__js_named_get__) ? obj.__js_named_get__(prop.to_s) : obj.__js_get__(prop.to_s)
            wrap(value)
          end
        end
        # Named deleter (`delete el.dataset.foo`): true when the object handled
        # the delete, false/UNHANDLED when the JS side should fall back to its
        # own (expando) delete.
        @backend.define_host_function("__rb_host_delete") do |handle, prop|
          dom_guard do
            obj = host(handle)
            @profile.count(:__rb_host_delete, obj, prop)
            next false unless obj.respond_to?(:__js_delete__)

            ce_reactions(obj, :delete, prop) { dommy_handled?(obj.__js_delete__(prop)) }
          end
        end
      end

      # VM bookkeeping: proxy-handle release (driven by JS GC) and the native
      # microtask drain hook.
      def install_lifecycle_abi!
        @backend.define_host_function("__rb_release_handle") do |handle|
          @profile.count(:__rb_release_handle)
          @codec.release(handle)
          nil
        end
        # Run a Ruby microtask previously registered by schedule_native_microtask,
        # invoked from the resolved-promise job scheduleMicrotask queued.
        @backend.define_host_function("__rb_run_microtask") do |id|
          @profile.count(:__rb_run_microtask)
          callback = @microtask_procs.delete(id)
          callback&.call
          nil
        end
        # Opt-in rejection diagnostics: __rbHost.installRejectionTracker (only run
        # when asked) records a rich description of each promise rejection here, at
        # reject time, so #take_rejection_detail can replace the engine's
        # detail-less "[object Object]" unhandled-rejection report with the truth.
        # The engine's promise-rejection hook (see host_runtime.js
        # onPromiseRejection). Unlike the Ruby-level `on_unhandled_rejection`,
        # which hands over an exception the engine already converted, this keeps
        # the promise and the reason as the values the page threw — so
        # `event.reason` / `event.promise` are real, and a later "handled" can be
        # paired with the report it retracts.
        @backend.define_host_function("__rb_promise_rejection") do |type, promise, reason|
          window = @window
          if window.respond_to?(:__internal_handle_promise_rejection__)
            window.__internal_handle_promise_rejection__(type.to_s, unwrap(reason), promise: unwrap(promise))
          end
          nil
        end
        @backend.define_host_function("__rb_record_rejection_detail") do |detail|
          @rejection_details.push(detail.to_s)
          @rejection_details.shift if @rejection_details.size > 256
          nil
        end
      end

      # Reverse construction (`new Event(...)`) and interface static methods
      # (URL.createObjectURL, …).
      def install_construction_abi!
        # `new Event(...)` / `new DOMException(...)` from a bare interface
        # constructor — resolve the named constructor and build. Returns nil when
        # the interface isn't constructable, so the JS side throws.
        @backend.define_host_function("__rb_construct") do |name, args|
          @profile.count(:__rb_construct, nil, name)
          dom_guard do
            ctor = @constructor_resolver.resolve(name)
            ctor ? wrap(ctor.__js_new__(unwrap(args))) : nil
          end
        end
        # Static/class methods on an interface constructor (URL.createObjectURL,
        # URL.parse, …): names to expose, and the dispatch.
        @backend.define_host_function("__rb_static_names") do |name|
          @profile.count(:__rb_static_names, nil, name)
          @constructor_resolver.static_names(name)
        end
        # The same for every seeded interface at once — {name => [methods]},
        # interfaces without statics left out — so attaching them to the
        # globals is one crossing per window rather than one per interface.
        @backend.define_host_function("__rb_static_names_all") do |names|
          @profile.count(:__rb_static_names_all)
          Array(names).each_with_object({}) do |name, out|
            methods = @constructor_resolver.static_names(name)
            out[name] = methods unless methods.empty?
          end
        end
        @backend.define_host_function("__rb_static_call") do |name, method, args|
          @profile.count(:__rb_static_call, nil, "#{name}.#{method}")
          dom_guard do
            ctor = @constructor_resolver.resolve(name)
            ctor.respond_to?(:__js_call__) ? wrap(ctor.__js_call__(method, unwrap(args))) : nil
          end
        end
      end

      # A registry's define() / upgrade(), and the HTML element constructor's
      # fresh element — the Ruby halves of the JS custom element registry (see
      # CustomElementBridge).
      def install_custom_elements_abi!
        @backend.define_host_function("__rb_define_custom_element") do |registry, id, name, local_name, observed, callbacks, disabled, form_associated|
          @profile.count(:__rb_define_custom_element, nil, name)
          dom_guard do
            @custom_element_bridge.define(host(registry), id, name, local_name, Array(observed), Array(callbacks),
                                          disabled_features: Array(disabled), form_associated: form_associated)
            nil
          end
        end
        @backend.define_host_function("__rb_upgrade_custom_elements") do |registry, root|
          @profile.count(:__rb_upgrade_custom_elements)
          dom_guard do
            host(registry).upgrade(host(root))
            nil
          end
        end
        # The HTML element constructor with an empty construction stack
        # (`new MyElement()`): a fresh element of the definition.
        @backend.define_host_function("__rb_create_custom_element") do |id|
          @profile.count(:__rb_create_custom_element, nil, id)
          dom_guard { wrap(@custom_element_bridge.create(id)) }
        end
        # `new CustomElementRegistry()`: a scoped registry of the window.
        @backend.define_host_function("__rb_new_custom_element_registry") do
          @profile.count(:__rb_new_custom_element_registry)
          dom_guard { wrap(@custom_element_bridge.new_scoped_registry) }
        end
        @backend.define_host_function("__rb_initialize_custom_element_registry") do |registry, root|
          @profile.count(:__rb_initialize_custom_element_registry)
          dom_guard do
            host(registry).initialize_registry(host(root))
            nil
          end
        end
        # The interface `localName` names in the HTML namespace (define()'s
        # `extends` check).
        @backend.define_host_function("__rb_html_interface_for") do |local_name|
          DomInterfaces.class_chain(Dommy.element_class_for(local_name.to_s, Dommy::Element::HTML_NAMESPACE)).first
        end
      end

      # Run the JS half of the bridge and seed the interface prototypes. Must run
      # after every host function above is registered.
      def seed_runtime!
        @backend.run_bundle("webidl_tables.js", WEBIDL_TABLES_JS)
        @backend.run_bundle("webidl_signatures.js", WEBIDL_SIGNATURES_JS)
        @backend.run_bundle("webidl_members.js", WEBIDL_MEMBERS_JS)
        @backend.run_bundle("webidl_event_handlers.js", WEBIDL_EVENT_HANDLERS_JS)
        @backend.run_bundle("host_runtime.js", HOST_RUNTIME_JS)
        # Seed base interface prototypes from the single Ruby-side hierarchy.
        @backend.eval("__rbHost.seedInterfaces(#{JSON.generate(DomInterfaces::BASE_CHAINS)});")
        # Observable depends on EventTarget.prototype existing (seeded above).
        @backend.run_bundle("observable_runtime.js", OBSERVABLE_RUNTIME_JS)
      end

      # The strict handle lookup for a receiver (raises on a missing handle,
      # unlike the tolerant argument path in Marshaller#unwrap).
      def host(handle)
        @codec.host(handle)
      end

      # Marshalling is the Marshaller's job; the bridge calls these from its ABI
      # blocks and invoke_* helpers.
      # A script's call of a [CEReactions] member runs in a custom element
      # reactions scope (HTML §4.13.6); any other just runs.
      def ce_reactions(obj, kind, name, &block)
        return yield unless Internal::CEReactions.member?(obj, kind, name.to_s)

        Internal::CEReactions.scope(&block)
      end

      def wrap(value) = @codec.wrap(value)
      def unwrap(value) = @codec.unwrap(value)
      def dom_guard(&block) = @codec.dom_guard(&block)
      def callback_result(raw, raising) = @codec.callback_result(raw, raising)

      # Which property names should be treated as callable methods. The ABI
      # keeps properties (__js_get__) and methods (__js_call__) in disjoint
      # namespaces, so the proxy asks the object to self-describe via the bridge
      # ABI method __js_method_names__. method_defined? (not respond_to?) avoids
      # classes whose respond_to_missing? answers true for arbitrary names (e.g.
      # StyleDeclaration's CSS-property accessors).
      def method_names(obj)
        return [] unless obj.class.method_defined?(:__js_method_names__)

        Array(obj.__js_method_names__).map(&:to_s)
      end

      # Did Dommy treat a __js_set__ as a real DOM property? A returned UNHANDLED
      # sentinel means "no" (the JS side then keeps it as an expando).
      def dommy_handled?(result)
        result != Dommy::Bridge::UNHANDLED
      end
    end
  end
end
