// GENERATED by script/build_webidl_signatures.rb from
// test/fixtures/webidl/interfaces.json (web-platform-tests 863077959ca8c1a7ceecfbe2534b75d2527b9013).
// Do not edit by hand: re-run the script (`rake webidl:signatures`).
//
// For each interface, what WebIDL checks and converts of a script's
// values before the member sees them. An operation, static operation or
// constructor has `required`, the number of arguments a call must pass
// (fewer is a TypeError), and `arguments`, one string conversion per
// position; a writable attribute has its value's string conversion. A
// conversion is a string type ("DOMString", "USVString", "ByteString"),
// "?" after it when nullable, "[LegacyNullToEmptyString] " before it when
// null means "", "optional " before it when undefined is left for the
// default, and "..." after it when it converts every remaining argument.
// null is a position that is not a string type, or a member with nothing
// to check where an ancestor's member of the same name has something.
// `inherits` is the IDL parent.
//
// Read by host_runtime.js (see "WebIDL string conversions" there), which
// is the one place the conversions are carried out.
globalThis.__rbIdlSignatures = {
  "AbortSignal": {
    "inherits": "EventTarget",
    "static_operations": {
      "any": {"required":1},
      "timeout": {"required":1}
    }
  },
  "AnimationEvent": {
    "constructor": {"required":1,"arguments":["DOMString"]},
    "inherits": "Event"
  },
  "Attr": {
    "inherits": "Node",
    "attributes": {
      "value": "DOMString"
    }
  },
  "AudioTrackList": {
    "inherits": "EventTarget",
    "operations": {
      "getTrackById": {"required":1,"arguments":["DOMString"]}
    }
  },
  "BeforeUnloadEvent": {
    "inherits": "Event",
    "attributes": {
      "returnValue": "DOMString"
    }
  },
  "Blob": {
    "operations": {
      "slice": {"required":0,"arguments":[null,null,"optional DOMString"]}
    }
  },
  "BroadcastChannel": {
    "constructor": {"required":1,"arguments":["DOMString"]},
    "inherits": "EventTarget",
    "operations": {
      "postMessage": {"required":1}
    }
  },
  "ByteLengthQueuingStrategy": {
    "constructor": {"required":1}
  },
  "CDATASection": {
    "inherits": "Text"
  },
  "CSSGroupingRule": {
    "inherits": "CSSRule",
    "operations": {
      "deleteRule": {"required":1},
      "insertRule": {"required":1,"arguments":["DOMString"]}
    }
  },
  "CSSImportRule": {
    "inherits": "CSSRule"
  },
  "CSSKeyframeRule": {
    "inherits": "CSSRule",
    "attributes": {
      "keyText": "DOMString"
    }
  },
  "CSSKeyframesRule": {
    "inherits": "CSSRule",
    "operations": {
      "appendRule": {"required":1,"arguments":["DOMString"]},
      "deleteRule": {"required":1,"arguments":["DOMString"]},
      "findRule": {"required":1,"arguments":["DOMString"]}
    },
    "attributes": {
      "name": "DOMString"
    }
  },
  "CSSMarginRule": {
    "inherits": "CSSRule"
  },
  "CSSNamespaceRule": {
    "inherits": "CSSRule"
  },
  "CSSPageDescriptors": {
    "inherits": "CSSStyleDeclaration",
    "attributes": {
      "bleed": "[LegacyNullToEmptyString] DOMString",
      "margin": "[LegacyNullToEmptyString] DOMString",
      "margin-bottom": "[LegacyNullToEmptyString] DOMString",
      "margin-left": "[LegacyNullToEmptyString] DOMString",
      "margin-right": "[LegacyNullToEmptyString] DOMString",
      "margin-top": "[LegacyNullToEmptyString] DOMString",
      "marginBottom": "[LegacyNullToEmptyString] DOMString",
      "marginLeft": "[LegacyNullToEmptyString] DOMString",
      "marginRight": "[LegacyNullToEmptyString] DOMString",
      "marginTop": "[LegacyNullToEmptyString] DOMString",
      "marks": "[LegacyNullToEmptyString] DOMString",
      "page-orientation": "[LegacyNullToEmptyString] DOMString",
      "pageOrientation": "[LegacyNullToEmptyString] DOMString",
      "size": "[LegacyNullToEmptyString] DOMString"
    }
  },
  "CSSPageRule": {
    "inherits": "CSSGroupingRule",
    "attributes": {
      "selectorText": "DOMString"
    }
  },
  "CSSRule": {
    "attributes": {
      "cssText": "DOMString"
    }
  },
  "CSSRuleList": {
    "operations": {
      "item": {"required":1}
    }
  },
  "CSSStyleDeclaration": {
    "operations": {
      "getPropertyPriority": {"required":1,"arguments":["DOMString"]},
      "getPropertyValue": {"required":1,"arguments":["DOMString"]},
      "item": {"required":1},
      "removeProperty": {"required":1,"arguments":["DOMString"]},
      "setProperty": {"required":2,"arguments":["DOMString","[LegacyNullToEmptyString] DOMString","optional [LegacyNullToEmptyString] DOMString"]}
    },
    "attributes": {
      "cssText": "DOMString"
    }
  },
  "CSSStyleProperties": {
    "inherits": "CSSStyleDeclaration",
    "attributes": {
      "cssFloat": "[LegacyNullToEmptyString] DOMString"
    }
  },
  "CSSStyleRule": {
    "inherits": "CSSGroupingRule",
    "attributes": {
      "selectorText": "DOMString"
    }
  },
  "CSSStyleSheet": {
    "inherits": "StyleSheet",
    "operations": {
      "addRule": {"required":0,"arguments":["optional DOMString","optional DOMString"]},
      "deleteRule": {"required":1},
      "insertRule": {"required":1,"arguments":["DOMString"]},
      "replace": {"required":1,"arguments":["USVString"]},
      "replaceSync": {"required":1,"arguments":["USVString"]}
    }
  },
  "CanvasGradient": {
    "operations": {
      "addColorStop": {"required":2,"arguments":[null,"DOMString"]}
    }
  },
  "CanvasRenderingContext2D": {
    "operations": {
      "arc": {"required":5},
      "arcTo": {"required":5},
      "bezierCurveTo": {"required":6},
      "clearRect": {"required":4},
      "createConicGradient": {"required":3},
      "createImageData": {"required":1},
      "createLinearGradient": {"required":4},
      "createPattern": {"required":2,"arguments":[null,"[LegacyNullToEmptyString] DOMString"]},
      "createRadialGradient": {"required":6},
      "drawFocusIfNeeded": {"required":1},
      "drawImage": {"required":3},
      "ellipse": {"required":7},
      "fillRect": {"required":4},
      "fillText": {"required":3,"arguments":["DOMString"]},
      "getImageData": {"required":4},
      "isPointInPath": {"required":2},
      "isPointInStroke": {"required":2},
      "lineTo": {"required":2},
      "measureText": {"required":1,"arguments":["DOMString"]},
      "moveTo": {"required":2},
      "putImageData": {"required":3},
      "quadraticCurveTo": {"required":4},
      "rect": {"required":4},
      "rotate": {"required":1},
      "roundRect": {"required":4},
      "scale": {"required":2},
      "setLineDash": {"required":1},
      "strokeRect": {"required":4},
      "strokeText": {"required":3,"arguments":["DOMString"]},
      "transform": {"required":6},
      "translate": {"required":2}
    },
    "attributes": {
      "filter": "DOMString",
      "font": "DOMString",
      "globalCompositeOperation": "DOMString",
      "lang": "DOMString",
      "letterSpacing": "DOMString",
      "shadowColor": "DOMString",
      "wordSpacing": "DOMString"
    }
  },
  "CharacterData": {
    "inherits": "Node",
    "operations": {
      "appendData": {"required":1,"arguments":["DOMString"]},
      "deleteData": {"required":2},
      "insertData": {"required":2,"arguments":[null,"DOMString"]},
      "replaceData": {"required":3,"arguments":[null,null,"DOMString"]},
      "substringData": {"required":2}
    },
    "attributes": {
      "data": "[LegacyNullToEmptyString] DOMString"
    }
  },
  "CloseEvent": {
    "constructor": {"required":1,"arguments":["DOMString"]},
    "inherits": "Event"
  },
  "CloseWatcher": {
    "inherits": "EventTarget"
  },
  "CommandEvent": {
    "constructor": {"required":1,"arguments":["DOMString"]},
    "inherits": "Event"
  },
  "Comment": {
    "constructor": {"required":0,"arguments":["optional DOMString"]},
    "inherits": "CharacterData"
  },
  "CompositionEvent": {
    "constructor": {"required":1,"arguments":["DOMString"]},
    "inherits": "UIEvent",
    "operations": {
      "initCompositionEvent": {"required":1,"arguments":["DOMString",null,null,null,"optional DOMString"]}
    }
  },
  "CountQueuingStrategy": {
    "constructor": {"required":1}
  },
  "CustomElementRegistry": {
    "operations": {
      "define": {"required":2,"arguments":["DOMString"]},
      "get": {"required":1,"arguments":["DOMString"]},
      "getName": {"required":1},
      "initialize": {"required":1},
      "upgrade": {"required":1},
      "whenDefined": {"required":1,"arguments":["DOMString"]}
    }
  },
  "CustomEvent": {
    "constructor": {"required":1,"arguments":["DOMString"]},
    "inherits": "Event",
    "operations": {
      "initCustomEvent": {"required":1,"arguments":["DOMString"]}
    }
  },
  "DOMImplementation": {
    "operations": {
      "createDocument": {"required":2,"arguments":["DOMString?","[LegacyNullToEmptyString] DOMString"]},
      "createDocumentType": {"required":3,"arguments":["DOMString","DOMString","DOMString"]},
      "createHTMLDocument": {"required":0,"arguments":["optional DOMString"]}
    }
  },
  "DOMParser": {
    "operations": {
      "parseFromString": {"required":2,"arguments":["DOMString"]}
    }
  },
  "DOMStringList": {
    "operations": {
      "contains": {"required":1,"arguments":["DOMString"]},
      "item": {"required":1}
    }
  },
  "DOMTokenList": {
    "operations": {
      "add": {"required":0,"arguments":["DOMString..."]},
      "contains": {"required":1,"arguments":["DOMString"]},
      "item": {"required":1},
      "remove": {"required":0,"arguments":["DOMString..."]},
      "replace": {"required":2,"arguments":["DOMString","DOMString"]},
      "supports": {"required":1,"arguments":["DOMString"]},
      "toggle": {"required":1,"arguments":["DOMString"]}
    },
    "attributes": {
      "value": "DOMString"
    }
  },
  "DataTransfer": {
    "operations": {
      "clearData": {"required":0,"arguments":["optional DOMString"]},
      "getData": {"required":1,"arguments":["DOMString"]},
      "setData": {"required":2,"arguments":["DOMString","DOMString"]},
      "setDragImage": {"required":3}
    },
    "attributes": {
      "dropEffect": "DOMString",
      "effectAllowed": "DOMString"
    }
  },
  "DataTransferItem": {
    "operations": {
      "getAsString": {"required":1}
    }
  },
  "DataTransferItemList": {
    "operations": {
      "add": {"required":1,"arguments":[null,"optional DOMString"]},
      "remove": {"required":1}
    }
  },
  "DedicatedWorkerGlobalScope": {
    "inherits": "WorkerGlobalScope",
    "operations": {
      "cancelAnimationFrame": {"required":1},
      "postMessage": {"required":1},
      "requestAnimationFrame": {"required":1}
    }
  },
  "Document": {
    "inherits": "Node",
    "operations": {
      "adoptNode": {"required":1},
      "ariaNotify": {"required":1,"arguments":["DOMString"]},
      "caretPositionFromPoint": {"required":2},
      "convertPointFromNode": {"required":2},
      "convertQuadFromNode": {"required":2},
      "convertRectFromNode": {"required":2},
      "createAttribute": {"required":1,"arguments":["DOMString"]},
      "createAttributeNS": {"required":2,"arguments":["DOMString?","DOMString"]},
      "createCDATASection": {"required":1,"arguments":["DOMString"]},
      "createComment": {"required":1,"arguments":["DOMString"]},
      "createElement": {"required":1,"arguments":["DOMString"]},
      "createElementNS": {"required":2,"arguments":["DOMString?","DOMString"]},
      "createEvent": {"required":1,"arguments":["DOMString"]},
      "createExpression": {"required":1,"arguments":["DOMString"]},
      "createNSResolver": {"required":1},
      "createNodeIterator": {"required":1},
      "createProcessingInstruction": {"required":2,"arguments":["DOMString","DOMString"]},
      "createTextNode": {"required":1,"arguments":["DOMString"]},
      "createTreeWalker": {"required":1},
      "elementFromPoint": {"required":2},
      "elementsFromPoint": {"required":2},
      "evaluate": {"required":2,"arguments":["DOMString"]},
      "execCommand": {"required":1,"arguments":["DOMString",null,"optional DOMString"]},
      "getElementById": {"required":1,"arguments":["DOMString"]},
      "getElementsByClassName": {"required":1,"arguments":["DOMString"]},
      "getElementsByName": {"required":1,"arguments":["DOMString"]},
      "getElementsByTagName": {"required":1,"arguments":["DOMString"]},
      "getElementsByTagNameNS": {"required":2,"arguments":["DOMString?","DOMString"]},
      "importNode": {"required":1},
      "moveBefore": {"required":2},
      "open": {"required":0,"arguments":[null,"optional DOMString","optional DOMString"]},
      "queryCommandEnabled": {"required":1,"arguments":["DOMString"]},
      "queryCommandIndeterm": {"required":1,"arguments":["DOMString"]},
      "queryCommandState": {"required":1,"arguments":["DOMString"]},
      "queryCommandSupported": {"required":1,"arguments":["DOMString"]},
      "queryCommandValue": {"required":1,"arguments":["DOMString"]},
      "querySelector": {"required":1,"arguments":["DOMString"]},
      "querySelectorAll": {"required":1,"arguments":["DOMString"]},
      "write": {"required":0,"arguments":["DOMString..."]},
      "writeln": {"required":0,"arguments":["DOMString..."]}
    },
    "static_operations": {
      "parseHTML": {"required":1,"arguments":["DOMString"]},
      "parseHTMLUnsafe": {"required":1,"arguments":["DOMString"]}
    },
    "attributes": {
      "alinkColor": "[LegacyNullToEmptyString] DOMString",
      "bgColor": "[LegacyNullToEmptyString] DOMString",
      "cookie": "USVString",
      "designMode": "DOMString",
      "dir": "DOMString",
      "domain": "USVString",
      "fgColor": "[LegacyNullToEmptyString] DOMString",
      "linkColor": "[LegacyNullToEmptyString] DOMString",
      "title": "DOMString",
      "vlinkColor": "[LegacyNullToEmptyString] DOMString"
    }
  },
  "DocumentFragment": {
    "inherits": "Node",
    "operations": {
      "getElementById": {"required":1,"arguments":["DOMString"]},
      "moveBefore": {"required":2},
      "querySelector": {"required":1,"arguments":["DOMString"]},
      "querySelectorAll": {"required":1,"arguments":["DOMString"]}
    }
  },
  "DocumentType": {
    "inherits": "Node"
  },
  "DragEvent": {
    "constructor": {"required":1,"arguments":["DOMString"]},
    "inherits": "MouseEvent"
  },
  "Element": {
    "inherits": "Node",
    "operations": {
      "ariaNotify": {"required":1,"arguments":["DOMString"]},
      "attachShadow": {"required":1},
      "closest": {"required":1,"arguments":["DOMString"]},
      "convertPointFromNode": {"required":2},
      "convertQuadFromNode": {"required":2},
      "convertRectFromNode": {"required":2},
      "getAttribute": {"required":1,"arguments":["DOMString"]},
      "getAttributeNS": {"required":2,"arguments":["DOMString?","DOMString"]},
      "getAttributeNode": {"required":1,"arguments":["DOMString"]},
      "getAttributeNodeNS": {"required":2,"arguments":["DOMString?","DOMString"]},
      "getElementsByClassName": {"required":1,"arguments":["DOMString"]},
      "getElementsByTagName": {"required":1,"arguments":["DOMString"]},
      "getElementsByTagNameNS": {"required":2,"arguments":["DOMString?","DOMString"]},
      "hasAttribute": {"required":1,"arguments":["DOMString"]},
      "hasAttributeNS": {"required":2,"arguments":["DOMString?","DOMString"]},
      "hasPointerCapture": {"required":1},
      "insertAdjacentElement": {"required":2,"arguments":["DOMString"]},
      "insertAdjacentHTML": {"required":2,"arguments":["DOMString","DOMString"]},
      "insertAdjacentText": {"required":2,"arguments":["DOMString","DOMString"]},
      "matches": {"required":1,"arguments":["DOMString"]},
      "moveBefore": {"required":2},
      "querySelector": {"required":1,"arguments":["DOMString"]},
      "querySelectorAll": {"required":1,"arguments":["DOMString"]},
      "releasePointerCapture": {"required":1},
      "removeAttribute": {"required":1,"arguments":["DOMString"]},
      "removeAttributeNS": {"required":2,"arguments":["DOMString?","DOMString"]},
      "removeAttributeNode": {"required":1},
      "setAttribute": {"required":2,"arguments":["DOMString","DOMString"]},
      "setAttributeNS": {"required":3,"arguments":["DOMString?","DOMString","DOMString"]},
      "setAttributeNode": {"required":1},
      "setAttributeNodeNS": {"required":1},
      "setHTML": {"required":1,"arguments":["DOMString"]},
      "setHTMLUnsafe": {"required":1,"arguments":["DOMString"]},
      "setPointerCapture": {"required":1},
      "toggleAttribute": {"required":1,"arguments":["DOMString"]},
      "webkitMatchesSelector": {"required":1,"arguments":["DOMString"]}
    },
    "attributes": {
      "ariaAtomic": "DOMString?",
      "ariaAutoComplete": "DOMString?",
      "ariaBrailleLabel": "DOMString?",
      "ariaBrailleRoleDescription": "DOMString?",
      "ariaBusy": "DOMString?",
      "ariaChecked": "DOMString?",
      "ariaColCount": "DOMString?",
      "ariaColIndex": "DOMString?",
      "ariaColIndexText": "DOMString?",
      "ariaColSpan": "DOMString?",
      "ariaCurrent": "DOMString?",
      "ariaDescription": "DOMString?",
      "ariaDisabled": "DOMString?",
      "ariaExpanded": "DOMString?",
      "ariaHasPopup": "DOMString?",
      "ariaHidden": "DOMString?",
      "ariaInvalid": "DOMString?",
      "ariaKeyShortcuts": "DOMString?",
      "ariaLabel": "DOMString?",
      "ariaLevel": "DOMString?",
      "ariaLive": "DOMString?",
      "ariaModal": "DOMString?",
      "ariaMultiLine": "DOMString?",
      "ariaMultiSelectable": "DOMString?",
      "ariaOrientation": "DOMString?",
      "ariaPlaceholder": "DOMString?",
      "ariaPosInSet": "DOMString?",
      "ariaPressed": "DOMString?",
      "ariaReadOnly": "DOMString?",
      "ariaRelevant": "DOMString?",
      "ariaRequired": "DOMString?",
      "ariaRoleDescription": "DOMString?",
      "ariaRowCount": "DOMString?",
      "ariaRowIndex": "DOMString?",
      "ariaRowIndexText": "DOMString?",
      "ariaRowSpan": "DOMString?",
      "ariaSelected": "DOMString?",
      "ariaSetSize": "DOMString?",
      "ariaSort": "DOMString?",
      "ariaValueMax": "DOMString?",
      "ariaValueMin": "DOMString?",
      "ariaValueNow": "DOMString?",
      "ariaValueText": "DOMString?",
      "className": "DOMString",
      "id": "DOMString",
      "innerHTML": "[LegacyNullToEmptyString] DOMString",
      "outerHTML": "[LegacyNullToEmptyString] DOMString",
      "role": "DOMString?",
      "slot": "DOMString"
    }
  },
  "ElementInternals": {
    "operations": {
      "setFormValue": {"required":1},
      "setValidity": {"required":0,"arguments":[null,"optional DOMString"]}
    },
    "attributes": {
      "ariaAtomic": "DOMString?",
      "ariaAutoComplete": "DOMString?",
      "ariaBrailleLabel": "DOMString?",
      "ariaBrailleRoleDescription": "DOMString?",
      "ariaBusy": "DOMString?",
      "ariaChecked": "DOMString?",
      "ariaColCount": "DOMString?",
      "ariaColIndex": "DOMString?",
      "ariaColIndexText": "DOMString?",
      "ariaColSpan": "DOMString?",
      "ariaCurrent": "DOMString?",
      "ariaDescription": "DOMString?",
      "ariaDisabled": "DOMString?",
      "ariaExpanded": "DOMString?",
      "ariaHasPopup": "DOMString?",
      "ariaHidden": "DOMString?",
      "ariaInvalid": "DOMString?",
      "ariaKeyShortcuts": "DOMString?",
      "ariaLabel": "DOMString?",
      "ariaLevel": "DOMString?",
      "ariaLive": "DOMString?",
      "ariaModal": "DOMString?",
      "ariaMultiLine": "DOMString?",
      "ariaMultiSelectable": "DOMString?",
      "ariaOrientation": "DOMString?",
      "ariaPlaceholder": "DOMString?",
      "ariaPosInSet": "DOMString?",
      "ariaPressed": "DOMString?",
      "ariaReadOnly": "DOMString?",
      "ariaRelevant": "DOMString?",
      "ariaRequired": "DOMString?",
      "ariaRoleDescription": "DOMString?",
      "ariaRowCount": "DOMString?",
      "ariaRowIndex": "DOMString?",
      "ariaRowIndexText": "DOMString?",
      "ariaRowSpan": "DOMString?",
      "ariaSelected": "DOMString?",
      "ariaSetSize": "DOMString?",
      "ariaSort": "DOMString?",
      "ariaValueMax": "DOMString?",
      "ariaValueMin": "DOMString?",
      "ariaValueNow": "DOMString?",
      "ariaValueText": "DOMString?",
      "role": "DOMString?"
    }
  },
  "ErrorEvent": {
    "constructor": {"required":1,"arguments":["DOMString"]},
    "inherits": "Event"
  },
  "Event": {
    "constructor": {"required":1,"arguments":["DOMString"]},
    "operations": {
      "initEvent": {"required":1,"arguments":["DOMString"]}
    }
  },
  "EventListener": {
    "operations": {
      "handleEvent": {"required":1}
    }
  },
  "EventSource": {
    "constructor": {"required":1,"arguments":["USVString"]},
    "inherits": "EventTarget"
  },
  "EventTarget": {
    "operations": {
      "addEventListener": {"required":2,"arguments":["DOMString"]},
      "dispatchEvent": {"required":1},
      "removeEventListener": {"required":2,"arguments":["DOMString"]}
    }
  },
  "File": {
    "constructor": {"required":2,"arguments":[null,"USVString"]},
    "inherits": "Blob"
  },
  "FileList": {
    "operations": {
      "item": {"required":1}
    }
  },
  "FileReader": {
    "inherits": "EventTarget",
    "operations": {
      "readAsArrayBuffer": {"required":1},
      "readAsBinaryString": {"required":1},
      "readAsDataURL": {"required":1},
      "readAsText": {"required":1,"arguments":[null,"optional DOMString"]}
    }
  },
  "FileReaderSync": {
    "operations": {
      "readAsArrayBuffer": {"required":1},
      "readAsBinaryString": {"required":1},
      "readAsDataURL": {"required":1},
      "readAsText": {"required":1,"arguments":[null,"optional DOMString"]}
    }
  },
  "FocusEvent": {
    "constructor": {"required":1,"arguments":["DOMString"]},
    "inherits": "UIEvent"
  },
  "FormData": {
    "operations": {
      "append": {"required":2,"arguments":["USVString",null,"optional USVString"]},
      "delete": {"required":1,"arguments":["USVString"]},
      "get": {"required":1,"arguments":["USVString"]},
      "getAll": {"required":1,"arguments":["USVString"]},
      "has": {"required":1,"arguments":["USVString"]},
      "set": {"required":2,"arguments":["USVString",null,"optional USVString"]}
    }
  },
  "FormDataEvent": {
    "constructor": {"required":2,"arguments":["DOMString"]},
    "inherits": "Event"
  },
  "HTMLAllCollection": {
    "operations": {
      "item": {"required":0,"arguments":["optional DOMString"]},
      "namedItem": {"required":1,"arguments":["DOMString"]}
    }
  },
  "HTMLAnchorElement": {
    "inherits": "HTMLElement",
    "attributes": {
      "charset": "DOMString",
      "coords": "DOMString",
      "download": "DOMString",
      "hash": "USVString",
      "host": "USVString",
      "hostname": "USVString",
      "href": "USVString",
      "hreflang": "DOMString",
      "name": "DOMString",
      "password": "USVString",
      "pathname": "USVString",
      "ping": "USVString",
      "port": "USVString",
      "protocol": "USVString",
      "referrerPolicy": "DOMString",
      "rel": "DOMString",
      "rev": "DOMString",
      "search": "USVString",
      "shape": "DOMString",
      "target": "DOMString",
      "text": "DOMString",
      "type": "DOMString",
      "username": "USVString"
    }
  },
  "HTMLAreaElement": {
    "inherits": "HTMLElement",
    "attributes": {
      "alt": "DOMString",
      "coords": "DOMString",
      "download": "DOMString",
      "hash": "USVString",
      "host": "USVString",
      "hostname": "USVString",
      "href": "USVString",
      "hreflang": "DOMString",
      "password": "USVString",
      "pathname": "USVString",
      "ping": "USVString",
      "port": "USVString",
      "protocol": "USVString",
      "referrerPolicy": "DOMString",
      "rel": "DOMString",
      "search": "USVString",
      "shape": "DOMString",
      "target": "DOMString",
      "type": "DOMString",
      "username": "USVString"
    }
  },
  "HTMLAudioElement": {
    "inherits": "HTMLMediaElement"
  },
  "HTMLBRElement": {
    "inherits": "HTMLElement",
    "attributes": {
      "clear": "DOMString"
    }
  },
  "HTMLBaseElement": {
    "inherits": "HTMLElement",
    "attributes": {
      "href": "USVString",
      "target": "DOMString"
    }
  },
  "HTMLBodyElement": {
    "inherits": "HTMLElement",
    "attributes": {
      "aLink": "[LegacyNullToEmptyString] DOMString",
      "background": "DOMString",
      "bgColor": "[LegacyNullToEmptyString] DOMString",
      "link": "[LegacyNullToEmptyString] DOMString",
      "text": "[LegacyNullToEmptyString] DOMString",
      "vLink": "[LegacyNullToEmptyString] DOMString"
    }
  },
  "HTMLButtonElement": {
    "inherits": "HTMLElement",
    "operations": {
      "setCustomValidity": {"required":1,"arguments":["DOMString"]}
    },
    "attributes": {
      "command": "DOMString",
      "formAction": "USVString",
      "formEnctype": "DOMString",
      "formMethod": "DOMString",
      "formTarget": "DOMString",
      "name": "DOMString",
      "popoverTargetAction": "DOMString",
      "type": "DOMString",
      "value": "DOMString"
    }
  },
  "HTMLCanvasElement": {
    "inherits": "HTMLElement",
    "operations": {
      "getContext": {"required":1,"arguments":["DOMString"]},
      "toBlob": {"required":1,"arguments":[null,"optional DOMString"]},
      "toDataURL": {"required":0,"arguments":["optional DOMString"]}
    }
  },
  "HTMLCollection": {
    "operations": {
      "item": {"required":1},
      "namedItem": {"required":1,"arguments":["DOMString"]}
    }
  },
  "HTMLDListElement": {
    "inherits": "HTMLElement"
  },
  "HTMLDataElement": {
    "inherits": "HTMLElement",
    "attributes": {
      "value": "DOMString"
    }
  },
  "HTMLDataListElement": {
    "inherits": "HTMLElement"
  },
  "HTMLDetailsElement": {
    "inherits": "HTMLElement",
    "attributes": {
      "name": "DOMString"
    }
  },
  "HTMLDialogElement": {
    "inherits": "HTMLElement",
    "operations": {
      "close": {"required":0,"arguments":["optional DOMString"]},
      "requestClose": {"required":0,"arguments":["optional DOMString"]}
    },
    "attributes": {
      "closedBy": "DOMString",
      "returnValue": "DOMString"
    }
  },
  "HTMLDirectoryElement": {
    "inherits": "HTMLElement"
  },
  "HTMLDivElement": {
    "inherits": "HTMLElement",
    "attributes": {
      "align": "DOMString"
    }
  },
  "HTMLElement": {
    "inherits": "Element",
    "attributes": {
      "accessKey": "DOMString",
      "autocapitalize": "DOMString",
      "contentEditable": "DOMString",
      "dir": "DOMString",
      "enterKeyHint": "DOMString",
      "innerText": "[LegacyNullToEmptyString] DOMString",
      "inputMode": "DOMString",
      "lang": "DOMString",
      "nonce": "DOMString",
      "outerText": "[LegacyNullToEmptyString] DOMString",
      "popover": "DOMString?",
      "title": "DOMString",
      "writingSuggestions": "DOMString"
    }
  },
  "HTMLEmbedElement": {
    "inherits": "HTMLElement",
    "attributes": {
      "align": "DOMString",
      "height": "DOMString",
      "name": "DOMString",
      "src": "USVString",
      "type": "DOMString",
      "width": "DOMString"
    }
  },
  "HTMLFieldSetElement": {
    "inherits": "HTMLElement",
    "operations": {
      "setCustomValidity": {"required":1,"arguments":["DOMString"]}
    },
    "attributes": {
      "name": "DOMString"
    }
  },
  "HTMLFontElement": {
    "inherits": "HTMLElement",
    "attributes": {
      "color": "[LegacyNullToEmptyString] DOMString",
      "face": "DOMString",
      "size": "DOMString"
    }
  },
  "HTMLFormControlsCollection": {
    "inherits": "HTMLCollection",
    "operations": {
      "namedItem": {"required":1,"arguments":["DOMString"]}
    }
  },
  "HTMLFormElement": {
    "inherits": "HTMLElement",
    "attributes": {
      "acceptCharset": "DOMString",
      "action": "USVString",
      "autocomplete": "DOMString",
      "encoding": "DOMString",
      "enctype": "DOMString",
      "method": "DOMString",
      "name": "DOMString",
      "rel": "DOMString",
      "target": "DOMString"
    }
  },
  "HTMLFrameElement": {
    "inherits": "HTMLElement",
    "attributes": {
      "frameBorder": "DOMString",
      "longDesc": "USVString",
      "marginHeight": "[LegacyNullToEmptyString] DOMString",
      "marginWidth": "[LegacyNullToEmptyString] DOMString",
      "name": "DOMString",
      "scrolling": "DOMString",
      "src": "USVString"
    }
  },
  "HTMLFrameSetElement": {
    "inherits": "HTMLElement",
    "attributes": {
      "cols": "DOMString",
      "rows": "DOMString"
    }
  },
  "HTMLHRElement": {
    "inherits": "HTMLElement",
    "attributes": {
      "align": "DOMString",
      "color": "DOMString",
      "size": "DOMString",
      "width": "DOMString"
    }
  },
  "HTMLHeadElement": {
    "inherits": "HTMLElement"
  },
  "HTMLHeadingElement": {
    "inherits": "HTMLElement",
    "attributes": {
      "align": "DOMString"
    }
  },
  "HTMLHtmlElement": {
    "inherits": "HTMLElement",
    "attributes": {
      "version": "DOMString"
    }
  },
  "HTMLIFrameElement": {
    "inherits": "HTMLElement",
    "attributes": {
      "align": "DOMString",
      "allow": "DOMString",
      "frameBorder": "DOMString",
      "height": "DOMString",
      "loading": "DOMString",
      "longDesc": "USVString",
      "marginHeight": "[LegacyNullToEmptyString] DOMString",
      "marginWidth": "[LegacyNullToEmptyString] DOMString",
      "name": "DOMString",
      "referrerPolicy": "DOMString",
      "scrolling": "DOMString",
      "src": "USVString",
      "srcdoc": "DOMString",
      "width": "DOMString"
    }
  },
  "HTMLImageElement": {
    "inherits": "HTMLElement",
    "attributes": {
      "align": "DOMString",
      "alt": "DOMString",
      "border": "[LegacyNullToEmptyString] DOMString",
      "crossOrigin": "DOMString?",
      "decoding": "DOMString",
      "fetchPriority": "DOMString",
      "loading": "DOMString",
      "longDesc": "USVString",
      "lowsrc": "USVString",
      "name": "DOMString",
      "referrerPolicy": "DOMString",
      "sizes": "DOMString",
      "src": "USVString",
      "srcset": "USVString",
      "useMap": "DOMString"
    }
  },
  "HTMLInputElement": {
    "inherits": "HTMLElement",
    "operations": {
      "setCustomValidity": {"required":1,"arguments":["DOMString"]},
      "setRangeText": {"required":1,"arguments":["DOMString"]},
      "setSelectionRange": {"required":2,"arguments":[null,null,"optional DOMString"]}
    },
    "attributes": {
      "accept": "DOMString",
      "align": "DOMString",
      "alt": "DOMString",
      "autocomplete": "DOMString",
      "colorSpace": "DOMString",
      "defaultValue": "DOMString",
      "dirName": "DOMString",
      "formAction": "USVString",
      "formEnctype": "DOMString",
      "formMethod": "DOMString",
      "formTarget": "DOMString",
      "max": "DOMString",
      "min": "DOMString",
      "name": "DOMString",
      "pattern": "DOMString",
      "placeholder": "DOMString",
      "popoverTargetAction": "DOMString",
      "selectionDirection": "DOMString?",
      "src": "USVString",
      "step": "DOMString",
      "type": "DOMString",
      "useMap": "DOMString",
      "value": "[LegacyNullToEmptyString] DOMString"
    }
  },
  "HTMLLIElement": {
    "inherits": "HTMLElement",
    "attributes": {
      "type": "DOMString"
    }
  },
  "HTMLLabelElement": {
    "inherits": "HTMLElement",
    "attributes": {
      "htmlFor": "DOMString"
    }
  },
  "HTMLLegendElement": {
    "inherits": "HTMLElement",
    "attributes": {
      "align": "DOMString"
    }
  },
  "HTMLLinkElement": {
    "inherits": "HTMLElement",
    "attributes": {
      "as": "DOMString",
      "charset": "DOMString",
      "crossOrigin": "DOMString?",
      "fetchPriority": "DOMString",
      "href": "USVString",
      "hreflang": "DOMString",
      "imageSizes": "DOMString",
      "imageSrcset": "USVString",
      "integrity": "DOMString",
      "media": "DOMString",
      "referrerPolicy": "DOMString",
      "rel": "DOMString",
      "rev": "DOMString",
      "target": "DOMString",
      "type": "DOMString"
    }
  },
  "HTMLMapElement": {
    "inherits": "HTMLElement",
    "attributes": {
      "name": "DOMString"
    }
  },
  "HTMLMarqueeElement": {
    "inherits": "HTMLElement",
    "attributes": {
      "behavior": "DOMString",
      "bgColor": "DOMString",
      "direction": "DOMString",
      "height": "DOMString",
      "width": "DOMString"
    }
  },
  "HTMLMediaElement": {
    "inherits": "HTMLElement",
    "operations": {
      "addTextTrack": {"required":1,"arguments":[null,"optional DOMString","optional DOMString"]},
      "canPlayType": {"required":1,"arguments":["DOMString"]},
      "fastSeek": {"required":1}
    },
    "attributes": {
      "crossOrigin": "DOMString?",
      "loading": "DOMString",
      "preload": "DOMString",
      "src": "USVString"
    }
  },
  "HTMLMenuElement": {
    "inherits": "HTMLElement"
  },
  "HTMLMetaElement": {
    "inherits": "HTMLElement",
    "attributes": {
      "content": "DOMString",
      "httpEquiv": "DOMString",
      "media": "DOMString",
      "name": "DOMString",
      "scheme": "DOMString"
    }
  },
  "HTMLMeterElement": {
    "inherits": "HTMLElement"
  },
  "HTMLModElement": {
    "inherits": "HTMLElement",
    "attributes": {
      "cite": "USVString",
      "dateTime": "DOMString"
    }
  },
  "HTMLOListElement": {
    "inherits": "HTMLElement",
    "attributes": {
      "type": "DOMString"
    }
  },
  "HTMLObjectElement": {
    "inherits": "HTMLElement",
    "operations": {
      "setCustomValidity": {"required":1,"arguments":["DOMString"]}
    },
    "attributes": {
      "align": "DOMString",
      "archive": "DOMString",
      "border": "[LegacyNullToEmptyString] DOMString",
      "code": "DOMString",
      "codeBase": "DOMString",
      "codeType": "DOMString",
      "data": "USVString",
      "height": "DOMString",
      "name": "DOMString",
      "standby": "DOMString",
      "type": "DOMString",
      "useMap": "DOMString",
      "width": "DOMString"
    }
  },
  "HTMLOptGroupElement": {
    "inherits": "HTMLElement",
    "attributes": {
      "label": "DOMString"
    }
  },
  "HTMLOptionElement": {
    "inherits": "HTMLElement",
    "attributes": {
      "label": "DOMString",
      "text": "DOMString",
      "value": "DOMString"
    }
  },
  "HTMLOptionsCollection": {
    "inherits": "HTMLCollection",
    "operations": {
      "add": {"required":1},
      "remove": {"required":1}
    }
  },
  "HTMLOutputElement": {
    "inherits": "HTMLElement",
    "operations": {
      "setCustomValidity": {"required":1,"arguments":["DOMString"]}
    },
    "attributes": {
      "defaultValue": "DOMString",
      "name": "DOMString",
      "value": "DOMString"
    }
  },
  "HTMLParagraphElement": {
    "inherits": "HTMLElement",
    "attributes": {
      "align": "DOMString"
    }
  },
  "HTMLParamElement": {
    "inherits": "HTMLElement",
    "attributes": {
      "name": "DOMString",
      "type": "DOMString",
      "value": "DOMString",
      "valueType": "DOMString"
    }
  },
  "HTMLPictureElement": {
    "inherits": "HTMLElement"
  },
  "HTMLPreElement": {
    "inherits": "HTMLElement"
  },
  "HTMLProgressElement": {
    "inherits": "HTMLElement"
  },
  "HTMLQuoteElement": {
    "inherits": "HTMLElement",
    "attributes": {
      "cite": "USVString"
    }
  },
  "HTMLScriptElement": {
    "inherits": "HTMLElement",
    "static_operations": {
      "supports": {"required":1,"arguments":["DOMString"]}
    },
    "attributes": {
      "charset": "DOMString",
      "crossOrigin": "DOMString?",
      "event": "DOMString",
      "fetchPriority": "DOMString",
      "htmlFor": "DOMString",
      "integrity": "DOMString",
      "referrerPolicy": "DOMString",
      "src": "USVString",
      "text": "DOMString",
      "type": "DOMString"
    }
  },
  "HTMLSelectElement": {
    "inherits": "HTMLElement",
    "operations": {
      "add": {"required":1},
      "item": {"required":1},
      "namedItem": {"required":1,"arguments":["DOMString"]},
      "setCustomValidity": {"required":1,"arguments":["DOMString"]}
    },
    "attributes": {
      "autocomplete": "DOMString",
      "name": "DOMString",
      "value": "DOMString"
    }
  },
  "HTMLSelectedContentElement": {
    "inherits": "HTMLElement"
  },
  "HTMLSlotElement": {
    "inherits": "HTMLElement",
    "attributes": {
      "name": "DOMString"
    }
  },
  "HTMLSourceElement": {
    "inherits": "HTMLElement",
    "attributes": {
      "media": "DOMString",
      "sizes": "DOMString",
      "src": "USVString",
      "srcset": "USVString",
      "type": "DOMString"
    }
  },
  "HTMLSpanElement": {
    "inherits": "HTMLElement"
  },
  "HTMLStyleElement": {
    "inherits": "HTMLElement",
    "attributes": {
      "media": "DOMString",
      "type": "DOMString"
    }
  },
  "HTMLTableCaptionElement": {
    "inherits": "HTMLElement",
    "attributes": {
      "align": "DOMString"
    }
  },
  "HTMLTableCellElement": {
    "inherits": "HTMLElement",
    "attributes": {
      "abbr": "DOMString",
      "align": "DOMString",
      "axis": "DOMString",
      "bgColor": "[LegacyNullToEmptyString] DOMString",
      "ch": "DOMString",
      "chOff": "DOMString",
      "headers": "DOMString",
      "height": "DOMString",
      "scope": "DOMString",
      "vAlign": "DOMString",
      "width": "DOMString"
    }
  },
  "HTMLTableColElement": {
    "inherits": "HTMLElement",
    "attributes": {
      "align": "DOMString",
      "ch": "DOMString",
      "chOff": "DOMString",
      "vAlign": "DOMString",
      "width": "DOMString"
    }
  },
  "HTMLTableElement": {
    "inherits": "HTMLElement",
    "operations": {
      "deleteRow": {"required":1}
    },
    "attributes": {
      "align": "DOMString",
      "bgColor": "[LegacyNullToEmptyString] DOMString",
      "border": "DOMString",
      "cellPadding": "[LegacyNullToEmptyString] DOMString",
      "cellSpacing": "[LegacyNullToEmptyString] DOMString",
      "frame": "DOMString",
      "rules": "DOMString",
      "summary": "DOMString",
      "width": "DOMString"
    }
  },
  "HTMLTableRowElement": {
    "inherits": "HTMLElement",
    "operations": {
      "deleteCell": {"required":1}
    },
    "attributes": {
      "align": "DOMString",
      "bgColor": "[LegacyNullToEmptyString] DOMString",
      "ch": "DOMString",
      "chOff": "DOMString",
      "vAlign": "DOMString"
    }
  },
  "HTMLTableSectionElement": {
    "inherits": "HTMLElement",
    "operations": {
      "deleteRow": {"required":1}
    },
    "attributes": {
      "align": "DOMString",
      "ch": "DOMString",
      "chOff": "DOMString",
      "vAlign": "DOMString"
    }
  },
  "HTMLTemplateElement": {
    "inherits": "HTMLElement",
    "attributes": {
      "htmlFor": "DOMString",
      "shadowRootCustomElementRegistry": "DOMString",
      "shadowRootMode": "DOMString",
      "shadowRootSlotAssignment": "DOMString"
    }
  },
  "HTMLTextAreaElement": {
    "inherits": "HTMLElement",
    "operations": {
      "setCustomValidity": {"required":1,"arguments":["DOMString"]},
      "setRangeText": {"required":1,"arguments":["DOMString"]},
      "setSelectionRange": {"required":2,"arguments":[null,null,"optional DOMString"]}
    },
    "attributes": {
      "autocomplete": "DOMString",
      "defaultValue": "DOMString",
      "dirName": "DOMString",
      "name": "DOMString",
      "placeholder": "DOMString",
      "selectionDirection": "DOMString",
      "value": "[LegacyNullToEmptyString] DOMString",
      "wrap": "DOMString"
    }
  },
  "HTMLTimeElement": {
    "inherits": "HTMLElement",
    "attributes": {
      "dateTime": "DOMString"
    }
  },
  "HTMLTitleElement": {
    "inherits": "HTMLElement",
    "attributes": {
      "text": "DOMString"
    }
  },
  "HTMLTrackElement": {
    "inherits": "HTMLElement",
    "attributes": {
      "kind": "DOMString",
      "label": "DOMString",
      "src": "USVString",
      "srclang": "DOMString"
    }
  },
  "HTMLUListElement": {
    "inherits": "HTMLElement",
    "attributes": {
      "type": "DOMString"
    }
  },
  "HTMLUnknownElement": {
    "inherits": "HTMLElement"
  },
  "HTMLVideoElement": {
    "inherits": "HTMLMediaElement",
    "attributes": {
      "poster": "USVString"
    }
  },
  "HashChangeEvent": {
    "constructor": {"required":1,"arguments":["DOMString"]},
    "inherits": "Event"
  },
  "Headers": {
    "operations": {
      "append": {"required":2,"arguments":["ByteString","ByteString"]},
      "delete": {"required":1,"arguments":["ByteString"]},
      "get": {"required":1,"arguments":["ByteString"]},
      "has": {"required":1,"arguments":["ByteString"]},
      "set": {"required":2,"arguments":["ByteString","ByteString"]}
    }
  },
  "History": {
    "operations": {
      "pushState": {"required":2,"arguments":[null,"DOMString","optional USVString?"]},
      "replaceState": {"required":2,"arguments":[null,"DOMString","optional USVString?"]}
    }
  },
  "ImageBitmapRenderingContext": {
    "operations": {
      "transferFromImageBitmap": {"required":1}
    }
  },
  "ImageData": {
    "constructor": {"required":2}
  },
  "InputEvent": {
    "constructor": {"required":1,"arguments":["DOMString"]},
    "inherits": "UIEvent"
  },
  "KeyboardEvent": {
    "constructor": {"required":1,"arguments":["DOMString"]},
    "inherits": "UIEvent",
    "operations": {
      "getModifierState": {"required":1,"arguments":["DOMString"]},
      "initKeyboardEvent": {"required":1,"arguments":["DOMString",null,null,null,"optional DOMString"]}
    }
  },
  "Location": {
    "operations": {
      "assign": {"required":1,"arguments":["USVString"]},
      "replace": {"required":1,"arguments":["USVString"]}
    },
    "attributes": {
      "hash": "USVString",
      "host": "USVString",
      "hostname": "USVString",
      "href": "USVString",
      "pathname": "USVString",
      "port": "USVString",
      "protocol": "USVString",
      "search": "USVString"
    }
  },
  "MediaList": {
    "operations": {
      "appendMedium": {"required":1,"arguments":["DOMString"]},
      "deleteMedium": {"required":1,"arguments":["DOMString"]},
      "item": {"required":1}
    },
    "attributes": {
      "mediaText": "[LegacyNullToEmptyString] DOMString"
    }
  },
  "MediaQueryList": {
    "inherits": "EventTarget",
    "operations": {
      "addListener": {"required":1},
      "removeListener": {"required":1}
    }
  },
  "MediaQueryListEvent": {
    "constructor": {"required":1,"arguments":["DOMString"]},
    "inherits": "Event"
  },
  "MessageEvent": {
    "constructor": {"required":1,"arguments":["DOMString"]},
    "inherits": "Event",
    "operations": {
      "initMessageEvent": {"required":1,"arguments":["DOMString",null,null,null,"optional USVString","optional DOMString"]}
    }
  },
  "MessagePort": {
    "inherits": "EventTarget",
    "operations": {
      "postMessage": {"required":1}
    }
  },
  "MimeTypeArray": {
    "operations": {
      "item": {"required":1},
      "namedItem": {"required":1,"arguments":["DOMString"]}
    }
  },
  "MouseEvent": {
    "constructor": {"required":1,"arguments":["DOMString"]},
    "inherits": "UIEvent",
    "operations": {
      "getModifierState": {"required":1,"arguments":["DOMString"]},
      "initMouseEvent": {"required":1,"arguments":["DOMString"]}
    }
  },
  "MutationObserver": {
    "constructor": {"required":1},
    "operations": {
      "observe": {"required":1}
    }
  },
  "NamedNodeMap": {
    "operations": {
      "getNamedItem": {"required":1,"arguments":["DOMString"]},
      "getNamedItemNS": {"required":2,"arguments":["DOMString?","DOMString"]},
      "item": {"required":1},
      "removeNamedItem": {"required":1,"arguments":["DOMString"]},
      "removeNamedItemNS": {"required":2,"arguments":["DOMString?","DOMString"]},
      "setNamedItem": {"required":1},
      "setNamedItemNS": {"required":1}
    }
  },
  "NavigateEvent": {
    "constructor": {"required":2,"arguments":["DOMString"]},
    "inherits": "Event"
  },
  "Navigation": {
    "inherits": "EventTarget",
    "operations": {
      "navigate": {"required":1,"arguments":["USVString"]},
      "traverseTo": {"required":1,"arguments":["DOMString"]},
      "updateCurrentEntry": {"required":1}
    }
  },
  "NavigationCurrentEntryChangeEvent": {
    "constructor": {"required":2,"arguments":["DOMString"]},
    "inherits": "Event"
  },
  "NavigationHistoryEntry": {
    "inherits": "EventTarget"
  },
  "NavigationPrecommitController": {
    "operations": {
      "addHandler": {"required":1},
      "redirect": {"required":1,"arguments":["USVString"]}
    }
  },
  "Navigator": {
    "operations": {
      "registerProtocolHandler": {"required":2,"arguments":["DOMString","USVString"]},
      "unregisterProtocolHandler": {"required":2,"arguments":["DOMString","USVString"]}
    }
  },
  "Node": {
    "inherits": "EventTarget",
    "operations": {
      "appendChild": {"required":1},
      "compareDocumentPosition": {"required":1},
      "contains": {"required":1},
      "insertBefore": {"required":2},
      "isDefaultNamespace": {"required":1,"arguments":["DOMString?"]},
      "isEqualNode": {"required":1},
      "isSameNode": {"required":1},
      "lookupNamespaceURI": {"required":1,"arguments":["DOMString?"]},
      "lookupPrefix": {"required":1,"arguments":["DOMString?"]},
      "removeChild": {"required":1},
      "replaceChild": {"required":2}
    },
    "attributes": {
      "nodeValue": "DOMString?",
      "textContent": "DOMString?"
    }
  },
  "NodeFilter": {
    "operations": {
      "acceptNode": {"required":1}
    }
  },
  "NodeList": {
    "operations": {
      "item": {"required":1}
    }
  },
  "Notification": {
    "constructor": {"required":1,"arguments":["DOMString"]},
    "inherits": "EventTarget"
  },
  "NotificationEvent": {
    "constructor": {"required":2,"arguments":["DOMString"]},
    "inherits": "ExtendableEvent"
  },
  "OffscreenCanvas": {
    "constructor": {"required":2},
    "inherits": "EventTarget",
    "operations": {
      "getContext": {"required":1}
    }
  },
  "OffscreenCanvasRenderingContext2D": {
    "operations": {
      "arc": {"required":5},
      "arcTo": {"required":5},
      "bezierCurveTo": {"required":6},
      "clearRect": {"required":4},
      "createConicGradient": {"required":3},
      "createImageData": {"required":1},
      "createLinearGradient": {"required":4},
      "createPattern": {"required":2,"arguments":[null,"[LegacyNullToEmptyString] DOMString"]},
      "createRadialGradient": {"required":6},
      "drawImage": {"required":3},
      "ellipse": {"required":7},
      "fillRect": {"required":4},
      "fillText": {"required":3,"arguments":["DOMString"]},
      "getImageData": {"required":4},
      "isPointInPath": {"required":2},
      "isPointInStroke": {"required":2},
      "lineTo": {"required":2},
      "measureText": {"required":1,"arguments":["DOMString"]},
      "moveTo": {"required":2},
      "putImageData": {"required":3},
      "quadraticCurveTo": {"required":4},
      "rect": {"required":4},
      "rotate": {"required":1},
      "roundRect": {"required":4},
      "scale": {"required":2},
      "setLineDash": {"required":1},
      "strokeRect": {"required":4},
      "strokeText": {"required":3,"arguments":["DOMString"]},
      "transform": {"required":6},
      "translate": {"required":2}
    },
    "attributes": {
      "filter": "DOMString",
      "font": "DOMString",
      "globalCompositeOperation": "DOMString",
      "lang": "DOMString",
      "letterSpacing": "DOMString",
      "shadowColor": "DOMString",
      "wordSpacing": "DOMString"
    }
  },
  "Origin": {
    "operations": {
      "isSameOrigin": {"required":1},
      "isSameSite": {"required":1}
    },
    "static_operations": {
      "from": {"required":1}
    }
  },
  "PageRevealEvent": {
    "constructor": {"required":1,"arguments":["DOMString"]},
    "inherits": "Event"
  },
  "PageSwapEvent": {
    "constructor": {"required":1,"arguments":["DOMString"]},
    "inherits": "Event"
  },
  "PageTransitionEvent": {
    "constructor": {"required":1,"arguments":["DOMString"]},
    "inherits": "Event"
  },
  "Path2D": {
    "operations": {
      "addPath": {"required":1},
      "arc": {"required":5},
      "arcTo": {"required":5},
      "bezierCurveTo": {"required":6},
      "ellipse": {"required":7},
      "lineTo": {"required":2},
      "moveTo": {"required":2},
      "quadraticCurveTo": {"required":4},
      "rect": {"required":4},
      "roundRect": {"required":4}
    }
  },
  "Plugin": {
    "operations": {
      "item": {"required":1},
      "namedItem": {"required":1,"arguments":["DOMString"]}
    }
  },
  "PluginArray": {
    "operations": {
      "item": {"required":1},
      "namedItem": {"required":1,"arguments":["DOMString"]}
    }
  },
  "PointerEvent": {
    "constructor": {"required":1,"arguments":["DOMString"]},
    "inherits": "MouseEvent"
  },
  "PopStateEvent": {
    "constructor": {"required":1,"arguments":["DOMString"]},
    "inherits": "Event"
  },
  "ProcessingInstruction": {
    "constructor": {"required":1,"arguments":["DOMString","optional DOMString"]},
    "inherits": "CharacterData",
    "operations": {
      "getAttribute": {"required":1,"arguments":["DOMString"]},
      "hasAttribute": {"required":1,"arguments":["DOMString"]},
      "removeAttribute": {"required":1,"arguments":["DOMString"]},
      "setAttribute": {"required":2,"arguments":["DOMString","DOMString"]},
      "toggleAttribute": {"required":1,"arguments":["DOMString"]}
    }
  },
  "ProgressEvent": {
    "constructor": {"required":1,"arguments":["DOMString"]},
    "inherits": "Event"
  },
  "PromiseRejectionEvent": {
    "constructor": {"required":2,"arguments":["DOMString"]},
    "inherits": "Event"
  },
  "RadioNodeList": {
    "inherits": "NodeList",
    "attributes": {
      "value": "DOMString"
    }
  },
  "Range": {
    "inherits": "AbstractRange",
    "operations": {
      "compareBoundaryPoints": {"required":2},
      "comparePoint": {"required":2},
      "createContextualFragment": {"required":1,"arguments":["DOMString"]},
      "insertNode": {"required":1},
      "intersectsNode": {"required":1},
      "isPointInRange": {"required":2},
      "selectNode": {"required":1},
      "selectNodeContents": {"required":1},
      "setEnd": {"required":2},
      "setEndAfter": {"required":1},
      "setEndBefore": {"required":1},
      "setStart": {"required":2},
      "setStartAfter": {"required":1},
      "setStartBefore": {"required":1},
      "surroundContents": {"required":1}
    }
  },
  "ReadableByteStreamController": {
    "operations": {
      "enqueue": {"required":1}
    }
  },
  "ReadableStream": {
    "operations": {
      "pipeThrough": {"required":1},
      "pipeTo": {"required":1}
    },
    "static_operations": {
      "from": {"required":1}
    }
  },
  "ReadableStreamBYOBReader": {
    "constructor": {"required":1},
    "operations": {
      "read": {"required":1}
    }
  },
  "ReadableStreamBYOBRequest": {
    "operations": {
      "respond": {"required":1},
      "respondWithNewView": {"required":1}
    }
  },
  "ReadableStreamDefaultReader": {
    "constructor": {"required":1}
  },
  "Request": {
    "constructor": {"required":1}
  },
  "Response": {
    "static_operations": {
      "redirect": {"required":1,"arguments":["USVString"]}
    }
  },
  "Sanitizer": {
    "operations": {
      "allowAttribute": {"required":1},
      "allowElement": {"required":1},
      "allowProcessingInstruction": {"required":1},
      "removeAttribute": {"required":1},
      "removeElement": {"required":1},
      "removeProcessingInstruction": {"required":1},
      "replaceElementWithChildren": {"required":1},
      "setComments": {"required":1},
      "setDataAttributes": {"required":1},
      "setJavascriptURLs": {"required":1}
    }
  },
  "Selection": {
    "operations": {
      "addRange": {"required":1},
      "collapse": {"required":1},
      "containsNode": {"required":1},
      "extend": {"required":1},
      "getRangeAt": {"required":1},
      "modify": {"required":0,"arguments":["optional DOMString","optional DOMString","optional DOMString"]},
      "removeRange": {"required":1},
      "selectAllChildren": {"required":1},
      "setBaseAndExtent": {"required":4},
      "setPosition": {"required":1}
    }
  },
  "ShadowRoot": {
    "inherits": "DocumentFragment",
    "operations": {
      "setHTML": {"required":1,"arguments":["DOMString"]},
      "setHTMLUnsafe": {"required":1,"arguments":["DOMString"]}
    },
    "attributes": {
      "innerHTML": "[LegacyNullToEmptyString] DOMString"
    }
  },
  "SharedWorker": {
    "constructor": {"required":1,"arguments":["USVString"]},
    "inherits": "EventTarget"
  },
  "SharedWorkerGlobalScope": {
    "inherits": "WorkerGlobalScope"
  },
  "StaticRange": {
    "constructor": {"required":1},
    "inherits": "AbstractRange"
  },
  "Storage": {
    "operations": {
      "getItem": {"required":1,"arguments":["DOMString"]},
      "key": {"required":1},
      "removeItem": {"required":1,"arguments":["DOMString"]},
      "setItem": {"required":2,"arguments":["DOMString","DOMString"]}
    }
  },
  "StorageEvent": {
    "constructor": {"required":1,"arguments":["DOMString"]},
    "inherits": "Event",
    "operations": {
      "initStorageEvent": {"required":1,"arguments":["DOMString",null,null,"optional DOMString?","optional DOMString?","optional DOMString?","optional USVString"]}
    }
  },
  "StyleSheetList": {
    "operations": {
      "item": {"required":1}
    }
  },
  "SubmitEvent": {
    "constructor": {"required":1,"arguments":["DOMString"]},
    "inherits": "Event"
  },
  "Text": {
    "constructor": {"required":0,"arguments":["optional DOMString"]},
    "inherits": "CharacterData",
    "operations": {
      "convertPointFromNode": {"required":2},
      "convertQuadFromNode": {"required":2},
      "convertRectFromNode": {"required":2},
      "splitText": {"required":1}
    }
  },
  "TextDecoder": {
    "constructor": {"required":0,"arguments":["optional DOMString"]}
  },
  "TextDecoderStream": {
    "constructor": {"required":0,"arguments":["optional DOMString"]}
  },
  "TextEncoder": {
    "operations": {
      "encode": {"required":0,"arguments":["optional USVString"]},
      "encodeInto": {"required":2,"arguments":["USVString"]}
    }
  },
  "TextEvent": {
    "inherits": "UIEvent",
    "operations": {
      "initTextEvent": {"required":1,"arguments":["DOMString",null,null,null,"optional DOMString"]}
    }
  },
  "TextTrack": {
    "inherits": "EventTarget",
    "operations": {
      "addCue": {"required":1},
      "removeCue": {"required":1}
    }
  },
  "TextTrackCue": {
    "inherits": "EventTarget",
    "attributes": {
      "id": "DOMString"
    }
  },
  "TextTrackCueList": {
    "operations": {
      "getCueById": {"required":1,"arguments":["DOMString"]}
    }
  },
  "TextTrackList": {
    "inherits": "EventTarget",
    "operations": {
      "getTrackById": {"required":1,"arguments":["DOMString"]}
    }
  },
  "TimeRanges": {
    "operations": {
      "end": {"required":1},
      "start": {"required":1}
    }
  },
  "ToggleEvent": {
    "constructor": {"required":1,"arguments":["DOMString"]},
    "inherits": "Event"
  },
  "Touch": {
    "constructor": {"required":1}
  },
  "TouchEvent": {
    "constructor": {"required":1,"arguments":["DOMString"]},
    "inherits": "UIEvent",
    "operations": {
      "getModifierState": {"required":1,"arguments":["DOMString"]}
    }
  },
  "TouchList": {
    "operations": {
      "item": {"required":1}
    }
  },
  "TrackEvent": {
    "constructor": {"required":1,"arguments":["DOMString"]},
    "inherits": "Event"
  },
  "TransitionEvent": {
    "constructor": {"required":1,"arguments":["DOMString"]},
    "inherits": "Event"
  },
  "UIEvent": {
    "constructor": {"required":1,"arguments":["DOMString"]},
    "inherits": "Event",
    "operations": {
      "initUIEvent": {"required":1,"arguments":["DOMString"]}
    }
  },
  "URL": {
    "constructor": {"required":1,"arguments":["USVString","optional USVString"]},
    "static_operations": {
      "canParse": {"required":1,"arguments":["USVString","optional USVString"]},
      "createObjectURL": {"required":1},
      "parse": {"required":1,"arguments":["USVString","optional USVString"]},
      "revokeObjectURL": {"required":1,"arguments":["DOMString"]}
    },
    "attributes": {
      "hash": "USVString",
      "host": "USVString",
      "hostname": "USVString",
      "href": "USVString",
      "password": "USVString",
      "pathname": "USVString",
      "port": "USVString",
      "protocol": "USVString",
      "search": "USVString",
      "username": "USVString"
    }
  },
  "URLSearchParams": {
    "operations": {
      "append": {"required":2,"arguments":["USVString","USVString"]},
      "delete": {"required":1,"arguments":["USVString","optional USVString"]},
      "get": {"required":1,"arguments":["USVString"]},
      "getAll": {"required":1,"arguments":["USVString"]},
      "has": {"required":1,"arguments":["USVString","optional USVString"]},
      "set": {"required":2,"arguments":["USVString","USVString"]}
    }
  },
  "VideoTrackList": {
    "inherits": "EventTarget",
    "operations": {
      "getTrackById": {"required":1,"arguments":["DOMString"]}
    }
  },
  "VisibilityStateEntry": {
    "inherits": "PerformanceEntry"
  },
  "VisualViewport": {
    "inherits": "EventTarget"
  },
  "WebSocket": {
    "constructor": {"required":1,"arguments":["USVString"]},
    "inherits": "EventTarget",
    "operations": {
      "close": {"required":0,"arguments":[null,"optional USVString"]},
      "send": {"required":1}
    }
  },
  "WheelEvent": {
    "constructor": {"required":1,"arguments":["DOMString"]},
    "inherits": "MouseEvent"
  },
  "Window": {
    "inherits": "EventTarget",
    "operations": {
      "alert": {"required":0,"arguments":["optional DOMString"]},
      "atob": {"required":1,"arguments":["DOMString"]},
      "btoa": {"required":1,"arguments":["DOMString"]},
      "cancelAnimationFrame": {"required":1},
      "confirm": {"required":0,"arguments":["optional DOMString"]},
      "createImageBitmap": {"required":1},
      "fetch": {"required":1},
      "fetchLater": {"required":1},
      "getComputedStyle": {"required":1,"arguments":[null,"optional DOMString?"]},
      "matchMedia": {"required":1,"arguments":["DOMString"]},
      "moveBy": {"required":2},
      "moveTo": {"required":2},
      "open": {"required":0,"arguments":["optional USVString","optional DOMString","optional [LegacyNullToEmptyString] DOMString"]},
      "postMessage": {"required":1},
      "prompt": {"required":0,"arguments":["optional DOMString","optional DOMString"]},
      "queueMicrotask": {"required":1},
      "reportError": {"required":1},
      "requestAnimationFrame": {"required":1},
      "resizeBy": {"required":2},
      "resizeTo": {"required":2},
      "setInterval": {"required":1},
      "setTimeout": {"required":1},
      "structuredClone": {"required":1}
    },
    "attributes": {
      "name": "DOMString",
      "status": "DOMString"
    }
  },
  "Worker": {
    "constructor": {"required":1,"arguments":["USVString"]},
    "inherits": "EventTarget",
    "operations": {
      "postMessage": {"required":1}
    }
  },
  "WorkerGlobalScope": {
    "inherits": "EventTarget",
    "operations": {
      "atob": {"required":1,"arguments":["DOMString"]},
      "btoa": {"required":1,"arguments":["DOMString"]},
      "createImageBitmap": {"required":1},
      "fetch": {"required":1},
      "importScripts": {"required":0,"arguments":["USVString..."]},
      "queueMicrotask": {"required":1},
      "reportError": {"required":1},
      "setInterval": {"required":1},
      "setTimeout": {"required":1},
      "structuredClone": {"required":1}
    }
  },
  "Worklet": {
    "operations": {
      "addModule": {"required":1,"arguments":["USVString"]}
    }
  },
  "WritableStreamDefaultWriter": {
    "constructor": {"required":1}
  },
  "XMLDocument": {
    "inherits": "Document"
  },
  "XMLHttpRequest": {
    "inherits": "XMLHttpRequestEventTarget",
    "operations": {
      "getResponseHeader": {"required":1,"arguments":["ByteString"]},
      "open": {"required":2,"arguments":["ByteString","USVString",null,"optional USVString?","optional USVString?"]},
      "overrideMimeType": {"required":1,"arguments":["DOMString"]},
      "setRequestHeader": {"required":2,"arguments":["ByteString","ByteString"]}
    }
  },
  "XMLHttpRequestEventTarget": {
    "inherits": "EventTarget"
  },
  "XMLHttpRequestUpload": {
    "inherits": "XMLHttpRequestEventTarget"
  },
  "XMLSerializer": {
    "operations": {
      "serializeToString": {"required":1}
    }
  },
  "XPathEvaluator": {
    "operations": {
      "createExpression": {"required":1,"arguments":["DOMString"]},
      "createNSResolver": {"required":1},
      "evaluate": {"required":2,"arguments":["DOMString"]}
    }
  },
  "XPathExpression": {
    "operations": {
      "evaluate": {"required":1}
    }
  },
  "XPathNSResolver": {
    "operations": {
      "lookupNamespaceURI": {"required":1,"arguments":["DOMString?"]}
    }
  },
  "XPathResult": {
    "operations": {
      "snapshotItem": {"required":1}
    }
  },
  "XSLTProcessor": {
    "operations": {
      "getParameter": {"required":2,"arguments":["[LegacyNullToEmptyString] DOMString","DOMString"]},
      "importStylesheet": {"required":1},
      "removeParameter": {"required":2,"arguments":["[LegacyNullToEmptyString] DOMString","DOMString"]},
      "setParameter": {"required":3,"arguments":["[LegacyNullToEmptyString] DOMString","DOMString"]},
      "transformToDocument": {"required":1},
      "transformToFragment": {"required":2}
    }
  }
};
