// GENERATED by script/build_webidl_signatures.rb from
// test/fixtures/webidl/interfaces.json (web-platform-tests 863077959ca8c1a7ceecfbe2534b75d2527b9013).
// Do not edit by hand: re-run the script (`rake webidl:signatures`).
//
// For each interface, the string conversions WebIDL makes of a script's
// values: per operation, static operation and constructor, one entry per
// argument position; per writable attribute, the value's. An entry is a
// string type ("DOMString", "USVString", "ByteString"), "?" after it when
// nullable, "[LegacyNullToEmptyString] " before it when null means "",
// "optional " before it when undefined is left for the default, and
// "..." after it when it converts every remaining argument. null is a
// position that is not a string type, or a member that is not one where
// an ancestor's member of the same name is. `inherits` is the IDL parent.
//
// Read by host_runtime.js (see "WebIDL string conversions" there), which
// is the one place the conversions are carried out.
globalThis.__rbIdlSignatures = {
  "AbortSignal": {
    "inherits": "EventTarget"
  },
  "Attr": {
    "inherits": "Node",
    "attributes": {
      "value": "DOMString"
    }
  },
  "AudioTrackList": {
    "inherits": "EventTarget",
    "operations": {
      "getTrackById": ["DOMString"]
    }
  },
  "BeforeUnloadEvent": {
    "inherits": "Event",
    "attributes": {
      "returnValue": "DOMString"
    }
  },
  "Blob": {
    "operations": {
      "slice": [null,null,"optional DOMString"]
    }
  },
  "BroadcastChannel": {
    "constructor": ["DOMString"],
    "inherits": "EventTarget"
  },
  "CDATASection": {
    "inherits": "Text"
  },
  "CSSGroupingRule": {
    "inherits": "CSSRule",
    "operations": {
      "insertRule": ["DOMString"]
    }
  },
  "CSSImportRule": {
    "inherits": "CSSRule"
  },
  "CSSMarginRule": {
    "inherits": "CSSRule"
  },
  "CSSNamespaceRule": {
    "inherits": "CSSRule"
  },
  "CSSPageDescriptors": {
    "inherits": "CSSStyleDeclaration",
    "attributes": {
      "bleed": "[LegacyNullToEmptyString] DOMString",
      "margin": "[LegacyNullToEmptyString] DOMString",
      "margin-bottom": "[LegacyNullToEmptyString] DOMString",
      "margin-left": "[LegacyNullToEmptyString] DOMString",
      "margin-right": "[LegacyNullToEmptyString] DOMString",
      "margin-top": "[LegacyNullToEmptyString] DOMString",
      "marginBottom": "[LegacyNullToEmptyString] DOMString",
      "marginLeft": "[LegacyNullToEmptyString] DOMString",
      "marginRight": "[LegacyNullToEmptyString] DOMString",
      "marginTop": "[LegacyNullToEmptyString] DOMString",
      "marks": "[LegacyNullToEmptyString] DOMString",
      "page-orientation": "[LegacyNullToEmptyString] DOMString",
      "pageOrientation": "[LegacyNullToEmptyString] DOMString",
      "size": "[LegacyNullToEmptyString] DOMString"
    }
  },
  "CSSPageRule": {
    "inherits": "CSSGroupingRule",
    "attributes": {
      "selectorText": "DOMString"
    }
  },
  "CSSRule": {
    "attributes": {
      "cssText": "DOMString"
    }
  },
  "CSSStyleDeclaration": {
    "operations": {
      "getPropertyPriority": ["DOMString"],
      "getPropertyValue": ["DOMString"],
      "removeProperty": ["DOMString"],
      "setProperty": ["DOMString","[LegacyNullToEmptyString] DOMString","optional [LegacyNullToEmptyString] DOMString"]
    },
    "attributes": {
      "cssText": "DOMString"
    }
  },
  "CSSStyleProperties": {
    "inherits": "CSSStyleDeclaration",
    "attributes": {
      "cssFloat": "[LegacyNullToEmptyString] DOMString"
    }
  },
  "CSSStyleRule": {
    "inherits": "CSSGroupingRule",
    "attributes": {
      "selectorText": "DOMString"
    }
  },
  "CSSStyleSheet": {
    "inherits": "StyleSheet",
    "operations": {
      "addRule": ["optional DOMString","optional DOMString"],
      "insertRule": ["DOMString"],
      "replace": ["USVString"],
      "replaceSync": ["USVString"]
    }
  },
  "CanvasGradient": {
    "operations": {
      "addColorStop": [null,"DOMString"]
    }
  },
  "CanvasRenderingContext2D": {
    "operations": {
      "createPattern": [null,"[LegacyNullToEmptyString] DOMString"],
      "fillText": ["DOMString"],
      "measureText": ["DOMString"],
      "strokeText": ["DOMString"]
    },
    "attributes": {
      "filter": "DOMString",
      "font": "DOMString",
      "globalCompositeOperation": "DOMString",
      "lang": "DOMString",
      "letterSpacing": "DOMString",
      "shadowColor": "DOMString",
      "wordSpacing": "DOMString"
    }
  },
  "CharacterData": {
    "inherits": "Node",
    "operations": {
      "appendData": ["DOMString"],
      "insertData": [null,"DOMString"],
      "replaceData": [null,null,"DOMString"]
    },
    "attributes": {
      "data": "[LegacyNullToEmptyString] DOMString"
    }
  },
  "CloseWatcher": {
    "inherits": "EventTarget"
  },
  "CommandEvent": {
    "constructor": ["DOMString"],
    "inherits": "Event"
  },
  "Comment": {
    "constructor": ["optional DOMString"],
    "inherits": "CharacterData"
  },
  "CompositionEvent": {
    "constructor": ["DOMString"],
    "inherits": "UIEvent",
    "operations": {
      "initCompositionEvent": ["DOMString",null,null,null,"optional DOMString"]
    }
  },
  "CustomElementRegistry": {
    "operations": {
      "define": ["DOMString"],
      "get": ["DOMString"],
      "whenDefined": ["DOMString"]
    }
  },
  "CustomEvent": {
    "constructor": ["DOMString"],
    "inherits": "Event",
    "operations": {
      "initCustomEvent": ["DOMString"]
    }
  },
  "DOMImplementation": {
    "operations": {
      "createDocument": ["DOMString?","[LegacyNullToEmptyString] DOMString"],
      "createDocumentType": ["DOMString","DOMString","DOMString"],
      "createHTMLDocument": ["optional DOMString"]
    }
  },
  "DOMParser": {
    "operations": {
      "parseFromString": ["DOMString"]
    }
  },
  "DOMStringList": {
    "operations": {
      "contains": ["DOMString"]
    }
  },
  "DOMTokenList": {
    "operations": {
      "add": ["DOMString..."],
      "contains": ["DOMString"],
      "remove": ["DOMString..."],
      "replace": ["DOMString","DOMString"],
      "supports": ["DOMString"],
      "toggle": ["DOMString"]
    },
    "attributes": {
      "value": "DOMString"
    }
  },
  "DataTransfer": {
    "operations": {
      "clearData": ["optional DOMString"],
      "getData": ["DOMString"],
      "setData": ["DOMString","DOMString"]
    },
    "attributes": {
      "dropEffect": "DOMString",
      "effectAllowed": "DOMString"
    }
  },
  "DataTransferItemList": {
    "operations": {
      "add": [null,"optional DOMString"]
    }
  },
  "DedicatedWorkerGlobalScope": {
    "inherits": "WorkerGlobalScope"
  },
  "Document": {
    "inherits": "Node",
    "operations": {
      "ariaNotify": ["DOMString"],
      "createAttribute": ["DOMString"],
      "createAttributeNS": ["DOMString?","DOMString"],
      "createCDATASection": ["DOMString"],
      "createComment": ["DOMString"],
      "createElement": ["DOMString"],
      "createElementNS": ["DOMString?","DOMString"],
      "createEvent": ["DOMString"],
      "createExpression": ["DOMString"],
      "createProcessingInstruction": ["DOMString","DOMString"],
      "createTextNode": ["DOMString"],
      "evaluate": ["DOMString"],
      "execCommand": ["DOMString",null,"optional DOMString"],
      "getElementById": ["DOMString"],
      "getElementsByClassName": ["DOMString"],
      "getElementsByName": ["DOMString"],
      "getElementsByTagName": ["DOMString"],
      "getElementsByTagNameNS": ["DOMString?","DOMString"],
      "open": [null,"optional DOMString","optional DOMString"],
      "queryCommandEnabled": ["DOMString"],
      "queryCommandIndeterm": ["DOMString"],
      "queryCommandState": ["DOMString"],
      "queryCommandSupported": ["DOMString"],
      "queryCommandValue": ["DOMString"],
      "querySelector": ["DOMString"],
      "querySelectorAll": ["DOMString"],
      "write": ["DOMString..."],
      "writeln": ["DOMString..."]
    },
    "static_operations": {
      "parseHTML": ["DOMString"],
      "parseHTMLUnsafe": ["DOMString"]
    },
    "attributes": {
      "alinkColor": "[LegacyNullToEmptyString] DOMString",
      "bgColor": "[LegacyNullToEmptyString] DOMString",
      "cookie": "USVString",
      "designMode": "DOMString",
      "dir": "DOMString",
      "domain": "USVString",
      "fgColor": "[LegacyNullToEmptyString] DOMString",
      "linkColor": "[LegacyNullToEmptyString] DOMString",
      "title": "DOMString",
      "vlinkColor": "[LegacyNullToEmptyString] DOMString"
    }
  },
  "DocumentFragment": {
    "inherits": "Node",
    "operations": {
      "getElementById": ["DOMString"],
      "querySelector": ["DOMString"],
      "querySelectorAll": ["DOMString"]
    }
  },
  "DocumentType": {
    "inherits": "Node"
  },
  "DragEvent": {
    "constructor": ["DOMString"],
    "inherits": "MouseEvent"
  },
  "Element": {
    "inherits": "Node",
    "operations": {
      "ariaNotify": ["DOMString"],
      "closest": ["DOMString"],
      "getAttribute": ["DOMString"],
      "getAttributeNS": ["DOMString?","DOMString"],
      "getAttributeNode": ["DOMString"],
      "getAttributeNodeNS": ["DOMString?","DOMString"],
      "getElementsByClassName": ["DOMString"],
      "getElementsByTagName": ["DOMString"],
      "getElementsByTagNameNS": ["DOMString?","DOMString"],
      "hasAttribute": ["DOMString"],
      "hasAttributeNS": ["DOMString?","DOMString"],
      "insertAdjacentElement": ["DOMString"],
      "insertAdjacentHTML": ["DOMString","DOMString"],
      "insertAdjacentText": ["DOMString","DOMString"],
      "matches": ["DOMString"],
      "querySelector": ["DOMString"],
      "querySelectorAll": ["DOMString"],
      "removeAttribute": ["DOMString"],
      "removeAttributeNS": ["DOMString?","DOMString"],
      "setAttribute": ["DOMString","DOMString"],
      "setAttributeNS": ["DOMString?","DOMString","DOMString"],
      "setHTML": ["DOMString"],
      "setHTMLUnsafe": ["DOMString"],
      "toggleAttribute": ["DOMString"],
      "webkitMatchesSelector": ["DOMString"]
    },
    "attributes": {
      "ariaAtomic": "DOMString?",
      "ariaAutoComplete": "DOMString?",
      "ariaBrailleLabel": "DOMString?",
      "ariaBrailleRoleDescription": "DOMString?",
      "ariaBusy": "DOMString?",
      "ariaChecked": "DOMString?",
      "ariaColCount": "DOMString?",
      "ariaColIndex": "DOMString?",
      "ariaColIndexText": "DOMString?",
      "ariaColSpan": "DOMString?",
      "ariaCurrent": "DOMString?",
      "ariaDescription": "DOMString?",
      "ariaDisabled": "DOMString?",
      "ariaExpanded": "DOMString?",
      "ariaHasPopup": "DOMString?",
      "ariaHidden": "DOMString?",
      "ariaInvalid": "DOMString?",
      "ariaKeyShortcuts": "DOMString?",
      "ariaLabel": "DOMString?",
      "ariaLevel": "DOMString?",
      "ariaLive": "DOMString?",
      "ariaModal": "DOMString?",
      "ariaMultiLine": "DOMString?",
      "ariaMultiSelectable": "DOMString?",
      "ariaOrientation": "DOMString?",
      "ariaPlaceholder": "DOMString?",
      "ariaPosInSet": "DOMString?",
      "ariaPressed": "DOMString?",
      "ariaReadOnly": "DOMString?",
      "ariaRelevant": "DOMString?",
      "ariaRequired": "DOMString?",
      "ariaRoleDescription": "DOMString?",
      "ariaRowCount": "DOMString?",
      "ariaRowIndex": "DOMString?",
      "ariaRowIndexText": "DOMString?",
      "ariaRowSpan": "DOMString?",
      "ariaSelected": "DOMString?",
      "ariaSetSize": "DOMString?",
      "ariaSort": "DOMString?",
      "ariaValueMax": "DOMString?",
      "ariaValueMin": "DOMString?",
      "ariaValueNow": "DOMString?",
      "ariaValueText": "DOMString?",
      "className": "DOMString",
      "id": "DOMString",
      "innerHTML": "[LegacyNullToEmptyString] DOMString",
      "outerHTML": "[LegacyNullToEmptyString] DOMString",
      "role": "DOMString?",
      "slot": "DOMString"
    }
  },
  "ElementInternals": {
    "operations": {
      "setValidity": [null,"optional DOMString"]
    },
    "attributes": {
      "ariaAtomic": "DOMString?",
      "ariaAutoComplete": "DOMString?",
      "ariaBrailleLabel": "DOMString?",
      "ariaBrailleRoleDescription": "DOMString?",
      "ariaBusy": "DOMString?",
      "ariaChecked": "DOMString?",
      "ariaColCount": "DOMString?",
      "ariaColIndex": "DOMString?",
      "ariaColIndexText": "DOMString?",
      "ariaColSpan": "DOMString?",
      "ariaCurrent": "DOMString?",
      "ariaDescription": "DOMString?",
      "ariaDisabled": "DOMString?",
      "ariaExpanded": "DOMString?",
      "ariaHasPopup": "DOMString?",
      "ariaHidden": "DOMString?",
      "ariaInvalid": "DOMString?",
      "ariaKeyShortcuts": "DOMString?",
      "ariaLabel": "DOMString?",
      "ariaLevel": "DOMString?",
      "ariaLive": "DOMString?",
      "ariaModal": "DOMString?",
      "ariaMultiLine": "DOMString?",
      "ariaMultiSelectable": "DOMString?",
      "ariaOrientation": "DOMString?",
      "ariaPlaceholder": "DOMString?",
      "ariaPosInSet": "DOMString?",
      "ariaPressed": "DOMString?",
      "ariaReadOnly": "DOMString?",
      "ariaRelevant": "DOMString?",
      "ariaRequired": "DOMString?",
      "ariaRoleDescription": "DOMString?",
      "ariaRowCount": "DOMString?",
      "ariaRowIndex": "DOMString?",
      "ariaRowIndexText": "DOMString?",
      "ariaRowSpan": "DOMString?",
      "ariaSelected": "DOMString?",
      "ariaSetSize": "DOMString?",
      "ariaSort": "DOMString?",
      "ariaValueMax": "DOMString?",
      "ariaValueMin": "DOMString?",
      "ariaValueNow": "DOMString?",
      "ariaValueText": "DOMString?",
      "role": "DOMString?"
    }
  },
  "ErrorEvent": {
    "constructor": ["DOMString"],
    "inherits": "Event"
  },
  "Event": {
    "constructor": ["DOMString"],
    "operations": {
      "initEvent": ["DOMString"]
    }
  },
  "EventSource": {
    "constructor": ["USVString"],
    "inherits": "EventTarget"
  },
  "EventTarget": {
    "operations": {
      "addEventListener": ["DOMString"],
      "removeEventListener": ["DOMString"]
    }
  },
  "File": {
    "constructor": [null,"USVString"],
    "inherits": "Blob"
  },
  "FileReader": {
    "inherits": "EventTarget",
    "operations": {
      "readAsText": [null,"optional DOMString"]
    }
  },
  "FileReaderSync": {
    "operations": {
      "readAsText": [null,"optional DOMString"]
    }
  },
  "FocusEvent": {
    "constructor": ["DOMString"],
    "inherits": "UIEvent"
  },
  "FormData": {
    "operations": {
      "append": ["USVString",null,"optional USVString"],
      "delete": ["USVString"],
      "get": ["USVString"],
      "getAll": ["USVString"],
      "has": ["USVString"],
      "set": ["USVString",null,"optional USVString"]
    }
  },
  "FormDataEvent": {
    "constructor": ["DOMString"],
    "inherits": "Event"
  },
  "HTMLAllCollection": {
    "operations": {
      "item": ["optional DOMString"],
      "namedItem": ["DOMString"]
    }
  },
  "HTMLAnchorElement": {
    "inherits": "HTMLElement",
    "attributes": {
      "charset": "DOMString",
      "coords": "DOMString",
      "download": "DOMString",
      "hash": "USVString",
      "host": "USVString",
      "hostname": "USVString",
      "href": "USVString",
      "hreflang": "DOMString",
      "name": "DOMString",
      "password": "USVString",
      "pathname": "USVString",
      "ping": "USVString",
      "port": "USVString",
      "protocol": "USVString",
      "referrerPolicy": "DOMString",
      "rel": "DOMString",
      "rev": "DOMString",
      "search": "USVString",
      "shape": "DOMString",
      "target": "DOMString",
      "text": "DOMString",
      "type": "DOMString",
      "username": "USVString"
    }
  },
  "HTMLAreaElement": {
    "inherits": "HTMLElement",
    "attributes": {
      "alt": "DOMString",
      "coords": "DOMString",
      "download": "DOMString",
      "hash": "USVString",
      "host": "USVString",
      "hostname": "USVString",
      "href": "USVString",
      "hreflang": "DOMString",
      "password": "USVString",
      "pathname": "USVString",
      "ping": "USVString",
      "port": "USVString",
      "protocol": "USVString",
      "referrerPolicy": "DOMString",
      "rel": "DOMString",
      "search": "USVString",
      "shape": "DOMString",
      "target": "DOMString",
      "type": "DOMString",
      "username": "USVString"
    }
  },
  "HTMLAudioElement": {
    "inherits": "HTMLMediaElement"
  },
  "HTMLBRElement": {
    "inherits": "HTMLElement",
    "attributes": {
      "clear": "DOMString"
    }
  },
  "HTMLBaseElement": {
    "inherits": "HTMLElement",
    "attributes": {
      "href": "USVString",
      "target": "DOMString"
    }
  },
  "HTMLBodyElement": {
    "inherits": "HTMLElement",
    "attributes": {
      "aLink": "[LegacyNullToEmptyString] DOMString",
      "background": "DOMString",
      "bgColor": "[LegacyNullToEmptyString] DOMString",
      "link": "[LegacyNullToEmptyString] DOMString",
      "text": "[LegacyNullToEmptyString] DOMString",
      "vLink": "[LegacyNullToEmptyString] DOMString"
    }
  },
  "HTMLButtonElement": {
    "inherits": "HTMLElement",
    "operations": {
      "setCustomValidity": ["DOMString"]
    },
    "attributes": {
      "command": "DOMString",
      "formAction": "USVString",
      "formEnctype": "DOMString",
      "formMethod": "DOMString",
      "formTarget": "DOMString",
      "name": "DOMString",
      "popoverTargetAction": "DOMString",
      "type": "DOMString",
      "value": "DOMString"
    }
  },
  "HTMLCanvasElement": {
    "inherits": "HTMLElement",
    "operations": {
      "getContext": ["DOMString"],
      "toBlob": [null,"optional DOMString"],
      "toDataURL": ["optional DOMString"]
    }
  },
  "HTMLCollection": {
    "operations": {
      "namedItem": ["DOMString"]
    }
  },
  "HTMLDListElement": {
    "inherits": "HTMLElement"
  },
  "HTMLDataElement": {
    "inherits": "HTMLElement",
    "attributes": {
      "value": "DOMString"
    }
  },
  "HTMLDataListElement": {
    "inherits": "HTMLElement"
  },
  "HTMLDetailsElement": {
    "inherits": "HTMLElement",
    "attributes": {
      "name": "DOMString"
    }
  },
  "HTMLDialogElement": {
    "inherits": "HTMLElement",
    "operations": {
      "close": ["optional DOMString"],
      "requestClose": ["optional DOMString"]
    },
    "attributes": {
      "closedBy": "DOMString",
      "returnValue": "DOMString"
    }
  },
  "HTMLDirectoryElement": {
    "inherits": "HTMLElement"
  },
  "HTMLDivElement": {
    "inherits": "HTMLElement",
    "attributes": {
      "align": "DOMString"
    }
  },
  "HTMLElement": {
    "inherits": "Element",
    "attributes": {
      "accessKey": "DOMString",
      "autocapitalize": "DOMString",
      "contentEditable": "DOMString",
      "dir": "DOMString",
      "enterKeyHint": "DOMString",
      "innerText": "[LegacyNullToEmptyString] DOMString",
      "inputMode": "DOMString",
      "lang": "DOMString",
      "nonce": "DOMString",
      "outerText": "[LegacyNullToEmptyString] DOMString",
      "popover": "DOMString?",
      "title": "DOMString",
      "writingSuggestions": "DOMString"
    }
  },
  "HTMLEmbedElement": {
    "inherits": "HTMLElement",
    "attributes": {
      "align": "DOMString",
      "height": "DOMString",
      "name": "DOMString",
      "src": "USVString",
      "type": "DOMString",
      "width": "DOMString"
    }
  },
  "HTMLFieldSetElement": {
    "inherits": "HTMLElement",
    "operations": {
      "setCustomValidity": ["DOMString"]
    },
    "attributes": {
      "name": "DOMString"
    }
  },
  "HTMLFontElement": {
    "inherits": "HTMLElement",
    "attributes": {
      "color": "[LegacyNullToEmptyString] DOMString",
      "face": "DOMString",
      "size": "DOMString"
    }
  },
  "HTMLFormControlsCollection": {
    "inherits": "HTMLCollection",
    "operations": {
      "namedItem": ["DOMString"]
    }
  },
  "HTMLFormElement": {
    "inherits": "HTMLElement",
    "attributes": {
      "acceptCharset": "DOMString",
      "action": "USVString",
      "autocomplete": "DOMString",
      "encoding": "DOMString",
      "enctype": "DOMString",
      "method": "DOMString",
      "name": "DOMString",
      "rel": "DOMString",
      "target": "DOMString"
    }
  },
  "HTMLFrameElement": {
    "inherits": "HTMLElement",
    "attributes": {
      "frameBorder": "DOMString",
      "longDesc": "USVString",
      "marginHeight": "[LegacyNullToEmptyString] DOMString",
      "marginWidth": "[LegacyNullToEmptyString] DOMString",
      "name": "DOMString",
      "scrolling": "DOMString",
      "src": "USVString"
    }
  },
  "HTMLFrameSetElement": {
    "inherits": "HTMLElement",
    "attributes": {
      "cols": "DOMString",
      "rows": "DOMString"
    }
  },
  "HTMLHRElement": {
    "inherits": "HTMLElement",
    "attributes": {
      "align": "DOMString",
      "color": "DOMString",
      "size": "DOMString",
      "width": "DOMString"
    }
  },
  "HTMLHeadElement": {
    "inherits": "HTMLElement"
  },
  "HTMLHeadingElement": {
    "inherits": "HTMLElement",
    "attributes": {
      "align": "DOMString"
    }
  },
  "HTMLHtmlElement": {
    "inherits": "HTMLElement",
    "attributes": {
      "version": "DOMString"
    }
  },
  "HTMLIFrameElement": {
    "inherits": "HTMLElement",
    "attributes": {
      "align": "DOMString",
      "allow": "DOMString",
      "frameBorder": "DOMString",
      "height": "DOMString",
      "loading": "DOMString",
      "longDesc": "USVString",
      "marginHeight": "[LegacyNullToEmptyString] DOMString",
      "marginWidth": "[LegacyNullToEmptyString] DOMString",
      "name": "DOMString",
      "referrerPolicy": "DOMString",
      "scrolling": "DOMString",
      "src": "USVString",
      "srcdoc": "DOMString",
      "width": "DOMString"
    }
  },
  "HTMLImageElement": {
    "inherits": "HTMLElement",
    "attributes": {
      "align": "DOMString",
      "alt": "DOMString",
      "border": "[LegacyNullToEmptyString] DOMString",
      "crossOrigin": "DOMString?",
      "decoding": "DOMString",
      "fetchPriority": "DOMString",
      "loading": "DOMString",
      "longDesc": "USVString",
      "lowsrc": "USVString",
      "name": "DOMString",
      "referrerPolicy": "DOMString",
      "sizes": "DOMString",
      "src": "USVString",
      "srcset": "USVString",
      "useMap": "DOMString"
    }
  },
  "HTMLInputElement": {
    "inherits": "HTMLElement",
    "operations": {
      "setCustomValidity": ["DOMString"],
      "setRangeText": ["DOMString"],
      "setSelectionRange": [null,null,"optional DOMString"]
    },
    "attributes": {
      "accept": "DOMString",
      "align": "DOMString",
      "alt": "DOMString",
      "autocomplete": "DOMString",
      "colorSpace": "DOMString",
      "defaultValue": "DOMString",
      "dirName": "DOMString",
      "formAction": "USVString",
      "formEnctype": "DOMString",
      "formMethod": "DOMString",
      "formTarget": "DOMString",
      "max": "DOMString",
      "min": "DOMString",
      "name": "DOMString",
      "pattern": "DOMString",
      "placeholder": "DOMString",
      "popoverTargetAction": "DOMString",
      "selectionDirection": "DOMString?",
      "src": "USVString",
      "step": "DOMString",
      "type": "DOMString",
      "useMap": "DOMString",
      "value": "[LegacyNullToEmptyString] DOMString"
    }
  },
  "HTMLLIElement": {
    "inherits": "HTMLElement",
    "attributes": {
      "type": "DOMString"
    }
  },
  "HTMLLabelElement": {
    "inherits": "HTMLElement",
    "attributes": {
      "htmlFor": "DOMString"
    }
  },
  "HTMLLegendElement": {
    "inherits": "HTMLElement",
    "attributes": {
      "align": "DOMString"
    }
  },
  "HTMLLinkElement": {
    "inherits": "HTMLElement",
    "attributes": {
      "as": "DOMString",
      "charset": "DOMString",
      "crossOrigin": "DOMString?",
      "fetchPriority": "DOMString",
      "href": "USVString",
      "hreflang": "DOMString",
      "imageSizes": "DOMString",
      "imageSrcset": "USVString",
      "integrity": "DOMString",
      "media": "DOMString",
      "referrerPolicy": "DOMString",
      "rel": "DOMString",
      "rev": "DOMString",
      "target": "DOMString",
      "type": "DOMString"
    }
  },
  "HTMLMapElement": {
    "inherits": "HTMLElement",
    "attributes": {
      "name": "DOMString"
    }
  },
  "HTMLMarqueeElement": {
    "inherits": "HTMLElement",
    "attributes": {
      "behavior": "DOMString",
      "bgColor": "DOMString",
      "direction": "DOMString",
      "height": "DOMString",
      "width": "DOMString"
    }
  },
  "HTMLMediaElement": {
    "inherits": "HTMLElement",
    "operations": {
      "addTextTrack": [null,"optional DOMString","optional DOMString"],
      "canPlayType": ["DOMString"]
    },
    "attributes": {
      "crossOrigin": "DOMString?",
      "loading": "DOMString",
      "preload": "DOMString",
      "src": "USVString"
    }
  },
  "HTMLMenuElement": {
    "inherits": "HTMLElement"
  },
  "HTMLMetaElement": {
    "inherits": "HTMLElement",
    "attributes": {
      "content": "DOMString",
      "httpEquiv": "DOMString",
      "media": "DOMString",
      "name": "DOMString",
      "scheme": "DOMString"
    }
  },
  "HTMLMeterElement": {
    "inherits": "HTMLElement"
  },
  "HTMLModElement": {
    "inherits": "HTMLElement",
    "attributes": {
      "cite": "USVString",
      "dateTime": "DOMString"
    }
  },
  "HTMLOListElement": {
    "inherits": "HTMLElement",
    "attributes": {
      "type": "DOMString"
    }
  },
  "HTMLObjectElement": {
    "inherits": "HTMLElement",
    "operations": {
      "setCustomValidity": ["DOMString"]
    },
    "attributes": {
      "align": "DOMString",
      "archive": "DOMString",
      "border": "[LegacyNullToEmptyString] DOMString",
      "code": "DOMString",
      "codeBase": "DOMString",
      "codeType": "DOMString",
      "data": "USVString",
      "height": "DOMString",
      "name": "DOMString",
      "standby": "DOMString",
      "type": "DOMString",
      "useMap": "DOMString",
      "width": "DOMString"
    }
  },
  "HTMLOptGroupElement": {
    "inherits": "HTMLElement",
    "attributes": {
      "label": "DOMString"
    }
  },
  "HTMLOptionElement": {
    "inherits": "HTMLElement",
    "attributes": {
      "label": "DOMString",
      "text": "DOMString",
      "value": "DOMString"
    }
  },
  "HTMLOptionsCollection": {
    "inherits": "HTMLCollection"
  },
  "HTMLOutputElement": {
    "inherits": "HTMLElement",
    "operations": {
      "setCustomValidity": ["DOMString"]
    },
    "attributes": {
      "defaultValue": "DOMString",
      "name": "DOMString",
      "value": "DOMString"
    }
  },
  "HTMLParagraphElement": {
    "inherits": "HTMLElement",
    "attributes": {
      "align": "DOMString"
    }
  },
  "HTMLParamElement": {
    "inherits": "HTMLElement",
    "attributes": {
      "name": "DOMString",
      "type": "DOMString",
      "value": "DOMString",
      "valueType": "DOMString"
    }
  },
  "HTMLPictureElement": {
    "inherits": "HTMLElement"
  },
  "HTMLPreElement": {
    "inherits": "HTMLElement"
  },
  "HTMLProgressElement": {
    "inherits": "HTMLElement"
  },
  "HTMLQuoteElement": {
    "inherits": "HTMLElement",
    "attributes": {
      "cite": "USVString"
    }
  },
  "HTMLScriptElement": {
    "inherits": "HTMLElement",
    "static_operations": {
      "supports": ["DOMString"]
    },
    "attributes": {
      "charset": "DOMString",
      "crossOrigin": "DOMString?",
      "event": "DOMString",
      "fetchPriority": "DOMString",
      "htmlFor": "DOMString",
      "integrity": "DOMString",
      "referrerPolicy": "DOMString",
      "src": "USVString",
      "text": "DOMString",
      "type": "DOMString"
    }
  },
  "HTMLSelectElement": {
    "inherits": "HTMLElement",
    "operations": {
      "namedItem": ["DOMString"],
      "setCustomValidity": ["DOMString"]
    },
    "attributes": {
      "autocomplete": "DOMString",
      "name": "DOMString",
      "value": "DOMString"
    }
  },
  "HTMLSelectedContentElement": {
    "inherits": "HTMLElement"
  },
  "HTMLSlotElement": {
    "inherits": "HTMLElement",
    "attributes": {
      "name": "DOMString"
    }
  },
  "HTMLSourceElement": {
    "inherits": "HTMLElement",
    "attributes": {
      "media": "DOMString",
      "sizes": "DOMString",
      "src": "USVString",
      "srcset": "USVString",
      "type": "DOMString"
    }
  },
  "HTMLSpanElement": {
    "inherits": "HTMLElement"
  },
  "HTMLStyleElement": {
    "inherits": "HTMLElement",
    "attributes": {
      "media": "DOMString",
      "type": "DOMString"
    }
  },
  "HTMLTableCaptionElement": {
    "inherits": "HTMLElement",
    "attributes": {
      "align": "DOMString"
    }
  },
  "HTMLTableCellElement": {
    "inherits": "HTMLElement",
    "attributes": {
      "abbr": "DOMString",
      "align": "DOMString",
      "axis": "DOMString",
      "bgColor": "[LegacyNullToEmptyString] DOMString",
      "ch": "DOMString",
      "chOff": "DOMString",
      "headers": "DOMString",
      "height": "DOMString",
      "scope": "DOMString",
      "vAlign": "DOMString",
      "width": "DOMString"
    }
  },
  "HTMLTableColElement": {
    "inherits": "HTMLElement",
    "attributes": {
      "align": "DOMString",
      "ch": "DOMString",
      "chOff": "DOMString",
      "vAlign": "DOMString",
      "width": "DOMString"
    }
  },
  "HTMLTableElement": {
    "inherits": "HTMLElement",
    "attributes": {
      "align": "DOMString",
      "bgColor": "[LegacyNullToEmptyString] DOMString",
      "border": "DOMString",
      "cellPadding": "[LegacyNullToEmptyString] DOMString",
      "cellSpacing": "[LegacyNullToEmptyString] DOMString",
      "frame": "DOMString",
      "rules": "DOMString",
      "summary": "DOMString",
      "width": "DOMString"
    }
  },
  "HTMLTableRowElement": {
    "inherits": "HTMLElement",
    "attributes": {
      "align": "DOMString",
      "bgColor": "[LegacyNullToEmptyString] DOMString",
      "ch": "DOMString",
      "chOff": "DOMString",
      "vAlign": "DOMString"
    }
  },
  "HTMLTableSectionElement": {
    "inherits": "HTMLElement",
    "attributes": {
      "align": "DOMString",
      "ch": "DOMString",
      "chOff": "DOMString",
      "vAlign": "DOMString"
    }
  },
  "HTMLTemplateElement": {
    "inherits": "HTMLElement",
    "attributes": {
      "htmlFor": "DOMString",
      "shadowRootCustomElementRegistry": "DOMString",
      "shadowRootMode": "DOMString",
      "shadowRootSlotAssignment": "DOMString"
    }
  },
  "HTMLTextAreaElement": {
    "inherits": "HTMLElement",
    "operations": {
      "setCustomValidity": ["DOMString"],
      "setRangeText": ["DOMString"],
      "setSelectionRange": [null,null,"optional DOMString"]
    },
    "attributes": {
      "autocomplete": "DOMString",
      "defaultValue": "DOMString",
      "dirName": "DOMString",
      "name": "DOMString",
      "placeholder": "DOMString",
      "selectionDirection": "DOMString",
      "value": "[LegacyNullToEmptyString] DOMString",
      "wrap": "DOMString"
    }
  },
  "HTMLTimeElement": {
    "inherits": "HTMLElement",
    "attributes": {
      "dateTime": "DOMString"
    }
  },
  "HTMLTitleElement": {
    "inherits": "HTMLElement",
    "attributes": {
      "text": "DOMString"
    }
  },
  "HTMLTrackElement": {
    "inherits": "HTMLElement",
    "attributes": {
      "kind": "DOMString",
      "label": "DOMString",
      "src": "USVString",
      "srclang": "DOMString"
    }
  },
  "HTMLUListElement": {
    "inherits": "HTMLElement",
    "attributes": {
      "type": "DOMString"
    }
  },
  "HTMLUnknownElement": {
    "inherits": "HTMLElement"
  },
  "HTMLVideoElement": {
    "inherits": "HTMLMediaElement",
    "attributes": {
      "poster": "USVString"
    }
  },
  "HashChangeEvent": {
    "constructor": ["DOMString"],
    "inherits": "Event"
  },
  "Headers": {
    "operations": {
      "append": ["ByteString","ByteString"],
      "delete": ["ByteString"],
      "get": ["ByteString"],
      "has": ["ByteString"],
      "set": ["ByteString","ByteString"]
    }
  },
  "History": {
    "operations": {
      "pushState": [null,"DOMString","optional USVString?"],
      "replaceState": [null,"DOMString","optional USVString?"]
    }
  },
  "InputEvent": {
    "constructor": ["DOMString"],
    "inherits": "UIEvent"
  },
  "KeyboardEvent": {
    "constructor": ["DOMString"],
    "inherits": "UIEvent",
    "operations": {
      "getModifierState": ["DOMString"],
      "initKeyboardEvent": ["DOMString",null,null,null,"optional DOMString"]
    }
  },
  "Location": {
    "operations": {
      "assign": ["USVString"],
      "replace": ["USVString"]
    },
    "attributes": {
      "hash": "USVString",
      "host": "USVString",
      "hostname": "USVString",
      "href": "USVString",
      "pathname": "USVString",
      "port": "USVString",
      "protocol": "USVString",
      "search": "USVString"
    }
  },
  "MediaList": {
    "operations": {
      "appendMedium": ["DOMString"],
      "deleteMedium": ["DOMString"]
    },
    "attributes": {
      "mediaText": "[LegacyNullToEmptyString] DOMString"
    }
  },
  "MediaQueryList": {
    "inherits": "EventTarget"
  },
  "MediaQueryListEvent": {
    "constructor": ["DOMString"],
    "inherits": "Event"
  },
  "MessageEvent": {
    "constructor": ["DOMString"],
    "inherits": "Event",
    "operations": {
      "initMessageEvent": ["DOMString",null,null,null,"optional USVString","optional DOMString"]
    }
  },
  "MessagePort": {
    "inherits": "EventTarget"
  },
  "MimeTypeArray": {
    "operations": {
      "namedItem": ["DOMString"]
    }
  },
  "NamedNodeMap": {
    "operations": {
      "getNamedItem": ["DOMString"],
      "getNamedItemNS": ["DOMString?","DOMString"],
      "removeNamedItem": ["DOMString"],
      "removeNamedItemNS": ["DOMString?","DOMString"]
    }
  },
  "NavigateEvent": {
    "constructor": ["DOMString"],
    "inherits": "Event"
  },
  "Navigation": {
    "inherits": "EventTarget",
    "operations": {
      "navigate": ["USVString"],
      "traverseTo": ["DOMString"]
    }
  },
  "NavigationCurrentEntryChangeEvent": {
    "constructor": ["DOMString"],
    "inherits": "Event"
  },
  "NavigationHistoryEntry": {
    "inherits": "EventTarget"
  },
  "NavigationPrecommitController": {
    "operations": {
      "redirect": ["USVString"]
    }
  },
  "Navigator": {
    "operations": {
      "registerProtocolHandler": ["DOMString","USVString"],
      "unregisterProtocolHandler": ["DOMString","USVString"]
    }
  },
  "Node": {
    "inherits": "EventTarget",
    "operations": {
      "isDefaultNamespace": ["DOMString?"],
      "lookupNamespaceURI": ["DOMString?"],
      "lookupPrefix": ["DOMString?"]
    },
    "attributes": {
      "nodeValue": "DOMString?",
      "textContent": "DOMString?"
    }
  },
  "OffscreenCanvas": {
    "inherits": "EventTarget"
  },
  "OffscreenCanvasRenderingContext2D": {
    "operations": {
      "createPattern": [null,"[LegacyNullToEmptyString] DOMString"],
      "fillText": ["DOMString"],
      "measureText": ["DOMString"],
      "strokeText": ["DOMString"]
    },
    "attributes": {
      "filter": "DOMString",
      "font": "DOMString",
      "globalCompositeOperation": "DOMString",
      "lang": "DOMString",
      "letterSpacing": "DOMString",
      "shadowColor": "DOMString",
      "wordSpacing": "DOMString"
    }
  },
  "PageRevealEvent": {
    "constructor": ["DOMString"],
    "inherits": "Event"
  },
  "PageSwapEvent": {
    "constructor": ["DOMString"],
    "inherits": "Event"
  },
  "PageTransitionEvent": {
    "constructor": ["DOMString"],
    "inherits": "Event"
  },
  "Plugin": {
    "operations": {
      "namedItem": ["DOMString"]
    }
  },
  "PluginArray": {
    "operations": {
      "namedItem": ["DOMString"]
    }
  },
  "PopStateEvent": {
    "constructor": ["DOMString"],
    "inherits": "Event"
  },
  "ProcessingInstruction": {
    "constructor": ["DOMString","optional DOMString"],
    "inherits": "CharacterData",
    "operations": {
      "getAttribute": ["DOMString"],
      "hasAttribute": ["DOMString"],
      "removeAttribute": ["DOMString"],
      "setAttribute": ["DOMString","DOMString"],
      "toggleAttribute": ["DOMString"]
    }
  },
  "ProgressEvent": {
    "constructor": ["DOMString"],
    "inherits": "Event"
  },
  "PromiseRejectionEvent": {
    "constructor": ["DOMString"],
    "inherits": "Event"
  },
  "RadioNodeList": {
    "inherits": "NodeList",
    "attributes": {
      "value": "DOMString"
    }
  },
  "Range": {
    "inherits": "AbstractRange",
    "operations": {
      "createContextualFragment": ["DOMString"]
    }
  },
  "Response": {
    "static_operations": {
      "redirect": ["USVString"]
    }
  },
  "Selection": {
    "operations": {
      "modify": ["optional DOMString","optional DOMString","optional DOMString"]
    }
  },
  "ShadowRoot": {
    "inherits": "DocumentFragment",
    "operations": {
      "setHTML": ["DOMString"],
      "setHTMLUnsafe": ["DOMString"]
    },
    "attributes": {
      "innerHTML": "[LegacyNullToEmptyString] DOMString"
    }
  },
  "SharedWorker": {
    "constructor": ["USVString"],
    "inherits": "EventTarget"
  },
  "SharedWorkerGlobalScope": {
    "inherits": "WorkerGlobalScope"
  },
  "StaticRange": {
    "inherits": "AbstractRange"
  },
  "Storage": {
    "operations": {
      "getItem": ["DOMString"],
      "removeItem": ["DOMString"],
      "setItem": ["DOMString","DOMString"]
    }
  },
  "StorageEvent": {
    "constructor": ["DOMString"],
    "inherits": "Event",
    "operations": {
      "initStorageEvent": ["DOMString",null,null,"optional DOMString?","optional DOMString?","optional DOMString?","optional USVString"]
    }
  },
  "SubmitEvent": {
    "constructor": ["DOMString"],
    "inherits": "Event"
  },
  "Text": {
    "constructor": ["optional DOMString"],
    "inherits": "CharacterData"
  },
  "TextDecoder": {
    "constructor": ["optional DOMString"]
  },
  "TextDecoderStream": {
    "constructor": ["optional DOMString"]
  },
  "TextEncoder": {
    "operations": {
      "encode": ["optional USVString"],
      "encodeInto": ["USVString"]
    }
  },
  "TextEvent": {
    "inherits": "UIEvent",
    "operations": {
      "initTextEvent": ["DOMString",null,null,null,"optional DOMString"]
    }
  },
  "TextTrack": {
    "inherits": "EventTarget"
  },
  "TextTrackCue": {
    "inherits": "EventTarget",
    "attributes": {
      "id": "DOMString"
    }
  },
  "TextTrackCueList": {
    "operations": {
      "getCueById": ["DOMString"]
    }
  },
  "TextTrackList": {
    "inherits": "EventTarget",
    "operations": {
      "getTrackById": ["DOMString"]
    }
  },
  "ToggleEvent": {
    "constructor": ["DOMString"],
    "inherits": "Event"
  },
  "TrackEvent": {
    "constructor": ["DOMString"],
    "inherits": "Event"
  },
  "UIEvent": {
    "constructor": ["DOMString"],
    "inherits": "Event",
    "operations": {
      "initUIEvent": ["DOMString"]
    }
  },
  "URL": {
    "constructor": ["USVString","optional USVString"],
    "static_operations": {
      "canParse": ["USVString","optional USVString"],
      "parse": ["USVString","optional USVString"],
      "revokeObjectURL": ["DOMString"]
    },
    "attributes": {
      "hash": "USVString",
      "host": "USVString",
      "hostname": "USVString",
      "href": "USVString",
      "password": "USVString",
      "pathname": "USVString",
      "port": "USVString",
      "protocol": "USVString",
      "search": "USVString",
      "username": "USVString"
    }
  },
  "URLSearchParams": {
    "operations": {
      "append": ["USVString","USVString"],
      "delete": ["USVString","optional USVString"],
      "get": ["USVString"],
      "getAll": ["USVString"],
      "has": ["USVString","optional USVString"],
      "set": ["USVString","USVString"]
    }
  },
  "VideoTrackList": {
    "inherits": "EventTarget",
    "operations": {
      "getTrackById": ["DOMString"]
    }
  },
  "VisibilityStateEntry": {
    "inherits": "PerformanceEntry"
  },
  "VisualViewport": {
    "inherits": "EventTarget"
  },
  "Window": {
    "inherits": "EventTarget",
    "operations": {
      "alert": ["optional DOMString"],
      "atob": ["DOMString"],
      "btoa": ["DOMString"],
      "confirm": ["optional DOMString"],
      "getComputedStyle": [null,"optional DOMString?"],
      "matchMedia": ["DOMString"],
      "open": ["optional USVString","optional DOMString","optional [LegacyNullToEmptyString] DOMString"],
      "prompt": ["optional DOMString","optional DOMString"]
    },
    "attributes": {
      "name": "DOMString",
      "status": "DOMString"
    }
  },
  "Worker": {
    "constructor": ["USVString"],
    "inherits": "EventTarget"
  },
  "WorkerGlobalScope": {
    "inherits": "EventTarget",
    "operations": {
      "atob": ["DOMString"],
      "btoa": ["DOMString"],
      "importScripts": ["USVString..."]
    }
  },
  "Worklet": {
    "operations": {
      "addModule": ["USVString"]
    }
  },
  "XMLDocument": {
    "inherits": "Document"
  },
  "XMLHttpRequest": {
    "inherits": "XMLHttpRequestEventTarget",
    "operations": {
      "getResponseHeader": ["ByteString"],
      "open": ["ByteString","USVString",null,"optional USVString?","optional USVString?"],
      "overrideMimeType": ["DOMString"],
      "setRequestHeader": ["ByteString","ByteString"]
    }
  },
  "XMLHttpRequestEventTarget": {
    "inherits": "EventTarget"
  },
  "XMLHttpRequestUpload": {
    "inherits": "XMLHttpRequestEventTarget"
  },
  "XPathEvaluator": {
    "operations": {
      "createExpression": ["DOMString"],
      "evaluate": ["DOMString"]
    }
  },
  "XPathNSResolver": {
    "operations": {
      "lookupNamespaceURI": ["DOMString?"]
    }
  },
  "XSLTProcessor": {
    "operations": {
      "getParameter": ["[LegacyNullToEmptyString] DOMString","DOMString"],
      "removeParameter": ["[LegacyNullToEmptyString] DOMString","DOMString"],
      "setParameter": ["[LegacyNullToEmptyString] DOMString","DOMString"]
    }
  }
};
