# frozen_string_literal: true

require_relative "test_helper"

# Corpus regression for Playwright-compatible ARIA snapshots.
#
# The fixtures under `test/fixtures/aria_corpus/NNNN/` are generated by the
# aria-snapshot-pbt tool (see /Users/maki/git/aria-snapshot-pbt): real
# Playwright produces each `expected.yaml`, normalized into Dommy's notation.
# Each case asserts that `Dommy.parse(input.html).document.aria_snapshot`
# reproduces it byte-for-byte.
#
# Regenerate with:
#   cd /Users/maki/git/aria-snapshot-pbt
#   pnpm gen-corpus --count 500 \
#     --out /Users/maki/git/dommy/gems/dommy/test/fixtures/aria_corpus
#
# Point at a different corpus with DOMMY_ARIA_CORPUS=/path.
class TestAriaCorpus < Minitest::Test
  CORPUS_DIR = ENV.fetch(
    "DOMMY_ARIA_CORPUS",
    File.expand_path("fixtures/aria_corpus", __dir__),
  )

  case_dirs =
    if Dir.exist?(CORPUS_DIR)
      Dir.children(CORPUS_DIR)
        .select { |name| File.directory?(File.join(CORPUS_DIR, name)) }
        .sort
    else
      []
    end

  if case_dirs.empty?
    def test_corpus_present
      skip "No ARIA corpus at #{CORPUS_DIR}; run `pnpm gen-corpus --out ...` to populate."
    end
  else
    case_dirs.each do |name|
      define_method("test_case_#{name}") do
        dir = File.join(CORPUS_DIR, name)
        html = File.read(File.join(dir, "input.html"))
        expected = File.read(File.join(dir, "expected.yaml"))
        actual = Dommy.parse(html).document.aria_snapshot
        assert_equal expected, actual, "ARIA snapshot mismatch for corpus case #{name}"
      end
    end
  end
end
