#!/usr/bin/env ruby
# frozen_string_literal: true
#
# Build compact IDNA / Bidi / Joining-Type lookup tables from the
# Unicode source files vendored under `vendor/unicode/`. Output goes
# to `lib/dommy/internal/idna_data.rb`.
#
# Source files (Unicode 16.0):
#   IdnaMappingTable.txt    https://www.unicode.org/Public/idna/16.0.0/
#   DerivedBidiClass.txt    https://www.unicode.org/Public/16.0.0/ucd/extracted/
#   DerivedJoiningType.txt  https://www.unicode.org/Public/16.0.0/ucd/extracted/
#
# Re-run after upgrading Unicode versions.

require "pathname"

ROOT = Pathname.new(__dir__).parent
VENDOR_DIR = ROOT / "vendor/unicode"
OUTPUT = ROOT / "lib/dommy/internal/idna_data.rb"

# WHATWG URL IDNA parameters:
#   UseSTD3ASCIIRules    = false
#   Transitional_Processing = false (so `deviation` is treated as valid)
def remap_idna_status(status)
  case status
  when "valid", "deviation", "disallowed_STD3_valid"
    :valid
  when "mapped", "disallowed_STD3_mapped"
    :mapped
  when "ignored"
    :ignored
  when "disallowed"
    :disallowed
  else
    raise "unexpected IDNA status: #{status.inspect}"
  end
end

def parse_range(token)
  if token.include?("..")
    a, b = token.split("..")
    [a.to_i(16), b.to_i(16)]
  else
    cp = token.to_i(16)
    [cp, cp]
  end
end

def parse_mapping_field(field)
  field = field.to_s.strip
  return nil if field.empty?

  field.split.map { |cp| cp.to_i(16) }.pack("U*")
end

# Read a UCD-style file as an enumerator of [start_cp, end_cp, *fields].
def read_ucd(path)
  Enumerator.new do |y|
    path.each_line do |line|
      line = line.sub(/#.*/, "").strip
      next if line.empty?

      fields = line.split(";").map(&:strip)
      range = fields.shift
      start_cp, end_cp = parse_range(range)
      y << [start_cp, end_cp, *fields]
    end
  end
end

# Merge adjacent rows whose payloads are equal. Input/output is an
# array of [start, end, *payload].
def coalesce(rows)
  rows.sort_by! { |r| r[0] }

  out = []
  rows.each do |row|
    last = out.last
    if last && last[1] + 1 == row[0] && last[2..] == row[2..]
      last[1] = row[1]
    else
      out << row.dup
    end
  end

  out
end

# --- IdnaMappingTable -------------------------------------------------

def build_idna_table
  raw = read_ucd(VENDOR_DIR / "IdnaMappingTable.txt").map do |start_cp, end_cp, status, mapping, *_extra|
    [start_cp, end_cp, remap_idna_status(status), parse_mapping_field(mapping)]
  end

  coalesce(raw)
end

# --- DerivedBidiClass -------------------------------------------------

def build_bidi_table
  # `@missing` lines aren't parsed; defaults are L for unlisted code
  # points (per the file header). Code consumers of the table treat
  # absent ranges as :L.
  raw = read_ucd(VENDOR_DIR / "DerivedBidiClass.txt").map do |start_cp, end_cp, klass, *_|
    [start_cp, end_cp, klass.to_sym]
  end

  coalesce(raw)
end

# --- DerivedJoiningType -----------------------------------------------

def build_joining_table
  # Defaults to U (Non_Joining) for unlisted code points. Only T (Transparent)
  # and L/R/D matter for the ContextJ rules in RFC 5892.
  raw = read_ucd(VENDOR_DIR / "DerivedJoiningType.txt").map do |start_cp, end_cp, joining_type, *_|
    [start_cp, end_cp, joining_type.to_sym]
  end

  coalesce(raw)
end

# --- Virama set (Canonical_Combining_Class = 9) -----------------------

def build_virama_set
  # ContextJ rule for ZWJ/ZWNJ needs to know whether the preceding
  # character is a Virama. ~80 code points in Unicode 16; cheap to
  # store as a plain sorted array.
  viramas = []
  read_ucd(VENDOR_DIR / "DerivedCombiningClass.txt").each do |start_cp, end_cp, ccc, *_|
    next unless ccc == "9"

    (start_cp..end_cp).each { |cp| viramas << cp }
  end

  viramas.sort.uniq
end

# --- Emit Ruby --------------------------------------------------------

def emit_row_idna(row)
  start_cp, end_cp, status, mapping = row
  mapping_lit = mapping.nil? ? "nil" : mapping.inspect
  "    [0x#{start_cp.to_s(16).upcase}, 0x#{end_cp.to_s(16).upcase}, :#{status}, #{mapping_lit}]"
end

def emit_row_simple(row)
  start_cp, end_cp, value = row
  "    [0x#{start_cp.to_s(16).upcase}, 0x#{end_cp.to_s(16).upcase}, :#{value}]"
end

def emit
  idna = build_idna_table
  bidi = build_bidi_table
  join = build_joining_table
  viramas = build_virama_set

  warn("IDNA mapping rows: #{idna.length}")
  warn("Bidi class rows:   #{bidi.length}")
  warn("Joining type rows: #{join.length}")
  warn("Virama code points: #{viramas.length}")

  out = +<<~HEADER
    # frozen_string_literal: true

    # Generated by script/build_idna_tables.rb from Unicode 16.0.0
    # source files in vendor/unicode/. Re-run after upgrading.
    #
    # Tables are sorted, non-overlapping [start, end, value...] rows.
    # `IDNAData.lookup(table, cp)` does a binary search and returns
    # the matching row (or nil).

    module Dommy
      module Internal
        module IDNAData
          # [start, end, status, mapping_or_nil]
          # status ∈ :valid, :ignored, :mapped, :disallowed
          IDNA_MAPPING = [
  HEADER

  out << idna.map { |r| emit_row_idna(r) }.join(",\n") << "\n"
  out << "  ].freeze\n\n"
  out << "  # [start, end, bidi_class]\n"
  out << "  BIDI_CLASS = [\n"
  out << bidi.map { |r| emit_row_simple(r) }.join(",\n") << "\n"
  out << "  ].freeze\n\n"
  out << "  # [start, end, joining_type]\n"
  out << "  JOINING_TYPE = [\n"
  out << join.map { |r| emit_row_simple(r) }.join(",\n") << "\n"
  out << "  ].freeze\n\n"
  out << "  # Canonical_Combining_Class = 9 (Virama)\n"
  out << "  VIRAMA = ["
  out << viramas.map { |cp| "0x#{cp.to_s(16).upcase}" }.join(", ")
  out << "].freeze\n\n"
  out << <<~FOOTER
          # Binary search for `cp` in a sorted table of [start, end, ...]
          # rows. Returns the matching row or nil.
          def self.lookup(table, cp)
            lo = 0
            hi = table.length - 1
            while lo <= hi
              mid = (lo + hi) / 2
              row = table[mid]
              if cp < row[0]
                hi = mid - 1
              elsif cp > row[1]
                lo = mid + 1
              else
                return row
              end
            end

            nil
          end
          end
        end
      end
    FOOTER

  OUTPUT.write(out)
  warn("wrote #{OUTPUT} (#{OUTPUT.size} bytes)")
end

emit
